/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39

  Company:
      Microchip Technology, Inc.
 
  File Name:
     internal_resource.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef INTERNAL_RESOURCE_H_FILE
#define INTERNAL_RESOURCE_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION: Graphics Configuration
 * Overview:    This defines the size of the buffer used by font functions
 *              to retrieve font data from the external memory. The buffer
 *              size can be increased to accommodate large font sizes.
 *              The user must be aware of the expected glyph sizes of the 
 *              characters stored in the font table. 
 *              To modify the size used, declare this macro in the 
 *              GraphicsConfig.h file with the desired size.
 *
 * #define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE     (570)
 *****************************************************************************/

/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: Back_4bpp_16x16
 * Description:  16x16 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Back_4bpp_16x16;
#define Back_4bpp_16x16_WIDTH     (16)
#define Back_4bpp_16x16_HEIGHT    (16)
#define Back_4bpp_16x16_SIZE      (166)
/*********************************
 * Bitmap Structure
 * Label: MCHPFolderEmpty_8bpp_72x72
 * Description:  72x72 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR MCHPFolderEmpty_8bpp_72x72;
#define MCHPFolderEmpty_8bpp_72x72_WIDTH     (72)
#define MCHPFolderEmpty_8bpp_72x72_HEIGHT    (72)
#define MCHPFolderEmpty_8bpp_72x72_SIZE      (5702)
/*********************************
 * Bitmap Structure
 * Label: MCHPFolderFile_8bpp_72x72
 * Description:  72x72 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR MCHPFolderFile_8bpp_72x72;
#define MCHPFolderFile_8bpp_72x72_WIDTH     (72)
#define MCHPFolderFile_8bpp_72x72_HEIGHT    (72)
#define MCHPFolderFile_8bpp_72x72_SIZE      (10374)
/*********************************
 * Bitmap Structure
 * Label: MchpIcon
 * Description:  100x58 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR MchpIcon;
#define MchpIcon_WIDTH     (100)
#define MchpIcon_HEIGHT    (58)
#define MchpIcon_SIZE      (2938)
/*********************************
 * Bitmap Structure
 * Label: mouse
 * Description:  13x15 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mouse;
#define mouse_WIDTH     (13)
#define mouse_HEIGHT    (15)
#define mouse_SIZE      (143)
/*********************************
 * Bitmap Structure
 * Label: Pacman
 * Description:  90x50 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Pacman;
#define Pacman_WIDTH     (90)
#define Pacman_HEIGHT    (50)
#define Pacman_SIZE      (2288)
/*********************************
 * Bitmap Structure
 * Label: harmony
 * Description:  480x272 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR harmony;
#define harmony_WIDTH     (480)
#define harmony_HEIGHT    (272)
#define harmony_SIZE      (261126)
/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: clouds
 * Description:  141x107 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR clouds;
#define clouds_WIDTH     (141)
#define clouds_HEIGHT    (107)
#define clouds_SIZE      (2526)
/*****************************************************************************
 * SECTION:  Fonts
 *****************************************************************************/

/*********************************
 * Installed Font Structure
 * Label: Monospaced_bold_Bold_72
 * Description:  Height: 95 pixels, 1 bit per pixel, Range: '0' to '9'
 ***********************************/
extern const GFX_RESOURCE_HDR Monospaced_bold_Bold_72;
#define Monospaced_bold_Bold_72_SIZE    (5748)
/*********************************
 * Installed Font Structure
 * Label: Monospaced_plain_36
 * Description:  Height: 48 pixels, 1 bit per pixel, Range: ' ' to 'z'
 ***********************************/
extern const GFX_RESOURCE_HDR Monospaced_plain_36;
#define Monospaced_plain_36_SIZE    (13476)
/*********************************
 * TTF Font File Structure
 * Label: Gentium_16
 * Description:  Height: 19 pixels, 1 bit per pixel, Range: ' ' to '~'
 ***********************************/
extern const GFX_RESOURCE_HDR Gentium_16;
#define Gentium_16_SIZE    (2668)
#endif

