/*******************************************************************************
  MPLAB Harmony Graphics Composer Generated Definitions Header

  File Name:
    gfx_hgc_definitions.h

  Summary:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

  Description:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

    Created with MPLAB Harmony Version 2.01
*******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
Copyright (c) 2013-2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*******************************************************************************/
// DOM-IGNORE-END


#ifndef _GFX_HGC_DEFINITIONS_H
#define _GFX_HGC_DEFINITIONS_H

#include "system_config.h"
#include "system_definitions.h"

// DOM-IGNORE-BEGIN
#ifdef __cplusplus  // Provide C++ Compatibility

extern "C" {

#endif
// DOM-IGNORE-END 

typedef enum
{
    HGC_STATE_INIT = 0,
    HGC_STATE_RUNNING
} HGC_STATES;

typedef enum
{
    HGC_SCREEN_STATE_INIT = 0,
    HGC_SCREEN_STATE_SETUP_SCREEN_MainMenu,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_MainMenu,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_MainMenu,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_MainMenu,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_MainMenu,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_MainMenu,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_MainMenu,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_MainMenu,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_SlideShowInstructions,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_SlideShowInstructions,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Microchip,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Microchip,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Microchip,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Microchip,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Microchip,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Microchip,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Microchip,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Microchip,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_ScienceWorld,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_ScienceWorld,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_CoalHarbour,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_CoalHarbour,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_EnglishBay,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_EnglishBay,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_AutumnGrass,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_AutumnGrass,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_FalseCreek,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_FalseCreek,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_BoraBoraSunset,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_BoraBoraSunset,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_DowntownVancouver,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_DowntownVancouver,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_MacBethChart,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_MacBethChart,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Colors,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Colors,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Colors,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Colors,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Colors,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Colors,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Colors,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Colors,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Fishes,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Fishes,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Fishes,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Fishes,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Fishes,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Fishes,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Fishes,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Fishes,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_PartkTrees,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_PartkTrees,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Rockies,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Rockies,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Rockies,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Rockies,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Rockies,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Rockies,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Rockies,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Rockies,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_SnowLeopard,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_SnowLeopard,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_SnowHills,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_SnowHills,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_SnowHills,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_SnowHills,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_SnowHills,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_SnowHills,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_SnowHills,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_SnowHills,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Splash,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Splash,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Splash,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Splash,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Splash,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Splash,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Splash,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Splash,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Waterfall,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Waterfall,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Waterfall,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Waterfall,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Waterfall,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Waterfall,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Waterfall,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Waterfall,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Wheats,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Wheats,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Wheats,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Wheats,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Wheats,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Wheats,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Wheats,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Wheats,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Harmony,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Harmony,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Harmony,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Harmony,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Harmony,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Harmony,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Harmony,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Harmony,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_TouchTest,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_TouchTest,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_TouchTest,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_TouchTest,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_TouchTest,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_TouchTest,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_TouchTest,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_TouchTest,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Settings,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Settings,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Settings,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Settings,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Settings,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Settings,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Settings,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Settings,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_FeatureList,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_FeatureList,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_FeatureList,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_FeatureList,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_FeatureList,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_FeatureList,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_FeatureList,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_FeatureList,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Lines,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Lines,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Lines,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Lines,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Lines,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Lines,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Lines,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Lines,
	
} HGC_SCREEN_STATES;

/*** GFX GOL Scheme Definitions ***/

#define GFX_SCHEME_NAME_0                       "WindowScheme"
#define GFX_SCHEME_ALPHA_0                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_0      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_0     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_0          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_0        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_0         0x00

#define GFX_SCHEME_SECONDARY_COLOR_RED_0        0x00
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_0      0x00
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_0       0x00

#define GFX_SCHEME_DISABLED_COLOR_RED_0         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_0       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_0        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_0       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_0     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_0      0x00

#define GFX_SCHEME_EMBOSS_SIZE_0                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_0     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_0   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_0    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_0      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_0    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_0     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_0     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_0   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_0    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_0   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_0 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_0  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_0    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_0  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_0   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_0    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_0  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_0   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_0    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_0  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_0   0xFF

#define GFX_SCHEME_FILL_STYLE_0                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_0           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_1                       "default"
#define GFX_SCHEME_ALPHA_1                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_1      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_1     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_1          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_1        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_1         0x00

#define GFX_SCHEME_SECONDARY_COLOR_RED_1        0x00
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_1      0x00
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_1       0x00

#define GFX_SCHEME_DISABLED_COLOR_RED_1         0x00
#define GFX_SCHEME_DISABLED_COLOR_GREEN_1       0x00
#define GFX_SCHEME_DISABLED_COLOR_BLUE_1        0x00

#define GFX_SCHEME_BACKGROUND_COLOR_RED_1       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_1     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_1      0x00

#define GFX_SCHEME_EMBOSS_SIZE_1                0

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_1     0x00
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_1   0x00
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_1    0x00

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_1      0x00
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_1    0x00
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_1     0x00

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_1     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_1   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_1    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_1   0x00
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_1 0x00
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_1  0x00

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_1    0x00
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_1  0x00
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_1   0x00

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_1    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_1  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_1   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_1    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_1  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_1   0xFF

#define GFX_SCHEME_FILL_STYLE_1                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_1           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_2                       "ButtonTest"
#define GFX_SCHEME_ALPHA_2                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_2      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_2     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_2          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_2        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_2         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_2        0xF8
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_2      0xFC
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_2       0xF8

#define GFX_SCHEME_DISABLED_COLOR_RED_2         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_2       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_2        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_2       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_2     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_2      0x00

#define GFX_SCHEME_EMBOSS_SIZE_2                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_2     0xF8
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_2   0xFC
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_2    0xF8

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_2      0xF8
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_2    0xFC
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_2     0xF8

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_2     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_2   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_2    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_2   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_2 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_2  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_2    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_2  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_2   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_2    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_2  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_2   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_2    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_2  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_2   0xFF

#define GFX_SCHEME_FILL_STYLE_2                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_2           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_3                       "SimHeiTextLabel"
#define GFX_SCHEME_ALPHA_3                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_3      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_3     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_3          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_3        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_3         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_3        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_3      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_3       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_3         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_3       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_3        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_3       0xFF
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_3     0xFF
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_3      0xFF

#define GFX_SCHEME_EMBOSS_SIZE_3                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_3     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_3   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_3    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_3      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_3    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_3     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_3     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_3   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_3    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_3   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_3 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_3  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_3    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_3  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_3   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_3    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_3  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_3   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_3    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_3  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_3   0xFF

#define GFX_SCHEME_FILL_STYLE_3                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_3           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_4                       "TextLabelTheme"
#define GFX_SCHEME_ALPHA_4                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_4      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_4     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_4          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_4        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_4         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_4        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_4      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_4       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_4         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_4       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_4        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_4       0xFF
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_4     0xFF
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_4      0xFF

#define GFX_SCHEME_EMBOSS_SIZE_4                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_4     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_4   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_4    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_4      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_4    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_4     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_4     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_4   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_4    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_4   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_4 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_4  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_4    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_4  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_4   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_4    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_4  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_4   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_4    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_4  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_4   0xFF

#define GFX_SCHEME_FILL_STYLE_4                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_4           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_5                       "DigitalMeterScheme"
#define GFX_SCHEME_ALPHA_5                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_5      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_5     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_5          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_5        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_5         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_5        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_5      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_5       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_5         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_5       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_5        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_5       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_5     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_5      0x00

#define GFX_SCHEME_EMBOSS_SIZE_5                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_5     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_5   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_5    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_5      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_5    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_5     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_5     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_5   0xFC
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_5    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_5   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_5 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_5  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_5    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_5  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_5   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_5    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_5  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_5   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_5    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_5  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_5   0xFF

#define GFX_SCHEME_FILL_STYLE_5                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_5           GFX_BACKGROUND_NONE

		
/*** Screen IDs ***/
#define MainMenu                 0 
	
#define SlideShowInstructions                 1 
	
#define Microchip                 2 
	
#define ScienceWorld                 3 
	
#define CoalHarbour                 4 
	
#define EnglishBay                 5 
	
#define AutumnGrass                 6 
	
#define FalseCreek                 7 
	
#define BoraBoraSunset                 8 
	
#define DowntownVancouver                 9 
	
#define MacBethChart                 10 
	
#define Colors                 11 
	
#define Fishes                 12 
	
#define PartkTrees                 13 
	
#define Rockies                 14 
	
#define SnowLeopard                 15 
	
#define SnowHills                 16 
	
#define Splash                 17 
	
#define Waterfall                 18 
	
#define Wheats                 19 
	
#define Harmony                 20 
	
#define TouchTest                 21 
	
#define Settings                 22 
	
#define FeatureList                 23 
	
#define Lines                 24 
	
/*** GFX GOL Button Definitions ***/
#define GFX_BUTTON_LEFT_0            611
#define GFX_BUTTON_TOP_0             271
#define GFX_BUTTON_RIGHT_0           731
#define GFX_BUTTON_BOTTOM_0          391
#define GFX_BUTTON_TEXT_0            "0x0"
#define GFX_BUTTON_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_0          0
#define GFX_BUTTON_STATE_0           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_0     (GFX_RESOURCE_HDR*)&script_invert
#define GFX_BUTTON_RELEASE_IMAGE_0   (GFX_RESOURCE_HDR*)&script_outline
#define GFX_BUTTON_SCHEME_0          gfxScheme1
		
#define GFX_BUTTON_LEFT_1            246
#define GFX_BUTTON_TOP_1             272
#define GFX_BUTTON_RIGHT_1           366
#define GFX_BUTTON_BOTTOM_1          392
#define GFX_BUTTON_TEXT_1            "0x0"
#define GFX_BUTTON_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_1          0
#define GFX_BUTTON_STATE_1           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_1     (GFX_RESOURCE_HDR*)&location_pin
#define GFX_BUTTON_RELEASE_IMAGE_1   (GFX_RESOURCE_HDR*)&location_pin_outline
#define GFX_BUTTON_SCHEME_1          gfxScheme1
		
#define GFX_BUTTON_LEFT_2            434
#define GFX_BUTTON_TOP_2             271
#define GFX_BUTTON_RIGHT_2           554
#define GFX_BUTTON_BOTTOM_2          391
#define GFX_BUTTON_TEXT_2            "0x0"
#define GFX_BUTTON_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_2          0
#define GFX_BUTTON_STATE_2           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_2     (GFX_RESOURCE_HDR*)&cog
#define GFX_BUTTON_RELEASE_IMAGE_2   (GFX_RESOURCE_HDR*)&cog_outline
#define GFX_BUTTON_SCHEME_2          gfxScheme1
		
#define GFX_BUTTON_LEFT_3            78
#define GFX_BUTTON_TOP_3             271
#define GFX_BUTTON_RIGHT_3           198
#define GFX_BUTTON_BOTTOM_3          391
#define GFX_BUTTON_TEXT_3            "0x0"
#define GFX_BUTTON_ALIGNMENT_3       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_3          0
#define GFX_BUTTON_STATE_3           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_3     (GFX_RESOURCE_HDR*)&layers_image
#define GFX_BUTTON_RELEASE_IMAGE_3   (GFX_RESOURCE_HDR*)&layers_image_outline
#define GFX_BUTTON_SCHEME_3          gfxScheme1
		
#define GFX_BUTTON_LEFT_4            673
#define GFX_BUTTON_TOP_4             356
#define GFX_BUTTON_RIGHT_4           800
#define GFX_BUTTON_BOTTOM_4          480
#define GFX_BUTTON_TEXT_4            "0x0"
#define GFX_BUTTON_ALIGNMENT_4       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_4          0
#define GFX_BUTTON_STATE_4           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_4     (GFX_RESOURCE_HDR*)&layers_image
#define GFX_BUTTON_RELEASE_IMAGE_4   (GFX_RESOURCE_HDR*)&layers_image_outline
#define GFX_BUTTON_SCHEME_4          gfxScheme4
		
#define GFX_BUTTON_LEFT_5            671
#define GFX_BUTTON_TOP_5             351
#define GFX_BUTTON_RIGHT_5           799
#define GFX_BUTTON_BOTTOM_5          479
#define GFX_BUTTON_TEXT_5            "0x0"
#define GFX_BUTTON_ALIGNMENT_5       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_5          0
#define GFX_BUTTON_STATE_5           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_5     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_5   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_5          gfxScheme1
		
#define GFX_BUTTON_LEFT_6            671
#define GFX_BUTTON_TOP_6             351
#define GFX_BUTTON_RIGHT_6           799
#define GFX_BUTTON_BOTTOM_6          479
#define GFX_BUTTON_TEXT_6            "0x0"
#define GFX_BUTTON_ALIGNMENT_6       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_6          0
#define GFX_BUTTON_STATE_6           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_6     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_6   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_6          gfxScheme1
		
#define GFX_BUTTON_LEFT_7            671
#define GFX_BUTTON_TOP_7             351
#define GFX_BUTTON_RIGHT_7           799
#define GFX_BUTTON_BOTTOM_7          479
#define GFX_BUTTON_TEXT_7            "0x0"
#define GFX_BUTTON_ALIGNMENT_7       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_7          0
#define GFX_BUTTON_STATE_7           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_7     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_7   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_7          gfxScheme1
		
#define GFX_BUTTON_LEFT_8            671
#define GFX_BUTTON_TOP_8             351
#define GFX_BUTTON_RIGHT_8           799
#define GFX_BUTTON_BOTTOM_8          479
#define GFX_BUTTON_TEXT_8            "0x0"
#define GFX_BUTTON_ALIGNMENT_8       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_8          0
#define GFX_BUTTON_STATE_8           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_8     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_8   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_8          gfxScheme1
		
#define GFX_BUTTON_LEFT_9            671
#define GFX_BUTTON_TOP_9             351
#define GFX_BUTTON_RIGHT_9           799
#define GFX_BUTTON_BOTTOM_9          479
#define GFX_BUTTON_TEXT_9            "0x0"
#define GFX_BUTTON_ALIGNMENT_9       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_9          0
#define GFX_BUTTON_STATE_9           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_9     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_9   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_9          gfxScheme1
		
#define GFX_BUTTON_LEFT_10            671
#define GFX_BUTTON_TOP_10             351
#define GFX_BUTTON_RIGHT_10           799
#define GFX_BUTTON_BOTTOM_10          479
#define GFX_BUTTON_TEXT_10            "0x0"
#define GFX_BUTTON_ALIGNMENT_10       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_10          0
#define GFX_BUTTON_STATE_10           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_10     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_10   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_10          gfxScheme1
		
#define GFX_BUTTON_LEFT_11            671
#define GFX_BUTTON_TOP_11             351
#define GFX_BUTTON_RIGHT_11           799
#define GFX_BUTTON_BOTTOM_11          479
#define GFX_BUTTON_TEXT_11            "0x0"
#define GFX_BUTTON_ALIGNMENT_11       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_11          0
#define GFX_BUTTON_STATE_11           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_11     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_11   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_11          gfxScheme1
		
#define GFX_BUTTON_LEFT_12            671
#define GFX_BUTTON_TOP_12             351
#define GFX_BUTTON_RIGHT_12           799
#define GFX_BUTTON_BOTTOM_12          479
#define GFX_BUTTON_TEXT_12            "0x0"
#define GFX_BUTTON_ALIGNMENT_12       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_12          0
#define GFX_BUTTON_STATE_12           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_12     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_12   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_12          gfxScheme1
		
#define GFX_BUTTON_LEFT_13            671
#define GFX_BUTTON_TOP_13             351
#define GFX_BUTTON_RIGHT_13           799
#define GFX_BUTTON_BOTTOM_13          479
#define GFX_BUTTON_TEXT_13            "0x0"
#define GFX_BUTTON_ALIGNMENT_13       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_13          0
#define GFX_BUTTON_STATE_13           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_13     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_13   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_13          gfxScheme1
		
#define GFX_BUTTON_LEFT_14            671
#define GFX_BUTTON_TOP_14             351
#define GFX_BUTTON_RIGHT_14           799
#define GFX_BUTTON_BOTTOM_14          479
#define GFX_BUTTON_TEXT_14            "0x0"
#define GFX_BUTTON_ALIGNMENT_14       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_14          0
#define GFX_BUTTON_STATE_14           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_14     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_14   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_14          gfxScheme1
		
#define GFX_BUTTON_LEFT_15            671
#define GFX_BUTTON_TOP_15             351
#define GFX_BUTTON_RIGHT_15           799
#define GFX_BUTTON_BOTTOM_15          479
#define GFX_BUTTON_TEXT_15            "0x0"
#define GFX_BUTTON_ALIGNMENT_15       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_15          0
#define GFX_BUTTON_STATE_15           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_15     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_15   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_15          gfxScheme1
		
#define GFX_BUTTON_LEFT_16            671
#define GFX_BUTTON_TOP_16             351
#define GFX_BUTTON_RIGHT_16           799
#define GFX_BUTTON_BOTTOM_16          479
#define GFX_BUTTON_TEXT_16            "0x0"
#define GFX_BUTTON_ALIGNMENT_16       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_16          0
#define GFX_BUTTON_STATE_16           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_16     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_16   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_16          gfxScheme1
		
#define GFX_BUTTON_LEFT_17            671
#define GFX_BUTTON_TOP_17             351
#define GFX_BUTTON_RIGHT_17           799
#define GFX_BUTTON_BOTTOM_17          479
#define GFX_BUTTON_TEXT_17            "0x0"
#define GFX_BUTTON_ALIGNMENT_17       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_17          0
#define GFX_BUTTON_STATE_17           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_17     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_17   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_17          gfxScheme1
		
#define GFX_BUTTON_LEFT_18            671
#define GFX_BUTTON_TOP_18             351
#define GFX_BUTTON_RIGHT_18           799
#define GFX_BUTTON_BOTTOM_18          479
#define GFX_BUTTON_TEXT_18            "0x0"
#define GFX_BUTTON_ALIGNMENT_18       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_18          0
#define GFX_BUTTON_STATE_18           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_18     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_18   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_18          gfxScheme1
		
#define GFX_BUTTON_LEFT_19            671
#define GFX_BUTTON_TOP_19             351
#define GFX_BUTTON_RIGHT_19           799
#define GFX_BUTTON_BOTTOM_19          479
#define GFX_BUTTON_TEXT_19            "0x0"
#define GFX_BUTTON_ALIGNMENT_19       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_19          0
#define GFX_BUTTON_STATE_19           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_19     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_19   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_19          gfxScheme1
		
#define GFX_BUTTON_LEFT_20            671
#define GFX_BUTTON_TOP_20             351
#define GFX_BUTTON_RIGHT_20           799
#define GFX_BUTTON_BOTTOM_20          479
#define GFX_BUTTON_TEXT_20            "0x0"
#define GFX_BUTTON_ALIGNMENT_20       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_20          0
#define GFX_BUTTON_STATE_20           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_20     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_20   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_20          gfxScheme1
		
#define GFX_BUTTON_LEFT_21            671
#define GFX_BUTTON_TOP_21             351
#define GFX_BUTTON_RIGHT_21           799
#define GFX_BUTTON_BOTTOM_21          479
#define GFX_BUTTON_TEXT_21            "0x0"
#define GFX_BUTTON_ALIGNMENT_21       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_21          0
#define GFX_BUTTON_STATE_21           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_21     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_21   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_21          gfxScheme1
		
#define GFX_BUTTON_LEFT_22            671
#define GFX_BUTTON_TOP_22             351
#define GFX_BUTTON_RIGHT_22           799
#define GFX_BUTTON_BOTTOM_22          479
#define GFX_BUTTON_TEXT_22            "0x0"
#define GFX_BUTTON_ALIGNMENT_22       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_22          0
#define GFX_BUTTON_STATE_22           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_22     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_22   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_22          gfxScheme1
		
#define GFX_BUTTON_LEFT_23            671
#define GFX_BUTTON_TOP_23             351
#define GFX_BUTTON_RIGHT_23           799
#define GFX_BUTTON_BOTTOM_23          479
#define GFX_BUTTON_TEXT_23            "0x0"
#define GFX_BUTTON_ALIGNMENT_23       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_23          0
#define GFX_BUTTON_STATE_23           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_23     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_23   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_23          gfxScheme1
		
#define GFX_BUTTON_LEFT_24            671
#define GFX_BUTTON_TOP_24             351
#define GFX_BUTTON_RIGHT_24           799
#define GFX_BUTTON_BOTTOM_24          479
#define GFX_BUTTON_TEXT_24            "0x0"
#define GFX_BUTTON_ALIGNMENT_24       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_24          0
#define GFX_BUTTON_STATE_24           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_24     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_24   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_24          gfxScheme1
		
#define GFX_BUTTON_LEFT_25            671
#define GFX_BUTTON_TOP_25             351
#define GFX_BUTTON_RIGHT_25           799
#define GFX_BUTTON_BOTTOM_25          479
#define GFX_BUTTON_TEXT_25            "0x0"
#define GFX_BUTTON_ALIGNMENT_25       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_25          0
#define GFX_BUTTON_STATE_25           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_25     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_25   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_25          gfxScheme1
		
#define GFX_BUTTON_LEFT_26            671
#define GFX_BUTTON_TOP_26             351
#define GFX_BUTTON_RIGHT_26           799
#define GFX_BUTTON_BOTTOM_26          479
#define GFX_BUTTON_TEXT_26            "0x0"
#define GFX_BUTTON_ALIGNMENT_26       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_26          0
#define GFX_BUTTON_STATE_26           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_NOPANEL_STATE
#define GFX_BUTTON_PRESS_IMAGE_26     (GFX_RESOURCE_HDR*)&RoundHomeButton
#define GFX_BUTTON_RELEASE_IMAGE_26   (GFX_RESOURCE_HDR*)&RoundHomeButton_Outline
#define GFX_BUTTON_SCHEME_26          gfxScheme1
		
/*** Button IDs ***/
#define FeatureListButton                  1000 
	
#define TouchButton                  1001 
	
#define SettingsButton                  1002 
	
#define SlidesButton                  1003 
	
#define Button23                  1004 
	
#define Button7                  1005 
	
#define Button1                  1006 
	
#define Button2                  1007 
	
#define Button3                  1008 
	
#define Button8                  1009 
	
#define Button9                  1010 
	
#define Button10                  1011 
	
#define Button11                  1012 
	
#define Button13                  1013 
	
#define Button24                  1014 
	
#define Button14                  1015 
	
#define Button15                  1016 
	
#define Button16                  1017 
	
#define Button18                  1018 
	
#define Button19                  1019 
	
#define Button20                  1020 
	
#define Button21                  1021 
	
#define Button22                  1022 
	
#define Button12                  1023 
	
#define Button4                  1024 
	
#define Button5                  1025 
	
#define Button6                  1026 
	
/*** GFX GOL Digital Meter Definitions ***/

#define GFX_DGTL_MTR_LEFT_0            691
#define GFX_DGTL_MTR_TOP_0             69
#define GFX_DGTL_MTR_RIGHT_0           778
#define GFX_DGTL_MTR_BOTTOM_0          106
#define GFX_DGTL_MTR_STATE_0           GFX_GOL_DIGITALMETER_DRAW_STATE | GFX_GOL_DIGITALMETER_FRAME_STATE
#define GFX_DGTL_MTR_VALUE_0           0
#define GFX_DGTL_MTR_NO_OF_DIGITS_0    3
#define GFX_DGTL_MTR_DOT_POSITION_0    0
#define GFX_DGTL_MTR_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_DGTL_MTR_SCHEME_0          gfxScheme5
		

#define GFX_DGTL_MTR_LEFT_1            691
#define GFX_DGTL_MTR_TOP_1             19
#define GFX_DGTL_MTR_RIGHT_1           778
#define GFX_DGTL_MTR_BOTTOM_1          56
#define GFX_DGTL_MTR_STATE_1           GFX_GOL_DIGITALMETER_DRAW_STATE | GFX_GOL_DIGITALMETER_FRAME_STATE
#define GFX_DGTL_MTR_VALUE_1           0
#define GFX_DGTL_MTR_NO_OF_DIGITS_1    3
#define GFX_DGTL_MTR_DOT_POSITION_1    0
#define GFX_DGTL_MTR_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_DGTL_MTR_SCHEME_1          gfxScheme5
		
/*** Digital Meter IDs ***/
#define YPos                  2000 
	
#define XPos                  2001 
	
/*** GFX GOL Radio Button Definitions ***/

#define GFX_RADIOBUTTON_LEFT_0            469
#define GFX_RADIOBUTTON_TOP_0             327
#define GFX_RADIOBUTTON_RIGHT_0           700
#define GFX_RADIOBUTTON_BOTTOM_0          377
#define GFX_RADIOBUTTON_TEXT_0            "0x0"
#define GFX_RADIOBUTTON_STATE_0    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_0          gfxScheme4
#define GFX_RADIOBUTTON_GROUPNO_0          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_0   1
		

#define GFX_RADIOBUTTON_LEFT_1            69
#define GFX_RADIOBUTTON_TOP_1             403
#define GFX_RADIOBUTTON_RIGHT_1           438
#define GFX_RADIOBUTTON_BOTTOM_1          453
#define GFX_RADIOBUTTON_TEXT_1            "0x0"
#define GFX_RADIOBUTTON_STATE_1    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_1          gfxScheme4
#define GFX_RADIOBUTTON_GROUPNO_1          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_1   1
		

#define GFX_RADIOBUTTON_LEFT_2            69
#define GFX_RADIOBUTTON_TOP_2             327
#define GFX_RADIOBUTTON_RIGHT_2           439
#define GFX_RADIOBUTTON_BOTTOM_2          377
#define GFX_RADIOBUTTON_TEXT_2            "0x0"
#define GFX_RADIOBUTTON_STATE_2    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_GROUP_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_2          gfxScheme4
#define GFX_RADIOBUTTON_GROUPNO_2          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_2   1
		
/*** Radio Button IDs ***/
#define RadioButtonEnglish                  4000 
	
#define RadioButtonChineseSimpl                  4001 
	
#define RadioButtonChineseTrad                  4002 
	
/*** GFX GOL Scrollbar Definitions ***/
#define GFX_SCROLLBAR_LEFT_0            	100
#define GFX_SCROLLBAR_TOP_0             	115
#define GFX_SCROLLBAR_RIGHT_0           	700
#define GFX_SCROLLBAR_BOTTOM_0          	235
#define GFX_SCROLLBAR_STATE_0            GFX_GOL_SCROLLBAR_DRAW_STATE | GFX_GOL_SCROLLBAR_DRAW_THUMB_STATE | GFX_GOL_SCROLLBAR_SLIDER_MODE_STATE
#define GFX_SCROLLBAR_RANGE_0            5
#define GFX_SCROLLBAR_PAGE_0             1
#define GFX_SCROLLBAR_POS_0              2
#define GFX_SCROLLBAR_SCHEME_0           gfxScheme4
		
/*** Scrollbar IDs ***/
#define Slider1                  5000 
	
/*** GFX GOL Button Definitions ***/
#define GFX_STATICTEXT_LEFT_0            20
#define GFX_STATICTEXT_TOP_0             190
#define GFX_STATICTEXT_RIGHT_0           780
#define GFX_STATICTEXT_BOTTOM_0          250
#define GFX_STATICTEXT_STATE_0          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_0            "0x50, 0x49, 0x43, 0x33, 0x32, 0x20, 0x48, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x20, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x73, 0x20, 0x53, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73, 0x65, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_0          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_1            60
#define GFX_STATICTEXT_TOP_1             401
#define GFX_STATICTEXT_RIGHT_1           212
#define GFX_STATICTEXT_BOTTOM_1          450
#define GFX_STATICTEXT_STATE_1          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_1            "0x53, 0x6c, 0x69, 0x64, 0x65, 0x73, 0x68, 0x6f, 0x77, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_1          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_2            232
#define GFX_STATICTEXT_TOP_2             401
#define GFX_STATICTEXT_RIGHT_2           409
#define GFX_STATICTEXT_BOTTOM_2          451
#define GFX_STATICTEXT_STATE_2          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_2            "0x54, 0x6f, 0x75, 0x63, 0x68, 0x20, 0x54, 0x65, 0x73, 0x74, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_2          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_3            422
#define GFX_STATICTEXT_TOP_3             401
#define GFX_STATICTEXT_RIGHT_3           564
#define GFX_STATICTEXT_BOTTOM_3          450
#define GFX_STATICTEXT_STATE_3          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_3            "0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_3       GFX_ALIGN_HCENTER | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_3          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_4            583
#define GFX_STATICTEXT_TOP_4             402
#define GFX_STATICTEXT_RIGHT_4           757
#define GFX_STATICTEXT_BOTTOM_4          450
#define GFX_STATICTEXT_STATE_4          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_4            "0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_4       GFX_ALIGN_HCENTER | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_4          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_5            422
#define GFX_STATICTEXT_TOP_5             402
#define GFX_STATICTEXT_RIGHT_5           563
#define GFX_STATICTEXT_BOTTOM_5          447
#define GFX_STATICTEXT_STATE_5          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_5            "0x3c, 0x34, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_5       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_5          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_6            422
#define GFX_STATICTEXT_TOP_6             402
#define GFX_STATICTEXT_RIGHT_6           563
#define GFX_STATICTEXT_BOTTOM_6          447
#define GFX_STATICTEXT_STATE_6          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_6            "0x3a, 0x34, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_6       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_6          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_7            232
#define GFX_STATICTEXT_TOP_7             401
#define GFX_STATICTEXT_RIGHT_7           408
#define GFX_STATICTEXT_BOTTOM_7          446
#define GFX_STATICTEXT_STATE_7          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_7            "0x37, 0x26, 0x3f, 0x22, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_7       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_7          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_8            232
#define GFX_STATICTEXT_TOP_8             401
#define GFX_STATICTEXT_RIGHT_8           407
#define GFX_STATICTEXT_BOTTOM_8          446
#define GFX_STATICTEXT_STATE_8          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_8            "0x38, 0x26, 0x3e, 0x22, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_8       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_8          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_9            583
#define GFX_STATICTEXT_TOP_9             402
#define GFX_STATICTEXT_RIGHT_9           756
#define GFX_STATICTEXT_BOTTOM_9          447
#define GFX_STATICTEXT_STATE_9          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_9            "0x2b, 0x2f, 0x23, 0x35, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_9       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_9          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_10            60
#define GFX_STATICTEXT_TOP_10             401
#define GFX_STATICTEXT_RIGHT_10           211
#define GFX_STATICTEXT_BOTTOM_10          446
#define GFX_STATICTEXT_STATE_10          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_10            "0x24, 0x2d, 0x2e, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_10       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_10          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_11            60
#define GFX_STATICTEXT_TOP_11             401
#define GFX_STATICTEXT_RIGHT_11           211
#define GFX_STATICTEXT_BOTTOM_11          446
#define GFX_STATICTEXT_STATE_11          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_11            "0x24, 0x2c, 0x2e, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_11       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_11          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_12            51
#define GFX_STATICTEXT_TOP_12             22
#define GFX_STATICTEXT_RIGHT_12           762
#define GFX_STATICTEXT_BOTTOM_12          357
#define GFX_STATICTEXT_STATE_12          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE
#define GFX_STATICTEXT_TEXT_12            "0x53, 0x6c, 0x69, 0x64, 0x65, 0x73, 0x68, 0x6f, 0x77, 0x20, 0x54, 0x69, 0x70, 0x73, 0xA, 0xA, 0x31, 0x29, 0x20, 0x54, 0x61, 0x70, 0x20, 0x74, 0x6f, 0x20, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x20, 0x74, 0x6f, 0x20, 0x74, 0x68, 0x65, 0x20, 0x6e, 0x65, 0x78, 0x74, 0x20, 0x73, 0x6c, 0x69, 0x64, 0x65, 0xA, 0x32, 0x29, 0x20, 0x50, 0x72, 0x65, 0x73, 0x73, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x68, 0x6f, 0x6c, 0x64, 0x20, 0x74, 0x6f, 0x20, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x20, 0x6f, 0x6e, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x20, 0xA, 0x20, 0x20, 0x20, 0x69, 0x6d, 0x61, 0x67, 0x65, 0xA, 0x33, 0x29, 0x20, 0x50, 0x72, 0x65, 0x73, 0x73, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x69, 0x63, 0x6f, 0x6e, 0x20, 0x74, 0x6f, 0x20, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x20, 0x74, 0x6f, 0x20, 0x74, 0x68, 0x65, 0x20, 0x6d, 0x61, 0x69, 0x6e, 0x20, 0x6d, 0x65, 0x6e, 0x75, 0xA, 0xA, 0x34, 0x29, 0x20, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x20, 0x70, 0x61, 0x75, 0x73, 0x65, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x20, 0x74, 0x69, 0x6d, 0x65, 0x20, 0x63, 0x61, 0x6e, 0x20, 0x62, 0x65, 0x20, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x20, 0xA, 0x20, 0x20, 0x20, 0x76, 0x69, 0x61, 0x20, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0xA, 0x35, 0x29, 0x20, 0x50, 0x72, 0x65, 0x73, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20, 0x69, 0x63, 0x6f, 0x6e, 0x20, 0x62, 0x65, 0x6c, 0x6f, 0x77, 0x20, 0x74, 0x6f, 0x20, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_12       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_12          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_13            650
#define GFX_STATICTEXT_TOP_13             69
#define GFX_STATICTEXT_RIGHT_13           689
#define GFX_STATICTEXT_BOTTOM_13          109
#define GFX_STATICTEXT_STATE_13          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_13            "0x59, 0x3a, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_13       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_13          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_14            650
#define GFX_STATICTEXT_TOP_14             19
#define GFX_STATICTEXT_RIGHT_14           689
#define GFX_STATICTEXT_BOTTOM_14          59
#define GFX_STATICTEXT_STATE_14          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_14            "0x58, 0x3a, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_14       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_14          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_15            541
#define GFX_STATICTEXT_TOP_15             60
#define GFX_STATICTEXT_RIGHT_15           596
#define GFX_STATICTEXT_BOTTOM_15          110
#define GFX_STATICTEXT_STATE_15          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_15            "0x73, 0x65, 0x63, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_15       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_15          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_16            545
#define GFX_STATICTEXT_TOP_16             60
#define GFX_STATICTEXT_RIGHT_16           590
#define GFX_STATICTEXT_BOTTOM_16          105
#define GFX_STATICTEXT_STATE_16          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_16            "0x30, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_16       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_16          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_17            591
#define GFX_STATICTEXT_TOP_17             60
#define GFX_STATICTEXT_RIGHT_17           651
#define GFX_STATICTEXT_BOTTOM_17          110
#define GFX_STATICTEXT_STATE_17          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_17            "0x29, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_17       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_17          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_18            147
#define GFX_STATICTEXT_TOP_18             60
#define GFX_STATICTEXT_RIGHT_18           487
#define GFX_STATICTEXT_BOTTOM_18          109
#define GFX_STATICTEXT_STATE_18          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_18            "0x53, 0x6c, 0x69, 0x64, 0x65, 0x20, 0x50, 0x61, 0x75, 0x73, 0x65, 0x20, 0x54, 0x69, 0x6d, 0x65, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_18       GFX_ALIGN_RIGHT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_18          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_19            205
#define GFX_STATICTEXT_TOP_19             60
#define GFX_STATICTEXT_RIGHT_19           478
#define GFX_STATICTEXT_BOTTOM_19          105
#define GFX_STATICTEXT_STATE_19          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_19            "0x24, 0x2d, 0x2e, 0x42, 0x44, 0x2a, 0x42, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_19       GFX_ALIGN_RIGHT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_19          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_20            205
#define GFX_STATICTEXT_TOP_20             60
#define GFX_STATICTEXT_RIGHT_20           477
#define GFX_STATICTEXT_BOTTOM_20          105
#define GFX_STATICTEXT_STATE_20          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_20            "0x24, 0x2c, 0x2e, 0x43, 0x44, 0x29, 0x43, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_20       GFX_ALIGN_RIGHT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_20          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_21            276
#define GFX_STATICTEXT_TOP_21             255
#define GFX_STATICTEXT_RIGHT_21           516
#define GFX_STATICTEXT_BOTTOM_21          305
#define GFX_STATICTEXT_STATE_21          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_21            "0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x20, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_21       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_21          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_22            276
#define GFX_STATICTEXT_TOP_22             260
#define GFX_STATICTEXT_RIGHT_22           517
#define GFX_STATICTEXT_BOTTOM_22          305
#define GFX_STATICTEXT_STATE_22          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_22            "0x3b, 0x39, 0x41, 0x27, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_22       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_22          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_23            276
#define GFX_STATICTEXT_TOP_23             260
#define GFX_STATICTEXT_RIGHT_23           515
#define GFX_STATICTEXT_BOTTOM_23          305
#define GFX_STATICTEXT_STATE_23          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_23            "0x3d, 0x39, 0x40, 0x25, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_23       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_23          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_24            133
#define GFX_STATICTEXT_TOP_24             403
#define GFX_STATICTEXT_RIGHT_24           425
#define GFX_STATICTEXT_BOTTOM_24          448
#define GFX_STATICTEXT_STATE_24          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_24            "0x43, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x20, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_24       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_24          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_25            133
#define GFX_STATICTEXT_TOP_25             328
#define GFX_STATICTEXT_RIGHT_25           425
#define GFX_STATICTEXT_BOTTOM_25          373
#define GFX_STATICTEXT_STATE_25          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_25            "0x43, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x20, 0x54, 0x72, 0x61, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_25       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_25          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_26            133
#define GFX_STATICTEXT_TOP_26             403
#define GFX_STATICTEXT_RIGHT_26           439
#define GFX_STATICTEXT_BOTTOM_26          448
#define GFX_STATICTEXT_STATE_26          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_26            "0x31, 0x21, 0x20, 0x28, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_26       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_26          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_27            138
#define GFX_STATICTEXT_TOP_27             326
#define GFX_STATICTEXT_RIGHT_27           424
#define GFX_STATICTEXT_BOTTOM_27          371
#define GFX_STATICTEXT_STATE_27          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_27            "0x33, 0x45, 0x20, 0x28, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_27       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_27          gfxScheme3
		
#define GFX_STATICTEXT_LEFT_28            545
#define GFX_STATICTEXT_TOP_28             328
#define GFX_STATICTEXT_RIGHT_28           660
#define GFX_STATICTEXT_BOTTOM_28          377
#define GFX_STATICTEXT_STATE_28          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_28            "0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_28       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_28          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_29            496
#define GFX_STATICTEXT_TOP_29             60
#define GFX_STATICTEXT_RIGHT_29           517
#define GFX_STATICTEXT_BOTTOM_29          109
#define GFX_STATICTEXT_STATE_29          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_29            "0x28, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_29       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_29          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_30            516
#define GFX_STATICTEXT_TOP_30             60
#define GFX_STATICTEXT_RIGHT_30           542
#define GFX_STATICTEXT_BOTTOM_30          109
#define GFX_STATICTEXT_STATE_30          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_30            "0x32, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_30       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_30          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_31            704
#define GFX_STATICTEXT_TOP_31             140
#define GFX_STATICTEXT_RIGHT_31           741
#define GFX_STATICTEXT_BOTTOM_31          186
#define GFX_STATICTEXT_STATE_31          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_31            "0x35, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_31       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_31          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_32            60
#define GFX_STATICTEXT_TOP_32             151
#define GFX_STATICTEXT_RIGHT_32           97
#define GFX_STATICTEXT_BOTTOM_32          197
#define GFX_STATICTEXT_STATE_32          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_32            "0x30, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_32       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_STATICTEXT_SCHEME_32          gfxScheme4
		
#define GFX_STATICTEXT_LEFT_33            21
#define GFX_STATICTEXT_TOP_33             22
#define GFX_STATICTEXT_RIGHT_33           776
#define GFX_STATICTEXT_BOTTOM_33          390
#define GFX_STATICTEXT_STATE_33          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_HIDE_STATE | GFX_GOL_STATICTEXT_NOBACKGROUND_STATE
#define GFX_STATICTEXT_TEXT_33            "0x44, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x64, 0x20, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0xA, 0xA, 0x57, 0x56, 0x47, 0x41, 0x20, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0xA, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x65, 0x64, 0x20, 0x4d, 0x54, 0x43, 0x48, 0x36, 0x33, 0x30, 0x33, 0x20, 0x50, 0x43, 0x41, 0x50, 0x20, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x20, 0x69, 0x6e, 0x70, 0x75, 0x74, 0xA, 0x4c, 0x6f, 0x77, 0x2d, 0x43, 0x6f, 0x73, 0x74, 0x20, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2d, 0x6c, 0x65, 0x73, 0x73, 0x20, 0x47, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x73, 0x20, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0xA, 0x31, 0x36, 0x2d, 0x62, 0x69, 0x74, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x20, 0x64, 0x65, 0x70, 0x74, 0x68, 0x20, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x20, 0x28, 0x36, 0x35, 0x35, 0x33, 0x35, 0x20, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x20, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x29, 0xA, 0x4a, 0x50, 0x45, 0x47, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x42, 0x4d, 0x50, 0x20, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x20, 0x6f, 0x6e, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x20, 0x66, 0x6c, 0x61, 0x73, 0x68, 0xA, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x74, 0x69, 0x6d, 0x65, 0x20, 0x4a, 0x50, 0x45, 0x47, 0x20, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0xA, 0x31, 0x36, 0x2d, 0x62, 0x69, 0x74, 0x20, 0x55, 0x6e, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x20, 0x66, 0x6f, 0x6e, 0x74, 0x20, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0xA, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x6c, 0x20, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x20, 0x6d, 0x65, 0x6e, 0x75, 0x20, 0x28, 0x43, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x20, 0x54, 0x72, 0x61, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x20, 0xA, 0x61, 0x6e, 0x64, 0x20, 0x43, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x65, 0x20, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x29, 0xA, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_33       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_33          gfxScheme4
		
/*** static text IDs ***/
#define e_st_DemoName                  9000 
	
#define e_st_Slideshow                  9001 
	
#define e_st_TouchTest                  9002 
	
#define e_st_Settings                  9003 
	
#define e_st_Features                  9004 
	
#define cs_st_Settings                  9005 
	
#define ct_st_Settings                  9006 
	
#define cs_st_TouchTest                  9007 
	
#define ct_st_TouchTest                  9008 
	
#define c_st_Features                  9009 
	
#define ct_st_SlideShow                  9010 
	
#define cs_st_SlideShow                  9011 
	
#define e_st_SlideShowTips                  9012 
	
#define StaticText11                  9013 
	
#define StaticText10                  9014 
	
#define e_st_Second                  9015 
	
#define c_st_Second                  9016 
	
#define e_st_CloseBracket                  9017 
	
#define e_st_SlidePauseTime                  9018 
	
#define ct_st_SlidePauseTime                  9019 
	
#define cs_st_SlidePauseTime                  9020 
	
#define e_st_SelectLanguage                  9021 
	
#define ct_st_SelectLanguage                  9022 
	
#define cs_st_SelectLanguage                  9023 
	
#define e_st_ChineseSimplified                  9024 
	
#define e_st_ChineseTraditional                  9025 
	
#define cs_st_ChineseSimplified                  9026 
	
#define ct_st_ChineseTraditional                  9027 
	
#define e_st_English                  9028 
	
#define e_st_OpenBracket                  9029 
	
#define SecondsString                  9030 
	
#define e_st_5                  9031 
	
#define e_st_0                  9032 
	
#define e_st_DemonstratedFeatures                  9033 
	
/*** GFX GOL windows Definitions ***/
#define GFX_WINDOW_LEFT_0            30
#define GFX_WINDOW_TOP_0             30
#define GFX_WINDOW_RIGHT_0           620
#define GFX_WINDOW_BOTTOM_0          449
#define GFX_WINDOW_STATE_0           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_0           NULL
#define GFX_WINDOW_TEXT_0            "0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x0"
#define GFX_WINDOW_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_0          gfxScheme1
		
/*** Window IDs ***/
#define TouchArea                  11000 
	
/*** GFX GOL windows Definitions ***/
#define GFX_PICTURE_LEFT_0            180
#define GFX_PICTURE_TOP_0             140
#define GFX_PICTURE_RIGHT_0           269
#define GFX_PICTURE_BOTTOM_0          229
#define GFX_PICTURE_STATE_0          GFX_GOL_PICTURECONTROL_DRAW_STATE | GFX_GOL_PICTURECONTROL_HIDE_STATE
#define GFX_PICTURE_SCALE_0       1
#define GFX_PICTURE_SCHEME_0          gfxScheme4
		
#define GFX_PICTURE_LEFT_1            51
#define GFX_PICTURE_TOP_1             34
#define GFX_PICTURE_RIGHT_1           733
#define GFX_PICTURE_BOTTOM_1          343
#define GFX_PICTURE_STATE_1          GFX_GOL_PICTURECONTROL_DRAW_STATE | GFX_GOL_PICTURECONTROL_HIDE_STATE
#define GFX_PICTURE_SCALE_1       1
#define GFX_PICTURE_SCHEME_1          gfxScheme4
		
#define GFX_PICTURE_LEFT_2            51
#define GFX_PICTURE_TOP_2             34
#define GFX_PICTURE_RIGHT_2           734
#define GFX_PICTURE_BOTTOM_2          344
#define GFX_PICTURE_STATE_2          GFX_GOL_PICTURECONTROL_DRAW_STATE | GFX_GOL_PICTURECONTROL_HIDE_STATE
#define GFX_PICTURE_SCALE_2       1
#define GFX_PICTURE_SCHEME_2          gfxScheme4
		
#define GFX_PICTURE_LEFT_3            0
#define GFX_PICTURE_TOP_3             0
#define GFX_PICTURE_RIGHT_3           800
#define GFX_PICTURE_BOTTOM_3          480
#define GFX_PICTURE_STATE_3          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_3       1
#define GFX_PICTURE_SCHEME_3          gfxScheme1
		
#define GFX_PICTURE_LEFT_4            0
#define GFX_PICTURE_TOP_4             0
#define GFX_PICTURE_RIGHT_4           800
#define GFX_PICTURE_BOTTOM_4          480
#define GFX_PICTURE_STATE_4          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_4       1
#define GFX_PICTURE_SCHEME_4          gfxScheme1
		
#define GFX_PICTURE_LEFT_5            1
#define GFX_PICTURE_TOP_5             0
#define GFX_PICTURE_RIGHT_5           801
#define GFX_PICTURE_BOTTOM_5          480
#define GFX_PICTURE_STATE_5          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_5       1
#define GFX_PICTURE_SCHEME_5          gfxScheme1
		
#define GFX_PICTURE_LEFT_6            0
#define GFX_PICTURE_TOP_6             0
#define GFX_PICTURE_RIGHT_6           800
#define GFX_PICTURE_BOTTOM_6          480
#define GFX_PICTURE_STATE_6          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_6       1
#define GFX_PICTURE_SCHEME_6          gfxScheme1
		
#define GFX_PICTURE_LEFT_7            0
#define GFX_PICTURE_TOP_7             0
#define GFX_PICTURE_RIGHT_7           800
#define GFX_PICTURE_BOTTOM_7          480
#define GFX_PICTURE_STATE_7          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_7       1
#define GFX_PICTURE_SCHEME_7          gfxScheme1
		
#define GFX_PICTURE_LEFT_8            0
#define GFX_PICTURE_TOP_8             0
#define GFX_PICTURE_RIGHT_8           800
#define GFX_PICTURE_BOTTOM_8          480
#define GFX_PICTURE_STATE_8          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_8       1
#define GFX_PICTURE_SCHEME_8          gfxScheme1
		
#define GFX_PICTURE_LEFT_9            0
#define GFX_PICTURE_TOP_9             0
#define GFX_PICTURE_RIGHT_9           800
#define GFX_PICTURE_BOTTOM_9          480
#define GFX_PICTURE_STATE_9          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_9       1
#define GFX_PICTURE_SCHEME_9          gfxScheme1
		
#define GFX_PICTURE_LEFT_10            0
#define GFX_PICTURE_TOP_10             0
#define GFX_PICTURE_RIGHT_10           800
#define GFX_PICTURE_BOTTOM_10          480
#define GFX_PICTURE_STATE_10          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_10       1
#define GFX_PICTURE_SCHEME_10          gfxScheme1
		
#define GFX_PICTURE_LEFT_11            0
#define GFX_PICTURE_TOP_11             0
#define GFX_PICTURE_RIGHT_11           800
#define GFX_PICTURE_BOTTOM_11          480
#define GFX_PICTURE_STATE_11          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_11       1
#define GFX_PICTURE_SCHEME_11          gfxScheme1
		
#define GFX_PICTURE_LEFT_12            0
#define GFX_PICTURE_TOP_12             0
#define GFX_PICTURE_RIGHT_12           800
#define GFX_PICTURE_BOTTOM_12          480
#define GFX_PICTURE_STATE_12          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_12       1
#define GFX_PICTURE_SCHEME_12          gfxScheme1
		
#define GFX_PICTURE_LEFT_13            0
#define GFX_PICTURE_TOP_13             0
#define GFX_PICTURE_RIGHT_13           800
#define GFX_PICTURE_BOTTOM_13          480
#define GFX_PICTURE_STATE_13          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_13       1
#define GFX_PICTURE_SCHEME_13          gfxScheme1
		
#define GFX_PICTURE_LEFT_14            0
#define GFX_PICTURE_TOP_14             0
#define GFX_PICTURE_RIGHT_14           800
#define GFX_PICTURE_BOTTOM_14          480
#define GFX_PICTURE_STATE_14          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_14       1
#define GFX_PICTURE_SCHEME_14          gfxScheme1
		
#define GFX_PICTURE_LEFT_15            0
#define GFX_PICTURE_TOP_15             0
#define GFX_PICTURE_RIGHT_15           800
#define GFX_PICTURE_BOTTOM_15          480
#define GFX_PICTURE_STATE_15          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_15       1
#define GFX_PICTURE_SCHEME_15          gfxScheme1
		
#define GFX_PICTURE_LEFT_16            0
#define GFX_PICTURE_TOP_16             0
#define GFX_PICTURE_RIGHT_16           800
#define GFX_PICTURE_BOTTOM_16          480
#define GFX_PICTURE_STATE_16          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_16       1
#define GFX_PICTURE_SCHEME_16          gfxScheme1
		
#define GFX_PICTURE_LEFT_17            0
#define GFX_PICTURE_TOP_17             0
#define GFX_PICTURE_RIGHT_17           800
#define GFX_PICTURE_BOTTOM_17          480
#define GFX_PICTURE_STATE_17          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_17       1
#define GFX_PICTURE_SCHEME_17          gfxScheme1
		
#define GFX_PICTURE_LEFT_18            0
#define GFX_PICTURE_TOP_18             0
#define GFX_PICTURE_RIGHT_18           800
#define GFX_PICTURE_BOTTOM_18          480
#define GFX_PICTURE_STATE_18          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_18       1
#define GFX_PICTURE_SCHEME_18          gfxScheme1
		
#define GFX_PICTURE_LEFT_19            0
#define GFX_PICTURE_TOP_19             0
#define GFX_PICTURE_RIGHT_19           800
#define GFX_PICTURE_BOTTOM_19          480
#define GFX_PICTURE_STATE_19          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_19       1
#define GFX_PICTURE_SCHEME_19          gfxScheme1
		
#define GFX_PICTURE_LEFT_20            0
#define GFX_PICTURE_TOP_20             0
#define GFX_PICTURE_RIGHT_20           800
#define GFX_PICTURE_BOTTOM_20          480
#define GFX_PICTURE_STATE_20          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_20       1
#define GFX_PICTURE_SCHEME_20          gfxScheme1
		
#define GFX_PICTURE_LEFT_21            0
#define GFX_PICTURE_TOP_21             0
#define GFX_PICTURE_RIGHT_21           800
#define GFX_PICTURE_BOTTOM_21          480
#define GFX_PICTURE_STATE_21          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_21       1
#define GFX_PICTURE_SCHEME_21          gfxScheme1
		
#define GFX_PICTURE_LEFT_22            21
#define GFX_PICTURE_TOP_22             22
#define GFX_PICTURE_RIGHT_22           564
#define GFX_PICTURE_BOTTOM_22          368
#define GFX_PICTURE_STATE_22          GFX_GOL_PICTURECONTROL_DRAW_STATE | GFX_GOL_PICTURECONTROL_HIDE_STATE
#define GFX_PICTURE_SCALE_22       1
#define GFX_PICTURE_SCHEME_22          gfxScheme4
		
#define GFX_PICTURE_LEFT_23            21
#define GFX_PICTURE_TOP_23             23
#define GFX_PICTURE_RIGHT_23           582
#define GFX_PICTURE_BOTTOM_23          369
#define GFX_PICTURE_STATE_23          GFX_GOL_PICTURECONTROL_DRAW_STATE | GFX_GOL_PICTURECONTROL_HIDE_STATE
#define GFX_PICTURE_SCALE_23       1
#define GFX_PICTURE_SCHEME_23          gfxScheme4
		
/*** Pictures IDs ***/
#define SlideShowTipIcon                  12000 
	
#define cs_p_SlideShowTips                  12001 
	
#define ct_p_SlideShowTips                  12002 
	
#define Picture4                  12003 
	
#define Picture3                  12004 
	
#define Picture1                  12005 
	
#define Picture2                  12006 
	
#define Picture6                  12007 
	
#define Picture7                  12008 
	
#define Picture8                  12009 
	
#define Picture9                  12010 
	
#define Picture10                  12011 
	
#define Picture20                  12012 
	
#define Picture11                  12013 
	
#define Picture12                  12014 
	
#define Picture13                  12015 
	
#define Picture15                  12016 
	
#define Picture16                  12017 
	
#define Picture17                  12018 
	
#define Picture18                  12019 
	
#define Picture19                  12020 
	
#define Picture5                  12021 
	
#define ct_p_FeatureList                  12022 
	
#define cs_p_FeatureList                  12023 
	
/*** Line IDs ***/
#define Line21                 15000 
	
#define Line20                 15001 
	
#define Line19                 15002 
	
#define Line1                 15003 
	
#define Line18                 15004 
	
#define Line15                 15005 
	
#define Line17                 15006 
	
#define Line16                 15007 
	
#define Line14                 15008 
	
#define Line13                 15009 
	
#define Line12                 15010 
	
#define Line11                 15011 
	
#define Line10                 15012 
	
#define Line9                 15013 
	
#define Line8                 15014 
	
#define Line7                 15015 
	
#define Line6                 15016 
	
#define Line5                 15017 
	
#define Line4                 15018 
	
#define Line3                 15019 
	
#define Line2                 15020 
	
/*** Rectangle IDs ***/
#define Rectangle1                 16000 
	
/*** Image IDs ***/
#define Microchip_Logo                 18000 
	
#define Harmony_Logo                 18001 
	



// *****************************************************************************
/* MPLAB Harmony Graphics Composer Objects

  Summary:
    Structure holding the graphics object handles

  Description:
    This structure contains the object handles for all graphics objects 
    generated by the Harmony Graphics Composer

  Remarks:
*/

typedef struct HGC_OBJECTS
{
    HGC_SCREEN_STATES screenState;      // current state of screen state machine
    HGC_SCREEN_STATES prevRefreshState; // previous state of screen state machine

    /*** Touch Event Callback ***/
    SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction;

    /*** GOL Objects References ***/
    GFX_GOL_BUTTON* pFeatureListButtonObj;
    GFX_GOL_BUTTON* pTouchButtonObj;
    GFX_GOL_BUTTON* pSettingsButtonObj;
    GFX_GOL_BUTTON* pSlidesButtonObj;
    GFX_GOL_BUTTON* pButton23Obj;
    GFX_GOL_BUTTON* pButton7Obj;
    GFX_GOL_BUTTON* pButton1Obj;
    GFX_GOL_BUTTON* pButton2Obj;
    GFX_GOL_BUTTON* pButton3Obj;
    GFX_GOL_BUTTON* pButton8Obj;
    GFX_GOL_BUTTON* pButton9Obj;
    GFX_GOL_BUTTON* pButton10Obj;
    GFX_GOL_BUTTON* pButton11Obj;
    GFX_GOL_BUTTON* pButton13Obj;
    GFX_GOL_BUTTON* pButton24Obj;
    GFX_GOL_BUTTON* pButton14Obj;
    GFX_GOL_BUTTON* pButton15Obj;
    GFX_GOL_BUTTON* pButton16Obj;
    GFX_GOL_BUTTON* pButton18Obj;
    GFX_GOL_BUTTON* pButton19Obj;
    GFX_GOL_BUTTON* pButton20Obj;
    GFX_GOL_BUTTON* pButton21Obj;
    GFX_GOL_BUTTON* pButton22Obj;
    GFX_GOL_BUTTON* pButton12Obj;
    GFX_GOL_BUTTON* pButton4Obj;
    GFX_GOL_BUTTON* pButton5Obj;
    GFX_GOL_BUTTON* pButton6Obj;
    GFX_GOL_DIGITALMETER* pYPosObj;
    GFX_GOL_DIGITALMETER* pXPosObj;
    GFX_GOL_RADIOBUTTON* pRadioButtonEnglishObj;
    GFX_GOL_RADIOBUTTON* pRadioButtonChineseSimplObj;
    GFX_GOL_RADIOBUTTON* pRadioButtonChineseTradObj;
    GFX_GOL_SCROLLBAR* pSlider1Obj;
    GFX_GOL_STATICTEXT* pe_st_DemoNameObj;
    GFX_GOL_STATICTEXT* pe_st_SlideshowObj;
    GFX_GOL_STATICTEXT* pe_st_TouchTestObj;
    GFX_GOL_STATICTEXT* pe_st_SettingsObj;
    GFX_GOL_STATICTEXT* pe_st_FeaturesObj;
    GFX_GOL_STATICTEXT* pcs_st_SettingsObj;
    GFX_GOL_STATICTEXT* pct_st_SettingsObj;
    GFX_GOL_STATICTEXT* pcs_st_TouchTestObj;
    GFX_GOL_STATICTEXT* pct_st_TouchTestObj;
    GFX_GOL_STATICTEXT* pc_st_FeaturesObj;
    GFX_GOL_STATICTEXT* pct_st_SlideShowObj;
    GFX_GOL_STATICTEXT* pcs_st_SlideShowObj;
    GFX_GOL_STATICTEXT* pe_st_SlideShowTipsObj;
    GFX_GOL_STATICTEXT* pStaticText11Obj;
    GFX_GOL_STATICTEXT* pStaticText10Obj;
    GFX_GOL_STATICTEXT* pe_st_SecondObj;
    GFX_GOL_STATICTEXT* pc_st_SecondObj;
    GFX_GOL_STATICTEXT* pe_st_CloseBracketObj;
    GFX_GOL_STATICTEXT* pe_st_SlidePauseTimeObj;
    GFX_GOL_STATICTEXT* pct_st_SlidePauseTimeObj;
    GFX_GOL_STATICTEXT* pcs_st_SlidePauseTimeObj;
    GFX_GOL_STATICTEXT* pe_st_SelectLanguageObj;
    GFX_GOL_STATICTEXT* pct_st_SelectLanguageObj;
    GFX_GOL_STATICTEXT* pcs_st_SelectLanguageObj;
    GFX_GOL_STATICTEXT* pe_st_ChineseSimplifiedObj;
    GFX_GOL_STATICTEXT* pe_st_ChineseTraditionalObj;
    GFX_GOL_STATICTEXT* pcs_st_ChineseSimplifiedObj;
    GFX_GOL_STATICTEXT* pct_st_ChineseTraditionalObj;
    GFX_GOL_STATICTEXT* pe_st_EnglishObj;
    GFX_GOL_STATICTEXT* pe_st_OpenBracketObj;
    GFX_GOL_STATICTEXT* pSecondsStringObj;
    GFX_GOL_STATICTEXT* pe_st_5Obj;
    GFX_GOL_STATICTEXT* pe_st_0Obj;
    GFX_GOL_STATICTEXT* pe_st_DemonstratedFeaturesObj;
    GFX_GOL_WINDOW* pTouchAreaObj;
    GFX_GOL_PICTURECONTROL* pSlideShowTipIconObj;
    GFX_GOL_PICTURECONTROL* pcs_p_SlideShowTipsObj;
    GFX_GOL_PICTURECONTROL* pct_p_SlideShowTipsObj;
    GFX_GOL_PICTURECONTROL* pPicture4Obj;
    GFX_GOL_PICTURECONTROL* pPicture3Obj;
    GFX_GOL_PICTURECONTROL* pPicture1Obj;
    GFX_GOL_PICTURECONTROL* pPicture2Obj;
    GFX_GOL_PICTURECONTROL* pPicture6Obj;
    GFX_GOL_PICTURECONTROL* pPicture7Obj;
    GFX_GOL_PICTURECONTROL* pPicture8Obj;
    GFX_GOL_PICTURECONTROL* pPicture9Obj;
    GFX_GOL_PICTURECONTROL* pPicture10Obj;
    GFX_GOL_PICTURECONTROL* pPicture20Obj;
    GFX_GOL_PICTURECONTROL* pPicture11Obj;
    GFX_GOL_PICTURECONTROL* pPicture12Obj;
    GFX_GOL_PICTURECONTROL* pPicture13Obj;
    GFX_GOL_PICTURECONTROL* pPicture15Obj;
    GFX_GOL_PICTURECONTROL* pPicture16Obj;
    GFX_GOL_PICTURECONTROL* pPicture17Obj;
    GFX_GOL_PICTURECONTROL* pPicture18Obj;
    GFX_GOL_PICTURECONTROL* pPicture19Obj;
    GFX_GOL_PICTURECONTROL* pPicture5Obj;
    GFX_GOL_PICTURECONTROL* pct_p_FeatureListObj;
    GFX_GOL_PICTURECONTROL* pcs_p_FeatureListObj;
} HGC_OBJECTS;

extern HGC_OBJECTS hgcObj;

/******************************************************************************
  Function:
    void GFX_HGC_RegisterAppTouchCallback ( SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction )

  Summary:
    This function allows the application to register a callback to allow access 
    to the current touch behavior
 */
void GFX_HGC_RegisterAppTouchCallback ( SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction );


/******************************************************************************
  Function:
    void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg )

  Summary:
    This function sets up the Message System Service to route touch callbacks
    to the GOL message system  
 */
void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg );


/******************************************************************************
  Function:
    void GFX_HGC_Initialize ( void )

  Summary:
    This function initializes the HGC state machine.  
 */
void GFX_HGC_Initialize ( void );


/******************************************************************************
  Function:
    void GFX_HGC_Setup ( void )

  Summary:
    This function sets up the GOL message callback and draw callbacks.  
 */
void GFX_HGC_Setup ( void );


/******************************************************************************
  Function:
    HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void )

  Remarks:
    This function returns the screen state
 */
HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void );


/******************************************************************************
  Function:
    void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState )

  Remarks:
    This function sets the screen state machine to a new state
 */
void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState );


/******************************************************************************
  Function:
    void GFX_HGC_Tasks (SYS_MODULE_OBJ gfxObject);

  Summary:
    This function is called in SYS_Tasks.  The intent wait until the GFX library
    is initialized before supplying items to draw
*/
void GFX_HGC_Tasks  (SYS_MODULE_OBJ gfxObject);


/******************************************************************************
  Function:
    void GFX_HGC_SchemeCreate ( void )

  Summary:
    Allocates memory for a new scheme
 */
GFX_GOL_OBJ_SCHEME *GFX_HGC_SchemeCreate(void);


/******************************************************************************
  Function:
    void GFX_HGC_InitializeSchemes ( void )

  Summary:
    Initializes all HGC-specified schemes
 */
void GFX_HGC_InitializeSchemes( void );


/******************************************************************************
  Function: 
    bool GFX_HGC_MESSAGECallback(uint16_t objMsg, GFX_GOL_OBJ_HEADER* pObj, GFX_GOL_MESSAGE* pMsg)

  Input: 
    objMsg - translated message for the object,
    pObj - pointer to the object,
    pMsg - pointer to the non-translated, raw GOL message

  Output: 
    If the function returns non-zero the message will be processed by default

  Remarks: 
    GFX_GOL_MESSAGECallback() function calls it each time the valid message for the GOL object is received.
 */
bool GFX_HGC_MessageCallback(GFX_GOL_TRANSLATED_ACTION objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawCallback( void )

  Output: 
    If the function returns non-zero the draw control will be passed to GOL

  Remarks: 
    GFX_GOL_Draw() function calls it each time when GOL objects drawing is 
    completed. HGC-specified draw data is grouped by screens states. It takes 
    two states to complete the drawing of each screen.  GFX GOL objects are drawn
    first and then GFX Primitives are drawn next to ensure primitives are not
    covered by GOL objects.
 */
bool GFX_HGC_DrawCallback( void );
/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_GOL( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX GOL objects are drawn here, grouped by screen.
    The draw order is reverse Z-ordered.
 */
bool GFX_HGC_DrawScreen_GOL(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_Primitives( uint8_t  screenId )

  Output:
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX Primitives are drawn here, grouped by screen.
    GFX Primitives are drawn after GFX GOL Objects to make sure GFX GOL Objects
    do not cover GFX Primitives
 */
bool GFX_HGC_DrawScreen_Primitives(uint8_t screenId);


/******************************************************************************
  Function: 
    void GFX_HGC_SetupScreen( uint8_t  screenId )

  Remarks: 
    Clears current screen and starts a fresh screen with its background color
 */
void GFX_HGC_SetupScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_HasCurrentScreenDrawn( void )

  Output: 
    Returns true if the current screen is completely drawn

  Remarks: 
    Allows application to know if the current screen is finished drawing
 */
bool GFX_HGC_HasCurrentScreenDrawn( void );


/******************************************************************************
  Function: 
    bool GFX_HGC_ChangeScreen( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    Can be called to initiate GFX Library to draw a new screen
 */
bool GFX_HGC_ChangeScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawItem(int itemId)

  Output:
    Returns true if a itemId matches an existing item identifier

  Remarks: 
    Every item specified in every screen in HGC is listed in this function
 */
bool GFX_HGC_DrawItem(int itemId);


/******************************************************************************
  Function: 
    bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Button events
 */
bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgDigitalMeters(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Digital Meter events
 */
bool GFX_HGC_MsgDigitalMeters(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgRadioButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Radio Button events
 */
bool GFX_HGC_MsgRadioButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgScrollBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Scroll Bar events
 */
bool GFX_HGC_MsgScrollBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgPictures(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Picture Control events
 */
bool GFX_HGC_MsgPictures(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Static Text events
 */
bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Window events
 */
bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);


//DOM-IGNORE-BEGIN
#ifdef __cplusplus
}
#endif
//DOM-IGNORE-END

#endif // _GFX_HGC_DEFINITIONS_H
/*******************************************************************************
 End of File
*/
