/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_FLASH_DISABLE
#error The GFX_CONFIG_IMAGE_FLASH_DISABLE is defined in system_config.h header file.
#endif

/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_FLASH_DISABLE
#error The GFX_CONFIG_FONT_FLASH_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: cog
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cog[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cog[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cog =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cog,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: cog_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cog_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cog_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cog_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cog_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: layers_image
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __layers_image[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __layers_image[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR layers_image =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __layers_image,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: layers_image_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __layers_image_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __layers_image_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR layers_image_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __layers_image_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: script_invert
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __script_invert[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __script_invert[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR script_invert =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __script_invert,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: script_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __script_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __script_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR script_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __script_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: NewHarmonyLogo_Small
 * Description:  172x120 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __NewHarmonyLogo_Small[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __NewHarmonyLogo_Small[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR NewHarmonyLogo_Small =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __NewHarmonyLogo_Small,
    .resource.image.width = 172,
    .resource.image.height = 120,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 41284,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton_Outline
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __RoundHomeButton_Outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __RoundHomeButton_Outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR RoundHomeButton_Outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __RoundHomeButton_Outline,
    .resource.image.width = 90,
    .resource.image.height = 89,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 16024,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __RoundHomeButton[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __RoundHomeButton[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR RoundHomeButton =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __RoundHomeButton,
    .resource.image.width = 90,
    .resource.image.height = 89,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 16024,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: microchipLogo_small
 * Description:  230x120 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __microchipLogo_small[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __microchipLogo_small[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR microchipLogo_small =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __microchipLogo_small,
    .resource.image.width = 230,
    .resource.image.height = 120,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: VeraMono
 * Description:  Height: 19 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR VeraMono = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __VeraMono,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x0013,
};
/*********************************
 * TTF Font File Structure
 * Label: VeraMono14
 * Description:  Height: 17 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __VeraMono14[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __VeraMono14[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __VeraMono14[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR VeraMono14 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __VeraMono14,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x0011,
};
/*********************************
 * TTF Font File Structure
 * Label: VeraMono12
 * Description:  Height: 15 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __VeraMono12[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __VeraMono12[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __VeraMono12[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR VeraMono12 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __VeraMono12,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x000F,
};
