/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef GFX_RESOURCES_INT_H_FILE
#define GFX_RESOURCES_INT_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif



/*****************************************************************************
 * SECTION: Graphics Configuration
 * Overview:    This defines the size of the buffer used by font functions
 *              to retrieve font data from the external memory. The buffer
 *              size can be increased to accommodate large font sizes.
 *              The user must be aware of the expected glyph sizes of the 
 *              characters stored in the font table. 
 *              To modify the size used, declare this macro in the 
 *              GraphicsConfig.h file with the desired size.
 *
 * #define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE     (462)
 *****************************************************************************/

/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: fan_2
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR fan_2;
#define fan_2_WIDTH     (140)
#define fan_2_HEIGHT    (140)
#define fan_2_SIZE      (39206)
/*********************************
 * Bitmap Structure
 * Label: fan_3
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR fan_3;
#define fan_3_WIDTH     (140)
#define fan_3_HEIGHT    (140)
#define fan_3_SIZE      (39206)
/*********************************
 * Bitmap Structure
 * Label: fan_4
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR fan_4;
#define fan_4_WIDTH     (140)
#define fan_4_HEIGHT    (140)
#define fan_4_SIZE      (39206)
/*********************************
 * Bitmap Structure
 * Label: blue_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR blue_temp_70;
#define blue_temp_70_WIDTH     (70)
#define blue_temp_70_HEIGHT    (220)
#define blue_temp_70_SIZE      (30806)
/*********************************
 * Bitmap Structure
 * Label: green_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR green_temp_70;
#define green_temp_70_WIDTH     (70)
#define green_temp_70_HEIGHT    (220)
#define green_temp_70_SIZE      (30806)
/*********************************
 * Bitmap Structure
 * Label: orange_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR orange_temp_70;
#define orange_temp_70_WIDTH     (70)
#define orange_temp_70_HEIGHT    (220)
#define orange_temp_70_SIZE      (30806)
/*********************************
 * Bitmap Structure
 * Label: red_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR red_temp_70;
#define red_temp_70_WIDTH     (70)
#define red_temp_70_HEIGHT    (220)
#define red_temp_70_SIZE      (30806)
/*********************************
 * Bitmap Structure
 * Label: fan_1
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR fan_1;
#define fan_1_WIDTH     (140)
#define fan_1_HEIGHT    (140)
#define fan_1_SIZE      (39206)
/*********************************
 * Bitmap Structure
 * Label: Down_Magenta_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Down_Magenta_80;
#define Down_Magenta_80_WIDTH     (80)
#define Down_Magenta_80_HEIGHT    (80)
#define Down_Magenta_80_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: Down_Magenta_80_pressed
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Down_Magenta_80_pressed;
#define Down_Magenta_80_pressed_WIDTH     (80)
#define Down_Magenta_80_pressed_HEIGHT    (80)
#define Down_Magenta_80_pressed_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: House_Blue_80
 * Description:  80x72 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR House_Blue_80;
#define House_Blue_80_WIDTH     (80)
#define House_Blue_80_HEIGHT    (72)
#define House_Blue_80_SIZE      (11526)
/*********************************
 * Bitmap Structure
 * Label: House_Blue_80_pressed
 * Description:  80x72 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR House_Blue_80_pressed;
#define House_Blue_80_pressed_WIDTH     (80)
#define House_Blue_80_pressed_HEIGHT    (72)
#define House_Blue_80_pressed_SIZE      (11526)
/*********************************
 * Bitmap Structure
 * Label: Up_Magenta_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Up_Magenta_80;
#define Up_Magenta_80_WIDTH     (80)
#define Up_Magenta_80_HEIGHT    (80)
#define Up_Magenta_80_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: Up_Magenta_80_pressed
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Up_Magenta_80_pressed;
#define Up_Magenta_80_pressed_WIDTH     (80)
#define Up_Magenta_80_pressed_HEIGHT    (80)
#define Up_Magenta_80_pressed_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: Up_Grey_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Up_Grey_80;
#define Up_Grey_80_WIDTH     (80)
#define Up_Grey_80_HEIGHT    (80)
#define Up_Grey_80_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: Down_Grey_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Down_Grey_80;
#define Down_Grey_80_WIDTH     (80)
#define Down_Grey_80_HEIGHT    (80)
#define Down_Grey_80_SIZE      (12806)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_1
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_1;
#define mchip_logo_1_WIDTH     (200)
#define mchip_logo_1_HEIGHT    (115)
#define mchip_logo_1_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_2
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_2;
#define mchip_logo_2_WIDTH     (200)
#define mchip_logo_2_HEIGHT    (115)
#define mchip_logo_2_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_3
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_3;
#define mchip_logo_3_WIDTH     (200)
#define mchip_logo_3_HEIGHT    (115)
#define mchip_logo_3_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_4
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_4;
#define mchip_logo_4_WIDTH     (200)
#define mchip_logo_4_HEIGHT    (115)
#define mchip_logo_4_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_10
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_10;
#define mchip_logo_10_WIDTH     (200)
#define mchip_logo_10_HEIGHT    (115)
#define mchip_logo_10_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_11
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_11;
#define mchip_logo_11_WIDTH     (200)
#define mchip_logo_11_HEIGHT    (115)
#define mchip_logo_11_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_12
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_12;
#define mchip_logo_12_WIDTH     (200)
#define mchip_logo_12_HEIGHT    (115)
#define mchip_logo_12_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_13
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_13;
#define mchip_logo_13_WIDTH     (200)
#define mchip_logo_13_HEIGHT    (115)
#define mchip_logo_13_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_14
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_14;
#define mchip_logo_14_WIDTH     (200)
#define mchip_logo_14_HEIGHT    (115)
#define mchip_logo_14_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_15
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_15;
#define mchip_logo_15_WIDTH     (200)
#define mchip_logo_15_HEIGHT    (115)
#define mchip_logo_15_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_16
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_16;
#define mchip_logo_16_WIDTH     (200)
#define mchip_logo_16_HEIGHT    (115)
#define mchip_logo_16_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_17
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_17;
#define mchip_logo_17_WIDTH     (200)
#define mchip_logo_17_HEIGHT    (115)
#define mchip_logo_17_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_18
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_18;
#define mchip_logo_18_WIDTH     (200)
#define mchip_logo_18_HEIGHT    (115)
#define mchip_logo_18_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_19
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_19;
#define mchip_logo_19_WIDTH     (200)
#define mchip_logo_19_HEIGHT    (115)
#define mchip_logo_19_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_20
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_20;
#define mchip_logo_20_WIDTH     (200)
#define mchip_logo_20_HEIGHT    (115)
#define mchip_logo_20_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_21
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_21;
#define mchip_logo_21_WIDTH     (200)
#define mchip_logo_21_HEIGHT    (115)
#define mchip_logo_21_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_22
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_22;
#define mchip_logo_22_WIDTH     (200)
#define mchip_logo_22_HEIGHT    (115)
#define mchip_logo_22_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_23
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_23;
#define mchip_logo_23_WIDTH     (200)
#define mchip_logo_23_HEIGHT    (115)
#define mchip_logo_23_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_24
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_24;
#define mchip_logo_24_WIDTH     (200)
#define mchip_logo_24_HEIGHT    (115)
#define mchip_logo_24_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_5
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_5;
#define mchip_logo_5_WIDTH     (200)
#define mchip_logo_5_HEIGHT    (115)
#define mchip_logo_5_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_6
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_6;
#define mchip_logo_6_WIDTH     (200)
#define mchip_logo_6_HEIGHT    (115)
#define mchip_logo_6_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_7
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_7;
#define mchip_logo_7_WIDTH     (200)
#define mchip_logo_7_HEIGHT    (115)
#define mchip_logo_7_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_8
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_8;
#define mchip_logo_8_WIDTH     (200)
#define mchip_logo_8_HEIGHT    (115)
#define mchip_logo_8_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_9
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_9;
#define mchip_logo_9_WIDTH     (200)
#define mchip_logo_9_HEIGHT    (115)
#define mchip_logo_9_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: mchip_logo_25
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR mchip_logo_25;
#define mchip_logo_25_WIDTH     (200)
#define mchip_logo_25_HEIGHT    (115)
#define mchip_logo_25_SIZE      (46006)
/*********************************
 * Bitmap Structure
 * Label: motion_mainscreen
 * Description:  476x270 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR motion_mainscreen;
#define motion_mainscreen_WIDTH     (476)
#define motion_mainscreen_HEIGHT    (270)
#define motion_mainscreen_SIZE      (257046)
/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: base
 * Description:  400x258 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR base;
#define base_WIDTH     (400)
#define base_HEIGHT    (258)
#define base_SIZE      (9185)
/*********************************
 * JPEG Structure
 * Label: needle_04
 * Description:  400x258 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR needle_04;
#define needle_04_WIDTH     (400)
#define needle_04_HEIGHT    (258)
#define needle_04_SIZE      (7099)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0003
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0003;
#define flash_logo_logo0003_WIDTH     (200)
#define flash_logo_logo0003_HEIGHT    (125)
#define flash_logo_logo0003_SIZE      (1370)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0004
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0004;
#define flash_logo_logo0004_WIDTH     (200)
#define flash_logo_logo0004_HEIGHT    (125)
#define flash_logo_logo0004_SIZE      (2100)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0005
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0005;
#define flash_logo_logo0005_WIDTH     (200)
#define flash_logo_logo0005_HEIGHT    (125)
#define flash_logo_logo0005_SIZE      (2323)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0006
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0006;
#define flash_logo_logo0006_WIDTH     (200)
#define flash_logo_logo0006_HEIGHT    (125)
#define flash_logo_logo0006_SIZE      (2499)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0007
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0007;
#define flash_logo_logo0007_WIDTH     (200)
#define flash_logo_logo0007_HEIGHT    (125)
#define flash_logo_logo0007_SIZE      (2706)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0008
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0008;
#define flash_logo_logo0008_WIDTH     (200)
#define flash_logo_logo0008_HEIGHT    (125)
#define flash_logo_logo0008_SIZE      (2935)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0009
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0009;
#define flash_logo_logo0009_WIDTH     (200)
#define flash_logo_logo0009_HEIGHT    (125)
#define flash_logo_logo0009_SIZE      (3082)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0010
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0010;
#define flash_logo_logo0010_WIDTH     (200)
#define flash_logo_logo0010_HEIGHT    (125)
#define flash_logo_logo0010_SIZE      (3172)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0011
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0011;
#define flash_logo_logo0011_WIDTH     (200)
#define flash_logo_logo0011_HEIGHT    (125)
#define flash_logo_logo0011_SIZE      (3226)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0012
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0012;
#define flash_logo_logo0012_WIDTH     (200)
#define flash_logo_logo0012_HEIGHT    (125)
#define flash_logo_logo0012_SIZE      (3281)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0013
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0013;
#define flash_logo_logo0013_WIDTH     (200)
#define flash_logo_logo0013_HEIGHT    (125)
#define flash_logo_logo0013_SIZE      (3298)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0014
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0014;
#define flash_logo_logo0014_WIDTH     (200)
#define flash_logo_logo0014_HEIGHT    (125)
#define flash_logo_logo0014_SIZE      (3300)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0015
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0015;
#define flash_logo_logo0015_WIDTH     (200)
#define flash_logo_logo0015_HEIGHT    (125)
#define flash_logo_logo0015_SIZE      (3342)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0016
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0016;
#define flash_logo_logo0016_WIDTH     (200)
#define flash_logo_logo0016_HEIGHT    (125)
#define flash_logo_logo0016_SIZE      (3346)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0017
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0017;
#define flash_logo_logo0017_WIDTH     (200)
#define flash_logo_logo0017_HEIGHT    (125)
#define flash_logo_logo0017_SIZE      (3373)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0018
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0018;
#define flash_logo_logo0018_WIDTH     (200)
#define flash_logo_logo0018_HEIGHT    (125)
#define flash_logo_logo0018_SIZE      (3412)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0019
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0019;
#define flash_logo_logo0019_WIDTH     (200)
#define flash_logo_logo0019_HEIGHT    (125)
#define flash_logo_logo0019_SIZE      (3430)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0020
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0020;
#define flash_logo_logo0020_WIDTH     (200)
#define flash_logo_logo0020_HEIGHT    (125)
#define flash_logo_logo0020_SIZE      (3466)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0021
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0021;
#define flash_logo_logo0021_WIDTH     (200)
#define flash_logo_logo0021_HEIGHT    (125)
#define flash_logo_logo0021_SIZE      (3456)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0022
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0022;
#define flash_logo_logo0022_WIDTH     (200)
#define flash_logo_logo0022_HEIGHT    (125)
#define flash_logo_logo0022_SIZE      (3458)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0023
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0023;
#define flash_logo_logo0023_WIDTH     (200)
#define flash_logo_logo0023_HEIGHT    (125)
#define flash_logo_logo0023_SIZE      (3503)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0024
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0024;
#define flash_logo_logo0024_WIDTH     (200)
#define flash_logo_logo0024_HEIGHT    (125)
#define flash_logo_logo0024_SIZE      (3500)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0025
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0025;
#define flash_logo_logo0025_WIDTH     (200)
#define flash_logo_logo0025_HEIGHT    (125)
#define flash_logo_logo0025_SIZE      (3538)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0026
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0026;
#define flash_logo_logo0026_WIDTH     (200)
#define flash_logo_logo0026_HEIGHT    (125)
#define flash_logo_logo0026_SIZE      (3573)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0027
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0027;
#define flash_logo_logo0027_WIDTH     (200)
#define flash_logo_logo0027_HEIGHT    (125)
#define flash_logo_logo0027_SIZE      (3581)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0028
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0028;
#define flash_logo_logo0028_WIDTH     (200)
#define flash_logo_logo0028_HEIGHT    (125)
#define flash_logo_logo0028_SIZE      (3592)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0029
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0029;
#define flash_logo_logo0029_WIDTH     (200)
#define flash_logo_logo0029_HEIGHT    (125)
#define flash_logo_logo0029_SIZE      (3582)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0030
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0030;
#define flash_logo_logo0030_WIDTH     (200)
#define flash_logo_logo0030_HEIGHT    (125)
#define flash_logo_logo0030_SIZE      (3587)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0031
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0031;
#define flash_logo_logo0031_WIDTH     (200)
#define flash_logo_logo0031_HEIGHT    (125)
#define flash_logo_logo0031_SIZE      (3605)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0032
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0032;
#define flash_logo_logo0032_WIDTH     (200)
#define flash_logo_logo0032_HEIGHT    (125)
#define flash_logo_logo0032_SIZE      (3605)
/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0002
 * Description:  200x125 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR flash_logo_logo0002;
#define flash_logo_logo0002_WIDTH     (200)
#define flash_logo_logo0002_HEIGHT    (125)
#define flash_logo_logo0002_SIZE      (1043)
/*****************************************************************************
 * SECTION:  Fonts
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: Arial16
 * Description:  Height: 19 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR Arial16;
#define Arial16_SIZE    (3527)
/*********************************
 * TTF Font File Structure
 * Label: Arial8
 * Description:  Height: 13 pixels, 2 bits per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR Arial8;
#define Arial8_SIZE    (2628)
/*********************************
 * TTF Font File Structure
 * Label: Arial55
 * Description:  Height: 64 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR Arial55;
#define Arial55_SIZE    (25961)
/*********************************
 * TTF Font File Structure
 * Label: Arial28
 * Description:  Height: 33 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR Arial28;
#define Arial28_SIZE    (7190)
#endif

