/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif



/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_FLASH_DISABLE
#error The GFX_CONFIG_IMAGE_FLASH_DISABLE is defined in system_config.h header file.
#endif

/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_FLASH_DISABLE
#error The GFX_CONFIG_FONT_FLASH_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: fan_2
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __fan_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __fan_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR fan_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __fan_2,
    .resource.image.width = 140,
    .resource.image.height = 140,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 39204,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: fan_3
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __fan_3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __fan_3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR fan_3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __fan_3,
    .resource.image.width = 140,
    .resource.image.height = 140,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 39204,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: fan_4
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __fan_4[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __fan_4[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR fan_4 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __fan_4,
    .resource.image.width = 140,
    .resource.image.height = 140,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 39204,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: blue_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __blue_temp_70[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __blue_temp_70[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR blue_temp_70 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __blue_temp_70,
    .resource.image.width = 70,
    .resource.image.height = 220,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 30804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: green_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __green_temp_70[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __green_temp_70[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR green_temp_70 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __green_temp_70,
    .resource.image.width = 70,
    .resource.image.height = 220,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 30804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: orange_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __orange_temp_70[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __orange_temp_70[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR orange_temp_70 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __orange_temp_70,
    .resource.image.width = 70,
    .resource.image.height = 220,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 30804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: red_temp_70
 * Description:  70x220 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __red_temp_70[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __red_temp_70[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR red_temp_70 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __red_temp_70,
    .resource.image.width = 70,
    .resource.image.height = 220,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 30804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: fan_1
 * Description:  140x140 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __fan_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __fan_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR fan_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __fan_1,
    .resource.image.width = 140,
    .resource.image.height = 140,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 39204,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Down_Magenta_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Down_Magenta_80[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Down_Magenta_80[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Down_Magenta_80 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Down_Magenta_80,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Down_Magenta_80_pressed
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Down_Magenta_80_pressed[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Down_Magenta_80_pressed[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Down_Magenta_80_pressed =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Down_Magenta_80_pressed,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: House_Blue_80
 * Description:  80x72 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __House_Blue_80[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __House_Blue_80[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR House_Blue_80 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __House_Blue_80,
    .resource.image.width = 80,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 11524,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: House_Blue_80_pressed
 * Description:  80x72 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __House_Blue_80_pressed[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __House_Blue_80_pressed[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR House_Blue_80_pressed =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __House_Blue_80_pressed,
    .resource.image.width = 80,
    .resource.image.height = 72,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 11524,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Up_Magenta_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Up_Magenta_80[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Up_Magenta_80[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Up_Magenta_80 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Up_Magenta_80,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Up_Magenta_80_pressed
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Up_Magenta_80_pressed[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Up_Magenta_80_pressed[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Up_Magenta_80_pressed =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Up_Magenta_80_pressed,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Up_Grey_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Up_Grey_80[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Up_Grey_80[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Up_Grey_80 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Up_Grey_80,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: Down_Grey_80
 * Description:  80x80 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Down_Grey_80[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Down_Grey_80[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Down_Grey_80 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Down_Grey_80,
    .resource.image.width = 80,
    .resource.image.height = 80,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 12804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_1
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_1[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_1[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_1 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_1,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_2
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_2[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_2[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_2 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_2,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_3
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_3[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_3[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_3 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_3,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_4
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_4[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_4[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_4 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_4,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_10
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_10[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_10[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_10 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_10,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_11
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_11[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_11[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_11 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_11,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_12
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_12[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_12[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_12 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_12,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_13
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_13[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_13[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_13 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_13,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_14
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_14[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_14[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_14 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_14,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_15
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_15[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_15[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_15 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_15,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_16
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_16[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_16[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_16 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_16,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_17
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_17[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_17[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_17 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_17,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_18
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_18[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_18[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_18 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_18,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_19
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_19[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_19[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_19 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_19,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_20
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_20[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_20[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_20 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_20,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_21
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_21[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_21[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_21 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_21,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_22
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_22[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_22[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_22 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_22,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_23
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_23[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_23[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_23 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_23,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_24
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_24[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_24[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_24 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_24,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_5
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_5[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_5[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_5 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_5,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_6
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_6[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_6[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_6 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_6,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_7
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_7[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_7[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_7 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_7,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_8
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_8[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_8[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_8 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_8,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_9
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_9[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_9[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_9 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_9,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: mchip_logo_25
 * Description:  200x115 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __mchip_logo_25[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __mchip_logo_25[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR mchip_logo_25 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __mchip_logo_25,
    .resource.image.width = 200,
    .resource.image.height = 115,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 46004,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: motion_mainscreen
 * Description:  476x270 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __motion_mainscreen[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __motion_mainscreen[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR motion_mainscreen =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __motion_mainscreen,
    .resource.image.width = 476,
    .resource.image.height = 270,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 257044,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: base
 * Description:  400x258 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __base[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __base[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR base =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __base,
    .resource.image.width = 400,
    .resource.image.height = 258,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: needle_04
 * Description:  400x258 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __needle_04[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __needle_04[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR needle_04 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __needle_04,
    .resource.image.width = 400,
    .resource.image.height = 258,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0003
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0003[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0003[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0003 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0003,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0004
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0004[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0004[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0004 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0004,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0005
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0005[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0005[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0005 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0005,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0006
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0006[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0006[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0006 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0006,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0007
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0007[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0007[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0007 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0007,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0008
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0008[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0008[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0008 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0008,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0009
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0009[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0009[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0009 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0009,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0010
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0010[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0010[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0010 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0010,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0011
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0011[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0011[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0011 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0011,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0012
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0012[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0012[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0012 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0012,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0013
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0013[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0013[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0013 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0013,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0014
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0014[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0014[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0014 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0014,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0015
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0015[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0015[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0015 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0015,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0016
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0016[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0016[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0016 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0016,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0017
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0017[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0017[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0017 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0017,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0018
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0018[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0018[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0018 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0018,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0019
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0019[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0019[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0019 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0019,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0020
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0020[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0020[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0020 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0020,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0021
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0021[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0021[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0021 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0021,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0022
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0022[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0022[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0022 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0022,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0023
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0023[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0023[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0023 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0023,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0024
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0024[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0024[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0024 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0024,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0025
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0025[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0025[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0025 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0025,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0026
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0026[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0026[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0026 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0026,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0027
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0027[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0027[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0027 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0027,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0028
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0028[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0028[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0028 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0028,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0029
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0029[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0029[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0029 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0029,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0030
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0030[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0030[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0030 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0030,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0031
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0031[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0031[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0031 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0031,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0032
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0032[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0032[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0032 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0032,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: flash_logo_logo0002
 * Description:  200x125 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __flash_logo_logo0002[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __flash_logo_logo0002[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR flash_logo_logo0002 =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __flash_logo_logo0002,
    .resource.image.width = 200,
    .resource.image.height = 125,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: Arial16
 * Description:  Height: 19 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __Arial16[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __Arial16[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __Arial16[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR Arial16 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __Arial16,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x0013,
};
/*********************************
 * TTF Font File Structure
 * Label: Arial8
 * Description:  Height: 13 pixels, 2 bits per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __Arial8[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __Arial8[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __Arial8[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR Arial8 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __Arial8,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 1,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x000D,
};
/*********************************
 * TTF Font File Structure
 * Label: Arial55
 * Description:  Height: 64 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __Arial55[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __Arial55[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __Arial55[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR Arial55 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __Arial55,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x0040,
};
/*********************************
 * TTF Font File Structure
 * Label: Arial28
 * Description:  Height: 33 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __Arial28[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __Arial28[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __Arial28[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR Arial28 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __Arial28,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x0021,
};
