/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int_reference.c
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION:  Graphics Configuration: Bitmap Check
 *****************************************************************************/

#ifdef GFX_CONFIG_IMAGE_FLASH_DISABLE
#error The GFX_CONFIG_IMAGE_FLASH_DISABLE is defined in system_config.h header file.
#endif

/*****************************************************************************
 * SECTION:  Graphics Configuration: Font Check
 *****************************************************************************/

#ifdef GFX_CONFIG_FONT_FLASH_DISABLE
#error The GFX_CONFIG_FONT_FLASH_DISABLE is defined in system_config.h header file.
#endif


/*****************************************************************************
 * SECTION:  SimHei18 - Unicode to GRC Index Table
 *****************************************************************************/

#ifdef GFX_LIB_CFG_USE_UNICODE_INDEX_TABLE
const uint16_t simhei18UnicodeIndexTable[38][2] =
{
//    Unicode   GRC Index
//    -------   ---------
    {  0x4E2D,   0x0020  },
    {  0x4F53,   0x0021  },
    {  0x5165,   0x0022  },
    {  0x529F,   0x0023  },
    {  0x5E7B,   0x0024  },
    {  0x62E9,   0x0025  },
    {  0x6478,   0x0026  },
    {  0x64C7,   0x0027  },
    {  0x6587,   0x0028  },
    {  0x65F6,   0x0029  },
    {  0x6642,   0x002A  },
    {  0x6F14,   0x002B  },
    {  0x706F,   0x002C  },
    {  0x71C8,   0x002D  },
    {  0x7247,   0x002E  },
    {  0x793A,   0x002F  },
    {  0x79D2,   0x0030  },
    {  0x7B80,   0x0031  },
    {  0x7C21,   0x0032  },
    {  0x7E41,   0x0033  },
    {  0x7F6E,   0x0034  },
    {  0x80FD,   0x0035  },
    {  0x82F1,   0x0036  },
    {  0x89E6,   0x0037  },
    {  0x89F8,   0x0038  },
    {  0x8A00,   0x0039  },
    {  0x8A2D,   0x003A  },
    {  0x8A9E,   0x003B  },
    {  0x8BBE,   0x003C  },
    {  0x8BED,   0x003D  },
    {  0x8F38,   0x003E  },
    {  0x8F93,   0x003F  },
    {  0x9009,   0x0040  },
    {  0x9078,   0x0041  },
    {  0x9593,   0x0042  },
    {  0x95F4,   0x0043  },
    {  0x9694,   0x0044  },
    {  0x9AD4,   0x0045  },
};
#endif
/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: cog
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cog[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cog[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cog =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cog,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: cog_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cog_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cog_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cog_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cog_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: layers_image
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __layers_image[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __layers_image[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR layers_image =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __layers_image,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: layers_image_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __layers_image_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __layers_image_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR layers_image_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __layers_image_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: location_pin
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __location_pin[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __location_pin[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR location_pin =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __location_pin,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: location_pin_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __location_pin_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __location_pin_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR location_pin_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __location_pin_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: script_invert
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __script_invert[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __script_invert[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR script_invert =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __script_invert,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: script_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __script_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __script_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR script_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __script_outline,
    .resource.image.width = 60,
    .resource.image.height = 60,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 488,
    .resource.image.colorDepth = 1,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: NewHarmonyLogo_Small
 * Description:  172x120 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __NewHarmonyLogo_Small[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __NewHarmonyLogo_Small[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR NewHarmonyLogo_Small =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __NewHarmonyLogo_Small,
    .resource.image.width = 172,
    .resource.image.height = 120,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 41284,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: cs_FeatureList
 * Description:  321x200 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cs_FeatureList[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cs_FeatureList[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cs_FeatureList =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cs_FeatureList,
    .resource.image.width = 321,
    .resource.image.height = 200,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 128404,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: ct_FeatureList
 * Description:  313x200 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __ct_FeatureList[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __ct_FeatureList[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR ct_FeatureList =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __ct_FeatureList,
    .resource.image.width = 313,
    .resource.image.height = 200,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 125204,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: cs_SlideShowInstructions
 * Description:  400x181 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __cs_SlideShowInstructions[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __cs_SlideShowInstructions[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR cs_SlideShowInstructions =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __cs_SlideShowInstructions,
    .resource.image.width = 400,
    .resource.image.height = 181,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 144804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: ct_SlideShowInstructions
 * Description:  400x181 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __ct_SlideShowInstructions[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __ct_SlideShowInstructions[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR ct_SlideShowInstructions =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __ct_SlideShowInstructions,
    .resource.image.width = 400,
    .resource.image.height = 181,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 144804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: TestImage
 * Description:  344x169 pixels, 8-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __TestImage[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __TestImage[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR TestImage =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __TestImage,
    .resource.image.width = 344,
    .resource.image.height = 169,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 58652,
    .resource.image.colorDepth = 8,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: home_outline
 * Description:  30x30 pixels, 4-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __home_outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __home_outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR home_outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __home_outline,
    .resource.image.width = 30,
    .resource.image.height = 30,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 484,
    .resource.image.colorDepth = 4,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton_Outline
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __RoundHomeButton_Outline[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __RoundHomeButton_Outline[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR RoundHomeButton_Outline =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __RoundHomeButton_Outline,
    .resource.image.width = 90,
    .resource.image.height = 89,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 16024,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __RoundHomeButton[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __RoundHomeButton[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR RoundHomeButton =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __RoundHomeButton,
    .resource.image.width = 90,
    .resource.image.height = 89,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 16024,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*********************************
 * Bitmap Structure
 * Label: microchipLogo_small
 * Description:  220x120 pixels, 16-bits per pixel
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __microchipLogo_small[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __microchipLogo_small[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR microchipLogo_small =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_MCHP_MBITMAP | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __microchipLogo_small,
    .resource.image.width = 220,
    .resource.image.height = 120,
    .resource.image.parameter1.compressedSize = 0,
    .resource.image.parameter2.rawSize = 52804,
    .resource.image.colorDepth = 16,
    .resource.image.type = 0x00,
    .resource.image.paletteID = 0x0000
};

/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: AutumnGrass_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __AutumnGrass_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __AutumnGrass_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR AutumnGrass_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __AutumnGrass_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: BoraBoraSunset_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __BoraBoraSunset_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __BoraBoraSunset_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR BoraBoraSunset_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __BoraBoraSunset_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: CoalHarbourDay_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __CoalHarbourDay_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __CoalHarbourDay_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR CoalHarbourDay_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __CoalHarbourDay_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: ColorPalette_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __ColorPalette_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __ColorPalette_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR ColorPalette_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __ColorPalette_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: DowntownVancouver_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __DowntownVancouver_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __DowntownVancouver_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR DowntownVancouver_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __DowntownVancouver_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: EnglishBayFireworks_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __EnglishBayFireworks_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __EnglishBayFireworks_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR EnglishBayFireworks_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __EnglishBayFireworks_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: FalseCreek_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __FalseCreek_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __FalseCreek_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR FalseCreek_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __FalseCreek_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Fishes_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Fishes_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Fishes_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Fishes_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Fishes_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: MicrochipLogo_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __MicrochipLogo_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __MicrochipLogo_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR MicrochipLogo_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __MicrochipLogo_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: NewHarmonyLogo_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __NewHarmonyLogo_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __NewHarmonyLogo_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR NewHarmonyLogo_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __NewHarmonyLogo_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: ParkTrees_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __ParkTrees_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __ParkTrees_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR ParkTrees_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __ParkTrees_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Rockies_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Rockies_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Rockies_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Rockies_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Rockies_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: ScienceWorldNight_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __ScienceWorldNight_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __ScienceWorldNight_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR ScienceWorldNight_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __ScienceWorldNight_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Sherwood_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Sherwood_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Sherwood_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Sherwood_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Sherwood_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: SnowLeopard_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __SnowLeopard_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __SnowLeopard_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR SnowLeopard_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __SnowLeopard_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: SnowyHills_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __SnowyHills_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __SnowyHills_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR SnowyHills_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __SnowyHills_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Splash_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Splash_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Splash_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Splash_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Splash_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Waterfall_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Waterfall_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Waterfall_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Waterfall_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Waterfall_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: Wheats_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __Wheats_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __Wheats_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR Wheats_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __Wheats_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*********************************
 * JPEG Structure
 * Label: MacBethChart_JPEG
 * Description:  453x272 pixels
 ***********************************/
#if defined (GFX_CONFIG_IMAGE_PACKED_ENABLE) && (__XC16_VERSION__ >= 1011)
extern uint8_gfx_image_prog __MacBethChart_JPEG[] __attribute__((section("grc_images")));
#else
extern uint8_gfx_image_prog __MacBethChart_JPEG[] __attribute__((section("grc_images"), aligned(2)));
#endif

const GFX_RESOURCE_HDR MacBethChart_JPEG =
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_JPEG | GFX_RESOURCE_COMP_NONE),
    .ID = 0,
    .resource.image.location.progByteAddress = (uint8_gfx_image_prog *) __MacBethChart_JPEG,
    .resource.image.width = 453,
    .resource.image.height = 272,
    .resource.image.parameter1.reserved = 0,
    .resource.image.parameter2.reserved = 0,
    .resource.image.colorDepth = 16
};

/*****************************************************************************
 * SECTION:  FONTS
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: VeraMono
 * Description:  Height: 15 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __VeraMono[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR VeraMono = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __VeraMono,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x007F,
    .resource.font.header.height = 0x000F,
};
/*********************************
 * TTF Font File Structure
 * Label: SimHei18
 * Description:  Height: 21 pixels, 1 bit per pixel, Range: '?' to '?'
 ***********************************/
#if defined(GFX_CONFIG_FONT_PROG_SPACE_ENABLE) && (__XC16_VERSION__ >= 1011)
#ifndef GFX_CONFIG_FONT_PACKED_ENABLE
extern GFX_FONT_SPACE char __SimHei18[] __attribute__((section("grc_text"), aligned(2)));
#else
extern GFX_FONT_SPACE char __SimHei18[] __attribute__((section("grc_text")));
#endif
#else
extern GFX_FONT_SPACE char __SimHei18[] __attribute__((aligned(2)));
#endif

const GFX_RESOURCE_HDR SimHei18 = 
{
    .type = (GFX_RESOURCE_MEMORY_FLASH | GFX_RESOURCE_TYPE_FONT | GFX_RESOURCE_COMP_NONE),
    .ID = 0x0000,
    .resource.font.location.progByteAddress = (GFX_FONT_SPACE char *) __SimHei18,
    .resource.font.header.fontID = 0,
    .resource.font.header.extendedGlyphEntry = 0,
    .resource.font.header.res1 = 0,
    .resource.font.header.bpp = 0,
    .resource.font.header.orientation = 0,
    .resource.font.header.res2 = 0,
    .resource.font.header.firstChar = 0x0020,
    .resource.font.header.lastChar = 0x0045,
    .resource.font.header.height = 0x0015,
};
