/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.00.39 BETA

  Company:
      Microchip Technology, Inc.
 
  File Name:
     gfx_resources_int.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef GFX_RESOURCES_INT_H_FILE
#define GFX_RESOURCES_INT_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Firmware Check
 *****************************************************************************/
#if(GRAPHICS_LIBRARY_VERSION != 0x0400)
#warning "It is suggested to use Graphics Library version 4.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif


/*****************************************************************************
 * SECTION: Graphics Configuration
 * Overview:    This defines the size of the buffer used by font functions
 *              to retrieve font data from the external memory. The buffer
 *              size can be increased to accommodate large font sizes.
 *              The user must be aware of the expected glyph sizes of the 
 *              characters stored in the font table. 
 *              To modify the size used, declare this macro in the 
 *              GraphicsConfig.h file with the desired size.
 *
 * #define GFX_EXTERNAL_FONT_RASTER_BUFFER_SIZE     (63)
 *****************************************************************************/

/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: cog
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR cog;
#define cog_WIDTH     (60)
#define cog_HEIGHT    (60)
#define cog_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: cog_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR cog_outline;
#define cog_outline_WIDTH     (60)
#define cog_outline_HEIGHT    (60)
#define cog_outline_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: layers_image
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR layers_image;
#define layers_image_WIDTH     (60)
#define layers_image_HEIGHT    (60)
#define layers_image_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: layers_image_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR layers_image_outline;
#define layers_image_outline_WIDTH     (60)
#define layers_image_outline_HEIGHT    (60)
#define layers_image_outline_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: location_pin
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR location_pin;
#define location_pin_WIDTH     (60)
#define location_pin_HEIGHT    (60)
#define location_pin_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: location_pin_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR location_pin_outline;
#define location_pin_outline_WIDTH     (60)
#define location_pin_outline_HEIGHT    (60)
#define location_pin_outline_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: script_invert
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR script_invert;
#define script_invert_WIDTH     (60)
#define script_invert_HEIGHT    (60)
#define script_invert_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: script_outline
 * Description:  60x60 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR script_outline;
#define script_outline_WIDTH     (60)
#define script_outline_HEIGHT    (60)
#define script_outline_SIZE      (490)
/*********************************
 * Bitmap Structure
 * Label: NewHarmonyLogo_Small
 * Description:  172x120 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR NewHarmonyLogo_Small;
#define NewHarmonyLogo_Small_WIDTH     (172)
#define NewHarmonyLogo_Small_HEIGHT    (120)
#define NewHarmonyLogo_Small_SIZE      (41286)
/*********************************
 * Bitmap Structure
 * Label: cs_FeatureList
 * Description:  321x200 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR cs_FeatureList;
#define cs_FeatureList_WIDTH     (321)
#define cs_FeatureList_HEIGHT    (200)
#define cs_FeatureList_SIZE      (128406)
/*********************************
 * Bitmap Structure
 * Label: ct_FeatureList
 * Description:  313x200 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR ct_FeatureList;
#define ct_FeatureList_WIDTH     (313)
#define ct_FeatureList_HEIGHT    (200)
#define ct_FeatureList_SIZE      (125206)
/*********************************
 * Bitmap Structure
 * Label: cs_SlideShowInstructions
 * Description:  400x181 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR cs_SlideShowInstructions;
#define cs_SlideShowInstructions_WIDTH     (400)
#define cs_SlideShowInstructions_HEIGHT    (181)
#define cs_SlideShowInstructions_SIZE      (144806)
/*********************************
 * Bitmap Structure
 * Label: ct_SlideShowInstructions
 * Description:  400x181 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR ct_SlideShowInstructions;
#define ct_SlideShowInstructions_WIDTH     (400)
#define ct_SlideShowInstructions_HEIGHT    (181)
#define ct_SlideShowInstructions_SIZE      (144806)
/*********************************
 * Bitmap Structure
 * Label: TestImage
 * Description:  344x169 pixels, 8-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR TestImage;
#define TestImage_WIDTH     (344)
#define TestImage_HEIGHT    (169)
#define TestImage_SIZE      (58654)
/*********************************
 * Bitmap Structure
 * Label: home_outline
 * Description:  30x30 pixels, 4-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR home_outline;
#define home_outline_WIDTH     (30)
#define home_outline_HEIGHT    (30)
#define home_outline_SIZE      (488)
/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton_Outline
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR RoundHomeButton_Outline;
#define RoundHomeButton_Outline_WIDTH     (90)
#define RoundHomeButton_Outline_HEIGHT    (89)
#define RoundHomeButton_Outline_SIZE      (16026)
/*********************************
 * Bitmap Structure
 * Label: RoundHomeButton
 * Description:  90x89 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR RoundHomeButton;
#define RoundHomeButton_WIDTH     (90)
#define RoundHomeButton_HEIGHT    (89)
#define RoundHomeButton_SIZE      (16026)
/*********************************
 * Bitmap Structure
 * Label: microchipLogo_small
 * Description:  220x120 pixels, 16-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR microchipLogo_small;
#define microchipLogo_small_WIDTH     (220)
#define microchipLogo_small_HEIGHT    (120)
#define microchipLogo_small_SIZE      (52806)
/*****************************************************************************
 * SECTION:  JPEGS
 *****************************************************************************/

/*********************************
 * JPEG Structure
 * Label: AutumnGrass_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR AutumnGrass_JPEG;
#define AutumnGrass_JPEG_WIDTH     (453)
#define AutumnGrass_JPEG_HEIGHT    (272)
#define AutumnGrass_JPEG_SIZE      (29397)
/*********************************
 * JPEG Structure
 * Label: BoraBoraSunset_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR BoraBoraSunset_JPEG;
#define BoraBoraSunset_JPEG_WIDTH     (453)
#define BoraBoraSunset_JPEG_HEIGHT    (272)
#define BoraBoraSunset_JPEG_SIZE      (27992)
/*********************************
 * JPEG Structure
 * Label: CoalHarbourDay_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR CoalHarbourDay_JPEG;
#define CoalHarbourDay_JPEG_WIDTH     (453)
#define CoalHarbourDay_JPEG_HEIGHT    (272)
#define CoalHarbourDay_JPEG_SIZE      (24985)
/*********************************
 * JPEG Structure
 * Label: ColorPalette_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR ColorPalette_JPEG;
#define ColorPalette_JPEG_WIDTH     (453)
#define ColorPalette_JPEG_HEIGHT    (272)
#define ColorPalette_JPEG_SIZE      (7068)
/*********************************
 * JPEG Structure
 * Label: DowntownVancouver_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR DowntownVancouver_JPEG;
#define DowntownVancouver_JPEG_WIDTH     (453)
#define DowntownVancouver_JPEG_HEIGHT    (272)
#define DowntownVancouver_JPEG_SIZE      (30961)
/*********************************
 * JPEG Structure
 * Label: EnglishBayFireworks_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR EnglishBayFireworks_JPEG;
#define EnglishBayFireworks_JPEG_WIDTH     (453)
#define EnglishBayFireworks_JPEG_HEIGHT    (272)
#define EnglishBayFireworks_JPEG_SIZE      (20229)
/*********************************
 * JPEG Structure
 * Label: FalseCreek_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR FalseCreek_JPEG;
#define FalseCreek_JPEG_WIDTH     (453)
#define FalseCreek_JPEG_HEIGHT    (272)
#define FalseCreek_JPEG_SIZE      (24056)
/*********************************
 * JPEG Structure
 * Label: Fishes_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Fishes_JPEG;
#define Fishes_JPEG_WIDTH     (453)
#define Fishes_JPEG_HEIGHT    (272)
#define Fishes_JPEG_SIZE      (20815)
/*********************************
 * JPEG Structure
 * Label: MicrochipLogo_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR MicrochipLogo_JPEG;
#define MicrochipLogo_JPEG_WIDTH     (453)
#define MicrochipLogo_JPEG_HEIGHT    (272)
#define MicrochipLogo_JPEG_SIZE      (9350)
/*********************************
 * JPEG Structure
 * Label: NewHarmonyLogo_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR NewHarmonyLogo_JPEG;
#define NewHarmonyLogo_JPEG_WIDTH     (453)
#define NewHarmonyLogo_JPEG_HEIGHT    (272)
#define NewHarmonyLogo_JPEG_SIZE      (14191)
/*********************************
 * JPEG Structure
 * Label: ParkTrees_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR ParkTrees_JPEG;
#define ParkTrees_JPEG_WIDTH     (453)
#define ParkTrees_JPEG_HEIGHT    (272)
#define ParkTrees_JPEG_SIZE      (39609)
/*********************************
 * JPEG Structure
 * Label: Rockies_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Rockies_JPEG;
#define Rockies_JPEG_WIDTH     (453)
#define Rockies_JPEG_HEIGHT    (272)
#define Rockies_JPEG_SIZE      (29556)
/*********************************
 * JPEG Structure
 * Label: ScienceWorldNight_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR ScienceWorldNight_JPEG;
#define ScienceWorldNight_JPEG_WIDTH     (453)
#define ScienceWorldNight_JPEG_HEIGHT    (272)
#define ScienceWorldNight_JPEG_SIZE      (21851)
/*********************************
 * JPEG Structure
 * Label: Sherwood_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Sherwood_JPEG;
#define Sherwood_JPEG_WIDTH     (453)
#define Sherwood_JPEG_HEIGHT    (272)
#define Sherwood_JPEG_SIZE      (36791)
/*********************************
 * JPEG Structure
 * Label: SnowLeopard_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR SnowLeopard_JPEG;
#define SnowLeopard_JPEG_WIDTH     (453)
#define SnowLeopard_JPEG_HEIGHT    (272)
#define SnowLeopard_JPEG_SIZE      (17839)
/*********************************
 * JPEG Structure
 * Label: SnowyHills_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR SnowyHills_JPEG;
#define SnowyHills_JPEG_WIDTH     (453)
#define SnowyHills_JPEG_HEIGHT    (272)
#define SnowyHills_JPEG_SIZE      (23877)
/*********************************
 * JPEG Structure
 * Label: Splash_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Splash_JPEG;
#define Splash_JPEG_WIDTH     (453)
#define Splash_JPEG_HEIGHT    (272)
#define Splash_JPEG_SIZE      (12271)
/*********************************
 * JPEG Structure
 * Label: Waterfall_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Waterfall_JPEG;
#define Waterfall_JPEG_WIDTH     (453)
#define Waterfall_JPEG_HEIGHT    (272)
#define Waterfall_JPEG_SIZE      (23947)
/*********************************
 * JPEG Structure
 * Label: Wheats_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR Wheats_JPEG;
#define Wheats_JPEG_WIDTH     (453)
#define Wheats_JPEG_HEIGHT    (272)
#define Wheats_JPEG_SIZE      (15352)
/*********************************
 * JPEG Structure
 * Label: MacBethChart_JPEG
 * Description:  453x272 pixels
 ***********************************/
extern const GFX_RESOURCE_HDR MacBethChart_JPEG;
#define MacBethChart_JPEG_WIDTH     (453)
#define MacBethChart_JPEG_HEIGHT    (272)
#define MacBethChart_JPEG_SIZE      (9860)
/*****************************************************************************
 * SECTION:  Fonts
 *****************************************************************************/

/*********************************
 * TTF Font File Structure
 * Label: VeraMono
 * Description:  Height: 15 pixels, 1 bit per pixel, Range: ' ' to ''
 ***********************************/
extern const GFX_RESOURCE_HDR VeraMono;
#define VeraMono_SIZE    (1847)
/*********************************
 * TTF Font File Structure
 * Label: SimHei18
 * Description:  Height: 21 pixels, 1 bit per pixel, Range: '?' to '?'
 ***********************************/
extern const GFX_RESOURCE_HDR SimHei18;
#define SimHei18_SIZE    (2554)
#endif

