/*******************************************************************************
  MPLAB Harmony Graphics Composer Generated Definitions Header

  File Name:
    gfx_hgc_definitions.h

  Summary:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

  Description:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

    Created with MPLAB Harmony Version 2.00
*******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
Copyright (c) 2013-2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*******************************************************************************/
// DOM-IGNORE-END


#ifndef _GFX_HGC_DEFINITIONS_H
#define _GFX_HGC_DEFINITIONS_H

#include "system_config.h"
#include "system_definitions.h"

// DOM-IGNORE-BEGIN
#ifdef __cplusplus  // Provide C++ Compatibility

extern "C" {

#endif
// DOM-IGNORE-END 

typedef enum
{
    HGC_STATE_INIT = 0,
    HGC_STATE_RUNNING
} HGC_STATES;

typedef enum
{
    HGC_SCREEN_STATE_INIT = 0,
    HGC_SCREEN_STATE_SETUP_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_ButtonScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_ButtonScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_EditBoxScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_EditBoxScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_ProgressBarScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_ProgressBarScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_TextEntryScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_TextEntryScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_ListBoxScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_ListBoxScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_MeterScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_MeterScreen,
	
} HGC_SCREEN_STATES;

/*** GFX GOL Scheme Definitions ***/

#define GFX_SCHEME_NAME_0                       "TextEntryScreen"
#define GFX_SCHEME_ALPHA_0                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_0      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_0     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_0          0x03
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_0        0x71
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_0         0x12

#define GFX_SCHEME_SECONDARY_COLOR_RED_0        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_0      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_0       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_0         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_0       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_0        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_0       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_0     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_0      0x00

#define GFX_SCHEME_EMBOSS_SIZE_0                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_0     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_0   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_0    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_0      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_0    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_0     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_0     0xF5
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_0   0xF9
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_0    0xF5

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_0   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_0 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_0  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_0    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_0  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_0   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_0    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_0  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_0   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_0    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_0  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_0   0xFF

#define GFX_SCHEME_FILL_STYLE_0                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_0           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_1                       "Window"
#define GFX_SCHEME_ALPHA_1                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_1      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_1     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_1          0x41
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_1        0x41
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_1         0xCC

#define GFX_SCHEME_SECONDARY_COLOR_RED_1        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_1      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_1       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_1         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_1       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_1        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_1       0xC0
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_1     0x97
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_1      0xD5

#define GFX_SCHEME_EMBOSS_SIZE_1                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_1     0xE6
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_1   0x94
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_1    0x9C

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_1      0xCD
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_1    0x1D
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_1     0x27

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_1     0xF5
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_1   0xF9
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_1    0xF5

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_1   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_1 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_1  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_1    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_1  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_1   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_1    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_1  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_1   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_1    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_1  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_1   0xFF

#define GFX_SCHEME_FILL_STYLE_1                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_1           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_2                       "default"
#define GFX_SCHEME_ALPHA_2                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_2      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_2     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_2          0x07
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_2        0x0B
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_2         0xF0

#define GFX_SCHEME_SECONDARY_COLOR_RED_2        0xC0
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_2      0x94
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_2       0xD8

#define GFX_SCHEME_DISABLED_COLOR_RED_2         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_2       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_2        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_2       0xC0
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_2     0x94
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_2      0xD8

#define GFX_SCHEME_EMBOSS_SIZE_2                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_2     0xEB
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_2   0xA7
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_2    0xB6

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_2      0xEE
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_2    0x63
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_2     0x63

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_2     0xF5
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_2   0xF9
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_2    0xF5

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_2   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_2 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_2  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_2    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_2  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_2   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_2    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_2  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_2   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_2    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_2  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_2   0xFF

#define GFX_SCHEME_FILL_STYLE_2                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_2           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_3                       "buttons"
#define GFX_SCHEME_ALPHA_3                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_3      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_3     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_3          0xF7
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_3        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_3         0x00

#define GFX_SCHEME_SECONDARY_COLOR_RED_3        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_3      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_3       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_3         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_3       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_3        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_3       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_3     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_3      0x00

#define GFX_SCHEME_EMBOSS_SIZE_3                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_3     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_3   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_3    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_3      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_3    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_3     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_3     0xF5
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_3   0xF9
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_3    0xF5

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_3   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_3 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_3  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_3    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_3  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_3   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_3    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_3  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_3   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_3    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_3  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_3   0xFF

#define GFX_SCHEME_FILL_STYLE_3                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_3           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_4                       "Meter"
#define GFX_SCHEME_ALPHA_4                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_4      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_4     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_4          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_4        0x10
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_4         0xE8

#define GFX_SCHEME_SECONDARY_COLOR_RED_4        0xF8
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_4      0xFC
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_4       0xF8

#define GFX_SCHEME_DISABLED_COLOR_RED_4         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_4       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_4        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_4       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_4     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_4      0x00

#define GFX_SCHEME_EMBOSS_SIZE_4                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_4     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_4   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_4    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_4      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_4    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_4     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_4     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_4   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_4    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_4   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_4 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_4  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_4    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_4  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_4   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_4    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_4  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_4   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_4    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_4  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_4   0xFF

#define GFX_SCHEME_FILL_STYLE_4                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_4           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_5                       "pressedButton"
#define GFX_SCHEME_ALPHA_5                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_5      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_5     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_5          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_5        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_5         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_5        0xFF
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_5      0xFF
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_5       0xFF

#define GFX_SCHEME_DISABLED_COLOR_RED_5         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_5       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_5        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_5       0xF8
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_5     0xFC
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_5      0xF8

#define GFX_SCHEME_EMBOSS_SIZE_5                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_5     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_5   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_5    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_5      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_5    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_5     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_5     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_5   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_5    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_5   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_5 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_5  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_5    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_5  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_5   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_5    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_5  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_5   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_5    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_5  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_5   0xFF

#define GFX_SCHEME_FILL_STYLE_5                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_5           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_6                       "staticText"
#define GFX_SCHEME_ALPHA_6                      0

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_6      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_6     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_6          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_6        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_6         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_6        0x00
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_6      0x00
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_6       0x00

#define GFX_SCHEME_DISABLED_COLOR_RED_6         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_6       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_6        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_6       0xC4
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_6     0xA4
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_6      0xF3

#define GFX_SCHEME_EMBOSS_SIZE_6                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_6     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_6   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_6    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_6      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_6    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_6     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_6     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_6   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_6    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_6   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_6 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_6  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_6    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_6  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_6   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_6    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_6  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_6   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_6    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_6  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_6   0xFF

#define GFX_SCHEME_FILL_STYLE_6                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_6           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_7                       "ListBoxScreen"
#define GFX_SCHEME_ALPHA_7                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_7      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_7     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_7          0xBA
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_7        0x87
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_7         0xF0

#define GFX_SCHEME_SECONDARY_COLOR_RED_7        0x96
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_7      0x0F
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_7       0xE9

#define GFX_SCHEME_DISABLED_COLOR_RED_7         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_7       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_7        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_7       0xBC
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_7     0x87
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_7      0xE9

#define GFX_SCHEME_EMBOSS_SIZE_7                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_7     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_7   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_7    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_7      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_7    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_7     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_7     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_7   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_7    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_7   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_7 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_7  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_7    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_7  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_7   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_7    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_7  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_7   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_7    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_7  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_7   0xFF

#define GFX_SCHEME_FILL_STYLE_7                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_7           GFX_BACKGROUND_NONE

		
/*** Screen IDs ***/
#define ButtonScreen                 0 
	
#define EditBoxScreen                 1 
	
#define ProgressBarScreen                 2 
	
#define TextEntryScreen                 3 
	
#define ListBoxScreen                 4 
	
#define MeterScreen                 5 
	
/*** GFX GOL Button Definitions ***/
#define GFX_BUTTON_LEFT_0            327
#define GFX_BUTTON_TOP_0             157
#define GFX_BUTTON_RIGHT_0           387
#define GFX_BUTTON_BOTTOM_0          217
#define GFX_BUTTON_TEXT_0            "0x4f, 0x66, 0x66, 0x0"
#define GFX_BUTTON_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_0          30
#define GFX_BUTTON_STATE_0           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_0     NULL
#define GFX_BUTTON_RELEASE_IMAGE_0   NULL
#define GFX_BUTTON_SCHEME_0          gfxScheme3
		
#define GFX_BUTTON_LEFT_1            245
#define GFX_BUTTON_TOP_1             158
#define GFX_BUTTON_RIGHT_1           305
#define GFX_BUTTON_BOTTOM_1          218
#define GFX_BUTTON_TEXT_1            "0x4f, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_1          30
#define GFX_BUTTON_STATE_1           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_1     NULL
#define GFX_BUTTON_RELEASE_IMAGE_1   NULL
#define GFX_BUTTON_SCHEME_1          gfxScheme3
		
#define GFX_BUTTON_LEFT_2            249
#define GFX_BUTTON_TOP_2             105
#define GFX_BUTTON_RIGHT_2           405
#define GFX_BUTTON_BOTTOM_2          148
#define GFX_BUTTON_TEXT_2            "0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x20, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_2          0
#define GFX_BUTTON_STATE_2           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_DISABLED_STATE
#define GFX_BUTTON_PRESS_IMAGE_2     NULL
#define GFX_BUTTON_RELEASE_IMAGE_2   NULL
#define GFX_BUTTON_SCHEME_2          gfxScheme2
		
#define GFX_BUTTON_LEFT_3            401
#define GFX_BUTTON_TOP_3             235
#define GFX_BUTTON_RIGHT_3           476
#define GFX_BUTTON_BOTTOM_3          266
#define GFX_BUTTON_TEXT_3            "0x4e, 0x65, 0x78, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_3       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_3          10
#define GFX_BUTTON_STATE_3           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_3     NULL
#define GFX_BUTTON_RELEASE_IMAGE_3   NULL
#define GFX_BUTTON_SCHEME_3          gfxScheme2
		
#define GFX_BUTTON_LEFT_4            63
#define GFX_BUTTON_TOP_4             166
#define GFX_BUTTON_RIGHT_4           228
#define GFX_BUTTON_BOTTOM_4          215
#define GFX_BUTTON_TEXT_4            "0x54, 0x77, 0x6f, 0x20, 0x54, 0x6f, 0x6e, 0x65, 0x0"
#define GFX_BUTTON_ALIGNMENT_4       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_4          10
#define GFX_BUTTON_STATE_4           GFX_GOL_BUTTON_DRAW_STATE | GFX_GOL_BUTTON_TWOTONE_STATE
#define GFX_BUTTON_PRESS_IMAGE_4     NULL
#define GFX_BUTTON_RELEASE_IMAGE_4   NULL
#define GFX_BUTTON_SCHEME_4          gfxScheme2
		
#define GFX_BUTTON_LEFT_5            62
#define GFX_BUTTON_TOP_5             106
#define GFX_BUTTON_RIGHT_5           227
#define GFX_BUTTON_BOTTOM_5          151
#define GFX_BUTTON_TEXT_5            "0x52, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x64, 0x20, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x0"
#define GFX_BUTTON_ALIGNMENT_5       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_5          15
#define GFX_BUTTON_STATE_5           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_5     NULL
#define GFX_BUTTON_RELEASE_IMAGE_5   NULL
#define GFX_BUTTON_SCHEME_5          gfxScheme3
		
#define GFX_BUTTON_LEFT_6            251
#define GFX_BUTTON_TOP_6             48
#define GFX_BUTTON_RIGHT_6           406
#define GFX_BUTTON_BOTTOM_6          98
#define GFX_BUTTON_TEXT_6            "0x0"
#define GFX_BUTTON_ALIGNMENT_6       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_6          0
#define GFX_BUTTON_STATE_6           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_6     (GFX_RESOURCE_HDR*)&bulbon
#define GFX_BUTTON_RELEASE_IMAGE_6   (GFX_RESOURCE_HDR*)&bulboff
#define GFX_BUTTON_SCHEME_6          gfxScheme5
		
#define GFX_BUTTON_LEFT_7            62
#define GFX_BUTTON_TOP_7             49
#define GFX_BUTTON_RIGHT_7           225
#define GFX_BUTTON_BOTTOM_7          97
#define GFX_BUTTON_TEXT_7            "0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x20, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_7       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_7          0
#define GFX_BUTTON_STATE_7           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_7     NULL
#define GFX_BUTTON_RELEASE_IMAGE_7   NULL
#define GFX_BUTTON_SCHEME_7          gfxScheme3
		
#define GFX_BUTTON_LEFT_8            401
#define GFX_BUTTON_TOP_8             235
#define GFX_BUTTON_RIGHT_8           476
#define GFX_BUTTON_BOTTOM_8          266
#define GFX_BUTTON_TEXT_8            "0x4e, 0x65, 0x78, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_8       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_8          10
#define GFX_BUTTON_STATE_8           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_8     NULL
#define GFX_BUTTON_RELEASE_IMAGE_8   NULL
#define GFX_BUTTON_SCHEME_8          gfxScheme2
		
#define GFX_BUTTON_LEFT_9            1
#define GFX_BUTTON_TOP_9             236
#define GFX_BUTTON_RIGHT_9           76
#define GFX_BUTTON_BOTTOM_9          267
#define GFX_BUTTON_TEXT_9            "0x50, 0x72, 0x65, 0x76, 0x2e, 0x0"
#define GFX_BUTTON_ALIGNMENT_9       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_9          10
#define GFX_BUTTON_STATE_9           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_9     NULL
#define GFX_BUTTON_RELEASE_IMAGE_9   NULL
#define GFX_BUTTON_SCHEME_9          gfxScheme2
		
#define GFX_BUTTON_LEFT_10            402
#define GFX_BUTTON_TOP_10             236
#define GFX_BUTTON_RIGHT_10           477
#define GFX_BUTTON_BOTTOM_10          267
#define GFX_BUTTON_TEXT_10            "0x4e, 0x65, 0x78, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_10       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_10          10
#define GFX_BUTTON_STATE_10           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_10     NULL
#define GFX_BUTTON_RELEASE_IMAGE_10   NULL
#define GFX_BUTTON_SCHEME_10          gfxScheme2
		
#define GFX_BUTTON_LEFT_11            3
#define GFX_BUTTON_TOP_11             237
#define GFX_BUTTON_RIGHT_11           78
#define GFX_BUTTON_BOTTOM_11          268
#define GFX_BUTTON_TEXT_11            "0x50, 0x72, 0x65, 0x76, 0x2e, 0x0"
#define GFX_BUTTON_ALIGNMENT_11       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_11          10
#define GFX_BUTTON_STATE_11           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_11     NULL
#define GFX_BUTTON_RELEASE_IMAGE_11   NULL
#define GFX_BUTTON_SCHEME_11          gfxScheme2
		
#define GFX_BUTTON_LEFT_12            8
#define GFX_BUTTON_TOP_12             235
#define GFX_BUTTON_RIGHT_12           83
#define GFX_BUTTON_BOTTOM_12          266
#define GFX_BUTTON_TEXT_12            "0x50, 0x72, 0x65, 0x76, 0x2e, 0x0"
#define GFX_BUTTON_ALIGNMENT_12       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_12          10
#define GFX_BUTTON_STATE_12           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_12     NULL
#define GFX_BUTTON_RELEASE_IMAGE_12   NULL
#define GFX_BUTTON_SCHEME_12          gfxScheme2
		
#define GFX_BUTTON_LEFT_13            402
#define GFX_BUTTON_TOP_13             236
#define GFX_BUTTON_RIGHT_13           477
#define GFX_BUTTON_BOTTOM_13          267
#define GFX_BUTTON_TEXT_13            "0x4e, 0x65, 0x78, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_13       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_13          10
#define GFX_BUTTON_STATE_13           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_13     NULL
#define GFX_BUTTON_RELEASE_IMAGE_13   NULL
#define GFX_BUTTON_SCHEME_13          gfxScheme2
		
#define GFX_BUTTON_LEFT_14            402
#define GFX_BUTTON_TOP_14             236
#define GFX_BUTTON_RIGHT_14           477
#define GFX_BUTTON_BOTTOM_14          267
#define GFX_BUTTON_TEXT_14            "0x4e, 0x65, 0x78, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_14       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_14          10
#define GFX_BUTTON_STATE_14           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_14     NULL
#define GFX_BUTTON_RELEASE_IMAGE_14   NULL
#define GFX_BUTTON_SCHEME_14          gfxScheme2
		
#define GFX_BUTTON_LEFT_15            339
#define GFX_BUTTON_TOP_15             229
#define GFX_BUTTON_RIGHT_15           368
#define GFX_BUTTON_BOTTOM_15          249
#define GFX_BUTTON_TEXT_15            "0x76, 0x0"
#define GFX_BUTTON_ALIGNMENT_15       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_15          0
#define GFX_BUTTON_STATE_15           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_15     NULL
#define GFX_BUTTON_RELEASE_IMAGE_15   NULL
#define GFX_BUTTON_SCHEME_15          gfxScheme7
		
#define GFX_BUTTON_LEFT_16            339
#define GFX_BUTTON_TOP_16             113
#define GFX_BUTTON_RIGHT_16           369
#define GFX_BUTTON_BOTTOM_16          136
#define GFX_BUTTON_TEXT_16            "0x5e, 0x0"
#define GFX_BUTTON_ALIGNMENT_16       GFX_ALIGN_HCENTER | GFX_ALIGN_BOTTOM
#define GFX_BUTTON_RADIUS_16          0
#define GFX_BUTTON_STATE_16           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_16     NULL
#define GFX_BUTTON_RELEASE_IMAGE_16   NULL
#define GFX_BUTTON_SCHEME_16          gfxScheme7
		
#define GFX_BUTTON_LEFT_17            2
#define GFX_BUTTON_TOP_17             237
#define GFX_BUTTON_RIGHT_17           77
#define GFX_BUTTON_BOTTOM_17          268
#define GFX_BUTTON_TEXT_17            "0x50, 0x72, 0x65, 0x76, 0x2e, 0x0"
#define GFX_BUTTON_ALIGNMENT_17       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_17          10
#define GFX_BUTTON_STATE_17           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_17     NULL
#define GFX_BUTTON_RELEASE_IMAGE_17   NULL
#define GFX_BUTTON_SCHEME_17          gfxScheme2
		
#define GFX_BUTTON_LEFT_18            174
#define GFX_BUTTON_TOP_18             221
#define GFX_BUTTON_RIGHT_18           299
#define GFX_BUTTON_BOTTOM_18          263
#define GFX_BUTTON_TEXT_18            "0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x65, 0x0"
#define GFX_BUTTON_ALIGNMENT_18       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_18          10
#define GFX_BUTTON_STATE_18           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_18     NULL
#define GFX_BUTTON_RELEASE_IMAGE_18   NULL
#define GFX_BUTTON_SCHEME_18          gfxScheme2
		
#define GFX_BUTTON_LEFT_19            2
#define GFX_BUTTON_TOP_19             237
#define GFX_BUTTON_RIGHT_19           77
#define GFX_BUTTON_BOTTOM_19          268
#define GFX_BUTTON_TEXT_19            "0x50, 0x72, 0x65, 0x76, 0x2e, 0x0"
#define GFX_BUTTON_ALIGNMENT_19       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_19          10
#define GFX_BUTTON_STATE_19           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_19     NULL
#define GFX_BUTTON_RELEASE_IMAGE_19   NULL
#define GFX_BUTTON_SCHEME_19          gfxScheme2
		
/*** Button IDs ***/
#define Button25                  1000 
	
#define Button24                  1001 
	
#define Button23                  1002 
	
#define Button22                  1003 
	
#define Button21                  1004 
	
#define Button20                  1005 
	
#define Button19                  1006 
	
#define Button18                  1007 
	
#define Button2                  1008 
	
#define Button1                  1009 
	
#define Button4                  1010 
	
#define Button3                  1011 
	
#define Button5                  1012 
	
#define Button6                  1013 
	
#define Button10                  1014 
	
#define Button9                  1015 
	
#define Button8                  1016 
	
#define Button7                  1017 
	
#define Button12                  1018 
	
#define Button11                  1019 
	
/*** GFX GOL Digital Meter Definitions ***/

#define GFX_DGTL_MTR_LEFT_0            192
#define GFX_DGTL_MTR_TOP_0             117
#define GFX_DGTL_MTR_RIGHT_0           281
#define GFX_DGTL_MTR_BOTTOM_0          160
#define GFX_DGTL_MTR_STATE_0           GFX_GOL_DIGITALMETER_DRAW_STATE
#define GFX_DGTL_MTR_VALUE_0           0
#define GFX_DGTL_MTR_NO_OF_DIGITS_0    3
#define GFX_DGTL_MTR_DOT_POSITION_0    1
#define GFX_DGTL_MTR_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_DGTL_MTR_SCHEME_0          gfxScheme3
		
/*** Digital Meter IDs ***/
#define DigitalMeter1                  2000 
	
/*** GFX GOL Checkbox Definitions ***/

#define GFX_CHECKBOX_LEFT_0            266
#define GFX_CHECKBOX_TOP_0             67
#define GFX_CHECKBOX_RIGHT_0           416
#define GFX_CHECKBOX_BOTTOM_0          95
#define GFX_CHECKBOX_TEXT_0            "0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x0"
#define GFX_CHECKBOX_STATE_0    		  GFX_GOL_CHECKBOX_DRAW_STATE | GFX_GOL_CHECKBOX_DRAW_CHECK_STATE | GFX_GOL_CHECKBOX_CHECKED_STATE
#define GFX_CHECKBOX_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_CHECKBOX_SCHEME_0          gfxScheme1
		
/*** Checkbox IDs ***/
#define CheckBox1                  3000 
	
/*** GFX GOL Radio Button Definitions ***/

#define GFX_RADIOBUTTON_LEFT_0            97
#define GFX_RADIOBUTTON_TOP_0             193
#define GFX_RADIOBUTTON_RIGHT_0           167
#define GFX_RADIOBUTTON_BOTTOM_0          220
#define GFX_RADIOBUTTON_TEXT_0            "0x54, 0x6f, 0x70, 0x0"
#define GFX_RADIOBUTTON_STATE_0    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_0          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_0          1
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_0   2
		

#define GFX_RADIOBUTTON_LEFT_1            315
#define GFX_RADIOBUTTON_TOP_1             193
#define GFX_RADIOBUTTON_RIGHT_1           409
#define GFX_RADIOBUTTON_BOTTOM_1          220
#define GFX_RADIOBUTTON_TEXT_1            "0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x0"
#define GFX_RADIOBUTTON_STATE_1    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_1       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_1          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_1          1
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_1   2
		

#define GFX_RADIOBUTTON_LEFT_2            198
#define GFX_RADIOBUTTON_TOP_2             193
#define GFX_RADIOBUTTON_RIGHT_2           288
#define GFX_RADIOBUTTON_BOTTOM_2          219
#define GFX_RADIOBUTTON_TEXT_2            "0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x0"
#define GFX_RADIOBUTTON_STATE_2    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_CHECKED_STATE | GFX_GOL_RADIOBUTTON_DRAW_CHECK_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_2       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_2          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_2          1
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_2   2
		

#define GFX_RADIOBUTTON_LEFT_3            315
#define GFX_RADIOBUTTON_TOP_3             135
#define GFX_RADIOBUTTON_RIGHT_3           402
#define GFX_RADIOBUTTON_BOTTOM_3          161
#define GFX_RADIOBUTTON_TEXT_3            "0x52, 0x69, 0x67, 0x68, 0x74, 0x0"
#define GFX_RADIOBUTTON_STATE_3    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_3       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_3          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_3          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_3   2
		

#define GFX_RADIOBUTTON_LEFT_4            198
#define GFX_RADIOBUTTON_TOP_4             135
#define GFX_RADIOBUTTON_RIGHT_4           299
#define GFX_RADIOBUTTON_BOTTOM_4          161
#define GFX_RADIOBUTTON_TEXT_4            "0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x0"
#define GFX_RADIOBUTTON_STATE_4    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_CHECKED_STATE | GFX_GOL_RADIOBUTTON_DRAW_CHECK_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_4       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_4          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_4          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_4   2
		

#define GFX_RADIOBUTTON_LEFT_5            97
#define GFX_RADIOBUTTON_TOP_5             135
#define GFX_RADIOBUTTON_RIGHT_5           174
#define GFX_RADIOBUTTON_BOTTOM_5          163
#define GFX_RADIOBUTTON_TEXT_5            "0x4c, 0x65, 0x66, 0x74, 0x0"
#define GFX_RADIOBUTTON_STATE_5    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_GROUP_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_5       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_5          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_5          0
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_5   2
		

#define GFX_RADIOBUTTON_LEFT_6            304
#define GFX_RADIOBUTTON_TOP_6             62
#define GFX_RADIOBUTTON_RIGHT_6           422
#define GFX_RADIOBUTTON_BOTTOM_6          97
#define GFX_RADIOBUTTON_TEXT_6            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x43, 0x0"
#define GFX_RADIOBUTTON_STATE_6    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_6       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_6          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_6          2
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_6   1
		

#define GFX_RADIOBUTTON_LEFT_7            172
#define GFX_RADIOBUTTON_TOP_7             62
#define GFX_RADIOBUTTON_RIGHT_7           302
#define GFX_RADIOBUTTON_BOTTOM_7          97
#define GFX_RADIOBUTTON_TEXT_7            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x42, 0x0"
#define GFX_RADIOBUTTON_STATE_7    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_CHECKED_STATE | GFX_GOL_RADIOBUTTON_DRAW_CHECK_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_7       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_7          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_7          2
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_7   1
		

#define GFX_RADIOBUTTON_LEFT_8            52
#define GFX_RADIOBUTTON_TOP_8             62
#define GFX_RADIOBUTTON_RIGHT_8           202
#define GFX_RADIOBUTTON_BOTTOM_8          97
#define GFX_RADIOBUTTON_TEXT_8            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x41, 0x0"
#define GFX_RADIOBUTTON_STATE_8    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_GROUP_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_8       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_8          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_8          2
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_8   1
		

#define GFX_RADIOBUTTON_LEFT_9            300
#define GFX_RADIOBUTTON_TOP_9             62
#define GFX_RADIOBUTTON_RIGHT_9           389
#define GFX_RADIOBUTTON_BOTTOM_9          93
#define GFX_RADIOBUTTON_TEXT_9            "0x52, 0x69, 0x67, 0x68, 0x74, 0x0"
#define GFX_RADIOBUTTON_STATE_9    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_9       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_9          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_9          3
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_9   1
		

#define GFX_RADIOBUTTON_LEFT_10            186
#define GFX_RADIOBUTTON_TOP_10             62
#define GFX_RADIOBUTTON_RIGHT_10           294
#define GFX_RADIOBUTTON_BOTTOM_10          93
#define GFX_RADIOBUTTON_TEXT_10            "0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x0"
#define GFX_RADIOBUTTON_STATE_10    		  GFX_GOL_RADIOBUTTON_DRAW_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_10       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_10          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_10          3
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_10   1
		

#define GFX_RADIOBUTTON_LEFT_11            84
#define GFX_RADIOBUTTON_TOP_11             61
#define GFX_RADIOBUTTON_RIGHT_11           164
#define GFX_RADIOBUTTON_BOTTOM_11          92
#define GFX_RADIOBUTTON_TEXT_11            "0x4c, 0x65, 0x66, 0x74, 0x0"
#define GFX_RADIOBUTTON_STATE_11    		  GFX_GOL_RADIOBUTTON_DRAW_STATE | GFX_GOL_RADIOBUTTON_CHECKED_STATE | GFX_GOL_RADIOBUTTON_DRAW_CHECK_STATE | GFX_GOL_RADIOBUTTON_GROUP_STATE
#define GFX_RADIOBUTTON_ALIGNMENT_11       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_RADIOBUTTON_SCHEME_11          gfxScheme1
#define GFX_RADIOBUTTON_GROUPNO_11          3
#define GFX_RADIOBUTTON_NUM_GROUPS_ON_SCREEN_11   1
		
/*** Radio Button IDs ***/
#define RadioButton10                  4000 
	
#define RadioButton12                  4001 
	
#define RadioButton11                  4002 
	
#define RadioButton9                  4003 
	
#define RadioButton8                  4004 
	
#define RadioButton7                  4005 
	
#define RadioButton3                  4006 
	
#define RadioButton2                  4007 
	
#define RadioButton1                  4008 
	
#define RadioButton6                  4009 
	
#define RadioButton5                  4010 
	
#define RadioButton4                  4011 
	
/*** GFX GOL Scrollbar Definitions ***/
#define GFX_SCROLLBAR_LEFT_0            	340
#define GFX_SCROLLBAR_TOP_0             	137
#define GFX_SCROLLBAR_RIGHT_0           	368
#define GFX_SCROLLBAR_BOTTOM_0          	228
#define GFX_SCROLLBAR_STATE_0            GFX_GOL_SCROLLBAR_DRAW_STATE | GFX_GOL_SCROLLBAR_DRAW_THUMB_STATE | GFX_GOL_SCROLLBAR_VERTICAL_STATE
#define GFX_SCROLLBAR_RANGE_0            9
#define GFX_SCROLLBAR_PAGE_0             1
#define GFX_SCROLLBAR_POS_0              9
#define GFX_SCROLLBAR_SCHEME_0           gfxScheme7
		
/*** Scrollbar IDs ***/
#define Slider1                  5000 
	
/*** GFX GOL Edit box Definitions ***/
#define GFX_EDITBOX_LEFT_0            60
#define GFX_EDITBOX_TOP_0             52
#define GFX_EDITBOX_RIGHT_0           232
#define GFX_EDITBOX_BOTTOM_0          106
#define GFX_EDITBOX_STATE_0           GFX_GOL_EDITBOX_DRAW_STATE
#define GFX_EDITBOX_TEXT_0            "0x45, 0x64, 0x69, 0x74, 0x20, 0x42, 0x6f, 0x78, 0x0"
#define GFX_EDITBOX_NOOFCHARS_0       15
#define GFX_EDITBOX_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_EDITBOX_SCHEME_0          gfxScheme2
		
/*** Edit Box IDs ***/
#define EditBox3                  6000 
	
/*** GFX GOL List box Definitions ***/
#define GFX_LISTBOX_LEFT_0            138
#define GFX_LISTBOX_TOP_0             115
#define GFX_LISTBOX_RIGHT_0           335
#define GFX_LISTBOX_BOTTOM_0          248
#define GFX_LISTBOX_STATE_0           GFX_GOL_LISTBOX_DRAW_STATE
#define GFX_LISTBOX_SCHEME_0          gfxScheme7
#define GFX_LISTBOX_ALIGNMENT_0       GFX_ALIGN_LEFT
#define GFX_LISTBOX_ITEM_COUNT_0      10

#define GFX_LISTBOX_0_ITEM_0_USERDATA    0
#define GFX_LISTBOX_0_ITEM_1_USERDATA    0
#define GFX_LISTBOX_0_ITEM_2_USERDATA    0
#define GFX_LISTBOX_0_ITEM_3_USERDATA    0
#define GFX_LISTBOX_0_ITEM_4_USERDATA    0
#define GFX_LISTBOX_0_ITEM_5_USERDATA    0
#define GFX_LISTBOX_0_ITEM_6_USERDATA    0
#define GFX_LISTBOX_0_ITEM_7_USERDATA    0
#define GFX_LISTBOX_0_ITEM_8_USERDATA    0
#define GFX_LISTBOX_0_ITEM_9_USERDATA    0
		
/*** List Box IDs ***/
#define ListBox2                  7000 
/*** GFX GOL Group box Definitions ***/
#define GFX_GROUPBOX_LEFT_0            60
#define GFX_GROUPBOX_TOP_0             172
#define GFX_GROUPBOX_RIGHT_0           433
#define GFX_GROUPBOX_BOTTOM_0          231
#define GFX_GROUPBOX_STATE_0           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_0          gfxScheme1
#define GFX_GROUPBOX_ALIGNMENT_0       GFX_ALIGN_HCENTER

		
#define GFX_GROUPBOX_LEFT_1            61
#define GFX_GROUPBOX_TOP_1             113
#define GFX_GROUPBOX_RIGHT_1           433
#define GFX_GROUPBOX_BOTTOM_1          171
#define GFX_GROUPBOX_STATE_1           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_1          gfxScheme1
#define GFX_GROUPBOX_ALIGNMENT_1       GFX_ALIGN_HCENTER

		
#define GFX_GROUPBOX_LEFT_2            243
#define GFX_GROUPBOX_TOP_2             45
#define GFX_GROUPBOX_RIGHT_2           433
#define GFX_GROUPBOX_BOTTOM_2          106
#define GFX_GROUPBOX_STATE_2           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_2          gfxScheme1
#define GFX_GROUPBOX_ALIGNMENT_2       GFX_ALIGN_HCENTER

		
#define GFX_GROUPBOX_LEFT_3            42
#define GFX_GROUPBOX_TOP_3             39
#define GFX_GROUPBOX_RIGHT_3           440
#define GFX_GROUPBOX_BOTTOM_3          115
#define GFX_GROUPBOX_STATE_3           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_3          gfxScheme1
#define GFX_GROUPBOX_ALIGNMENT_3       GFX_ALIGN_HCENTER

		
#define GFX_GROUPBOX_LEFT_4            55
#define GFX_GROUPBOX_TOP_4             39
#define GFX_GROUPBOX_RIGHT_4           439
#define GFX_GROUPBOX_BOTTOM_4          105
#define GFX_GROUPBOX_STATE_4           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_4          gfxScheme1
#define GFX_GROUPBOX_ALIGNMENT_4       GFX_ALIGN_HCENTER

		
/*** Group Box IDs ***/
#define GroupBox5                  8000 
#define GroupBox3                  8001 
#define GroupBox4                  8002 
#define GroupBox1                  8003 
#define GroupBox2                  8004 
/*** GFX GOL Button Definitions ***/
#define GFX_STATICTEXT_LEFT_0            42
#define GFX_STATICTEXT_TOP_0             194
#define GFX_STATICTEXT_RIGHT_0           129
#define GFX_STATICTEXT_BOTTOM_0          217
#define GFX_STATICTEXT_STATE_0          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_0            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x43, 0x3a, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_0          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_1            42
#define GFX_STATICTEXT_TOP_1             162
#define GFX_STATICTEXT_RIGHT_1           120
#define GFX_STATICTEXT_BOTTOM_1          185
#define GFX_STATICTEXT_STATE_1          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_1            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x42, 0x3a, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_1       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_1          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_2            42
#define GFX_STATICTEXT_TOP_2             129
#define GFX_STATICTEXT_RIGHT_2           124
#define GFX_STATICTEXT_BOTTOM_2          152
#define GFX_STATICTEXT_STATE_2          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_2            "0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x41, 0x3a, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_2       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_2          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_3            22
#define GFX_STATICTEXT_TOP_3             76
#define GFX_STATICTEXT_RIGHT_3           122
#define GFX_STATICTEXT_BOTTOM_3          98
#define GFX_STATICTEXT_STATE_3          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_3            "0x61, 0x6e, 0x64, 0x20, 0x50, 0x72, 0x65, 0x73, 0x73, 0x20, 0x4f, 0x6b, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_3       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_3          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_4            21
#define GFX_STATICTEXT_TOP_4             108
#define GFX_STATICTEXT_RIGHT_4           177
#define GFX_STATICTEXT_BOTTOM_4          225
#define GFX_STATICTEXT_STATE_4          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_4            "0x0"
#define GFX_STATICTEXT_ALIGNMENT_4       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_4          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_5            21
#define GFX_STATICTEXT_TOP_5             53
#define GFX_STATICTEXT_RIGHT_5           163
#define GFX_STATICTEXT_BOTTOM_5          74
#define GFX_STATICTEXT_STATE_5          GFX_GOL_STATICTEXT_DRAW_STATE
#define GFX_STATICTEXT_TEXT_5            "0x45, 0x6e, 0x74, 0x65, 0x72, 0x20, 0x79, 0x6f, 0x75, 0x72, 0x20, 0x6e, 0x61, 0x6d, 0x65, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_5       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_5          gfxScheme1
		
/*** static text IDs ***/
#define StaticText3                  9000 
	
#define StaticText2                  9001 
	
#define StaticText1                  9002 
	
#define StaticText6                  9003 
	
#define StaticText5                  9004 
	
#define StaticText4                  9005 
	
/*** GFX GOL Text Entry Definitions ***/
#define HGC_TEXTENTRY_LEFT_0           198
#define HGC_TEXTENTRY_TOP_0            54
#define HGC_TEXTENTRY_RIGHT_0          456
#define HGC_TEXTENTRY_BOTTOM_0         224
#define HGC_TEXTENTRY_STATE_0          GFX_GOL_TEXTENTRY_DRAW_STATE
#define HGC_TEXTENTRY_SCHEME_0         gfxScheme7
#define HGC_TEXTENTRY_BUFFERSIZE_0     35
#define HGC_TEXTENTRY_ALIGNMENT_0      GFX_ALIGN_LEFT
#define HGC_TEXTENTRY_ROW_COUNT_0      7
#define HGC_TEXTENTRY_COLUMN_COUNT_0   4

		
/*** Text Entry IDs ***/
#define TextEntry2                  10000 

/*** GFX GOL windows Definitions ***/
#define GFX_WINDOW_LEFT_0            2
#define GFX_WINDOW_TOP_0             1
#define GFX_WINDOW_RIGHT_0           480
#define GFX_WINDOW_BOTTOM_0          271
#define GFX_WINDOW_STATE_0           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_0           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_0            "0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73, 0x0"
#define GFX_WINDOW_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_0          gfxScheme1
		
#define GFX_WINDOW_LEFT_1            1
#define GFX_WINDOW_TOP_1             1
#define GFX_WINDOW_RIGHT_1           479
#define GFX_WINDOW_BOTTOM_1          271
#define GFX_WINDOW_STATE_1           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_1           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_1            "0x45, 0x64, 0x69, 0x74, 0x20, 0x42, 0x6f, 0x78, 0x0"
#define GFX_WINDOW_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_1          gfxScheme1
		
#define GFX_WINDOW_LEFT_2            1
#define GFX_WINDOW_TOP_2             1
#define GFX_WINDOW_RIGHT_2           479
#define GFX_WINDOW_BOTTOM_2          271
#define GFX_WINDOW_STATE_2           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_2           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_2            "0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x20, 0x42, 0x61, 0x72, 0x0"
#define GFX_WINDOW_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_2          gfxScheme1
		
#define GFX_WINDOW_LEFT_3            1
#define GFX_WINDOW_TOP_3             1
#define GFX_WINDOW_RIGHT_3           479
#define GFX_WINDOW_BOTTOM_3          271
#define GFX_WINDOW_STATE_3           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_3           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_3            "0x54, 0x65, 0x78, 0x74, 0x20, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x0"
#define GFX_WINDOW_ALIGNMENT_3       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_3          gfxScheme1
		
#define GFX_WINDOW_LEFT_4            1
#define GFX_WINDOW_TOP_4             1
#define GFX_WINDOW_RIGHT_4           479
#define GFX_WINDOW_BOTTOM_4          271
#define GFX_WINDOW_STATE_4           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_4           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_4            "0x4c, 0x69, 0x73, 0x74, 0x20, 0x42, 0x6f, 0x78, 0x0"
#define GFX_WINDOW_ALIGNMENT_4       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_4          gfxScheme1
		
#define GFX_WINDOW_LEFT_5            1
#define GFX_WINDOW_TOP_5             2
#define GFX_WINDOW_RIGHT_5           481
#define GFX_WINDOW_BOTTOM_5          271
#define GFX_WINDOW_STATE_5           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_5           (GFX_RESOURCE_HDR*)&mchpIcon0
#define GFX_WINDOW_TEXT_5            "0x4d, 0x65, 0x74, 0x65, 0x72, 0x0"
#define GFX_WINDOW_ALIGNMENT_5       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_5          gfxScheme1
		
/*** Window IDs ***/
#define Window6                  11000 
	
#define Window1                  11001 
	
#define Window2                  11002 
	
#define Window3                  11003 
	
#define Window4                  11004 
	
#define Window5                  11005 
	
/*** GFX GOL Progressbar Definitions ***/
#define GFX_PROGRESSBAR_LEFT_0            	141
#define GFX_PROGRESSBAR_TOP_0             	194
#define GFX_PROGRESSBAR_RIGHT_0           	441
#define GFX_PROGRESSBAR_BOTTOM_0          	219
#define GFX_PROGRESSBAR_STATE_0            GFX_GOL_PROGRESSBAR_DRAW_STATE
#define GFX_PROGRESSBAR_RANGE_0            100
#define GFX_PROGRESSBAR_POS_0              50
#define GFX_PROGRESSBAR_SCHEME_0           gfxScheme7
		
#define GFX_PROGRESSBAR_LEFT_1            	141
#define GFX_PROGRESSBAR_TOP_1             	129
#define GFX_PROGRESSBAR_RIGHT_1           	441
#define GFX_PROGRESSBAR_BOTTOM_1          	154
#define GFX_PROGRESSBAR_STATE_1            GFX_GOL_PROGRESSBAR_DRAW_STATE
#define GFX_PROGRESSBAR_RANGE_1            100
#define GFX_PROGRESSBAR_POS_1              10
#define GFX_PROGRESSBAR_SCHEME_1           gfxScheme7
		
#define GFX_PROGRESSBAR_LEFT_2            	141
#define GFX_PROGRESSBAR_TOP_2             	162
#define GFX_PROGRESSBAR_RIGHT_2           	441
#define GFX_PROGRESSBAR_BOTTOM_2          	187
#define GFX_PROGRESSBAR_STATE_2            GFX_GOL_PROGRESSBAR_DRAW_STATE
#define GFX_PROGRESSBAR_RANGE_2            100
#define GFX_PROGRESSBAR_POS_2              40
#define GFX_PROGRESSBAR_SCHEME_2           gfxScheme7
		
/*** Progressbar IDs ***/
#define ProgressBar3                  13000 
	
#define ProgressBar1                  13001 
	
#define ProgressBar2                  13002 
	
/*** GFX GOL Meter Definitions ***/
#define GFX_METER_LEFT_0            	290
#define GFX_METER_TOP_0             	43
#define GFX_METER_RIGHT_0           	466
#define GFX_METER_BOTTOM_0          	212
#define GFX_METER_STATE_0            GFX_GOL_METER_DRAW_STATE | GFX_GOL_METER_RING_STATE | GFX_GOL_METER_ACCURACY_STATE
#define GFX_METER_TYPE_0             GFX_GOL_METER_QUARTER_TYPE
#define GFX_METER_VALUE_0            0
#define GFX_METER_MIN_VALUE_0        0
#define GFX_METER_MAX_VALUE_0        300
#define GFX_METER_SCHEME_0           gfxScheme4

#define GFX_METER_COLOR1_RED_0       0x00
#define GFX_METER_COLOR1_GREEN_0     0xFC
#define GFX_METER_COLOR1_BLUE_0      0x00

#define GFX_METER_COLOR2_RED_0       0x00
#define GFX_METER_COLOR2_GREEN_0     0xFC
#define GFX_METER_COLOR2_BLUE_0      0x00

#define GFX_METER_COLOR3_RED_0       0x00
#define GFX_METER_COLOR3_GREEN_0     0xFC
#define GFX_METER_COLOR3_BLUE_0      0x00

#define GFX_METER_COLOR4_RED_0       0x00
#define GFX_METER_COLOR4_GREEN_0     0xFC
#define GFX_METER_COLOR4_BLUE_0      0x00

#define GFX_METER_COLOR5_RED_0       0xFF
#define GFX_METER_COLOR5_GREEN_0     0x00
#define GFX_METER_COLOR5_BLUE_0      0x00

#define GFX_METER_COLOR6_RED_0       0xFF
#define GFX_METER_COLOR6_GREEN_0     0x00
#define GFX_METER_COLOR6_BLUE_0      0x00
		
#define GFX_METER_LEFT_1            	8
#define GFX_METER_TOP_1             	41
#define GFX_METER_RIGHT_1           	184
#define GFX_METER_BOTTOM_1          	210
#define GFX_METER_STATE_1            GFX_GOL_METER_DRAW_STATE | GFX_GOL_METER_RING_STATE | GFX_GOL_METER_ACCURACY_STATE
#define GFX_METER_TYPE_1             GFX_GOL_METER_WHOLE_TYPE
#define GFX_METER_VALUE_1            0
#define GFX_METER_MIN_VALUE_1        0
#define GFX_METER_MAX_VALUE_1        300
#define GFX_METER_SCHEME_1           gfxScheme4

#define GFX_METER_COLOR1_RED_1       0x00
#define GFX_METER_COLOR1_GREEN_1     0xFC
#define GFX_METER_COLOR1_BLUE_1      0x00

#define GFX_METER_COLOR2_RED_1       0x00
#define GFX_METER_COLOR2_GREEN_1     0xFC
#define GFX_METER_COLOR2_BLUE_1      0x00

#define GFX_METER_COLOR3_RED_1       0x00
#define GFX_METER_COLOR3_GREEN_1     0xFC
#define GFX_METER_COLOR3_BLUE_1      0x00

#define GFX_METER_COLOR4_RED_1       0xFF
#define GFX_METER_COLOR4_GREEN_1     0xC8
#define GFX_METER_COLOR4_BLUE_1      0x00

#define GFX_METER_COLOR5_RED_1       0xFF
#define GFX_METER_COLOR5_GREEN_1     0x00
#define GFX_METER_COLOR5_BLUE_1      0x00

#define GFX_METER_COLOR6_RED_1       0xFF
#define GFX_METER_COLOR6_GREEN_1     0x00
#define GFX_METER_COLOR6_BLUE_1      0x00
		
/*** Meter IDs ***/
#define Meter2                  14000 
	
#define Meter1                  14001 
	



// *****************************************************************************
/* MPLAB Harmony Graphics Composer Objects

  Summary:
    Structure holding the graphics object handles

  Description:
    This structure contains the object handles for all graphics objects 
    generated by the Harmony Graphics Composer

  Remarks:
*/

typedef struct HGC_OBJECTS
{
    HGC_SCREEN_STATES screenState;      // current state of screen state machine
    HGC_SCREEN_STATES prevRefreshState; // previous state of screen state machine

    /*** Touch Event Callback ***/
    SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction;

    /*** GOL Objects References ***/
    GFX_GOL_BUTTON* pButton25Obj;
    GFX_GOL_BUTTON* pButton24Obj;
    GFX_GOL_BUTTON* pButton23Obj;
    GFX_GOL_BUTTON* pButton22Obj;
    GFX_GOL_BUTTON* pButton21Obj;
    GFX_GOL_BUTTON* pButton20Obj;
    GFX_GOL_BUTTON* pButton19Obj;
    GFX_GOL_BUTTON* pButton18Obj;
    GFX_GOL_BUTTON* pButton2Obj;
    GFX_GOL_BUTTON* pButton1Obj;
    GFX_GOL_BUTTON* pButton4Obj;
    GFX_GOL_BUTTON* pButton3Obj;
    GFX_GOL_BUTTON* pButton5Obj;
    GFX_GOL_BUTTON* pButton6Obj;
    GFX_GOL_BUTTON* pButton10Obj;
    GFX_GOL_BUTTON* pButton9Obj;
    GFX_GOL_BUTTON* pButton8Obj;
    GFX_GOL_BUTTON* pButton7Obj;
    GFX_GOL_BUTTON* pButton12Obj;
    GFX_GOL_BUTTON* pButton11Obj;
    GFX_GOL_DIGITALMETER* pDigitalMeter1Obj;
    GFX_GOL_CHECKBOX* pCheckBox1Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton10Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton12Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton11Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton9Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton8Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton7Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton3Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton2Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton1Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton6Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton5Obj;
    GFX_GOL_RADIOBUTTON* pRadioButton4Obj;
    GFX_GOL_SCROLLBAR* pSlider1Obj;
    GFX_GOL_EDITBOX* pEditBox3Obj;
    GFX_GOL_LISTITEM* pListBoxItem;
    GFX_GOL_LISTBOX* pListBox2Obj;
    GFX_GOL_GROUPBOX* pGroupBox5Obj;
    GFX_GOL_GROUPBOX* pGroupBox3Obj;
    GFX_GOL_GROUPBOX* pGroupBox4Obj;
    GFX_GOL_GROUPBOX* pGroupBox1Obj;
    GFX_GOL_GROUPBOX* pGroupBox2Obj;
    GFX_GOL_STATICTEXT* pStaticText3Obj;
    GFX_GOL_STATICTEXT* pStaticText2Obj;
    GFX_GOL_STATICTEXT* pStaticText1Obj;
    GFX_GOL_STATICTEXT* pStaticText6Obj;
    GFX_GOL_STATICTEXT* pStaticText5Obj;
    GFX_GOL_STATICTEXT* pStaticText4Obj;
    GFX_GOL_TEXTENTRY* pTextEntry2Obj;
    GFX_GOL_WINDOW* pWindow6Obj;
    GFX_GOL_WINDOW* pWindow1Obj;
    GFX_GOL_WINDOW* pWindow2Obj;
    GFX_GOL_WINDOW* pWindow3Obj;
    GFX_GOL_WINDOW* pWindow4Obj;
    GFX_GOL_WINDOW* pWindow5Obj;
    GFX_GOL_PROGRESSBAR* pProgressBar3Obj;
    GFX_GOL_PROGRESSBAR* pProgressBar1Obj;
    GFX_GOL_PROGRESSBAR* pProgressBar2Obj;
    GFX_GOL_METER* pMeter2Obj;
    GFX_GOL_METER* pMeter1Obj;
} HGC_OBJECTS;

extern HGC_OBJECTS hgcObj;

/******************************************************************************
  Function:
    void GFX_HGC_RegisterAppTouchCallback ( SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction )

  Summary:
    This function allows the application to register a callback to allow access 
    to the current touch behavior
 */
void GFX_HGC_RegisterAppTouchCallback ( SYS_MSG_RECEIVE_CALLBACK msgCallBackFunction );


/******************************************************************************
  Function:
    void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg )

  Summary:
    This function sets up the Message System Service to route touch callbacks
    to the GOL message system  
 */
void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg );


/******************************************************************************
  Function:
    void GFX_HGC_Initialize ( void )

  Summary:
    This function initializes the HGC state machine.  
 */
void GFX_HGC_Initialize ( void );


/******************************************************************************
  Function:
    void GFX_HGC_Setup ( void )

  Summary:
    This function sets up the GOL message callback and draw callbacks.  
 */
void GFX_HGC_Setup ( void );


/******************************************************************************
  Function:
    HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void )

  Remarks:
    This function returns the screen state
 */
HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void );


/******************************************************************************
  Function:
    void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState )

  Remarks:
    This function sets the screen state machine to a new state
 */
void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState );


/******************************************************************************
  Function:
    void GFX_HGC_Tasks (SYS_MODULE_OBJ gfxObject);

  Summary:
    This function is called in SYS_Tasks.  The intent wait until the GFX library
    is initialized before supplying items to draw
*/
void GFX_HGC_Tasks  (SYS_MODULE_OBJ gfxObject);


/******************************************************************************
  Function:
    void GFX_HGC_SchemeCreate ( void )

  Summary:
    Allocates memory for a new scheme
 */
GFX_GOL_OBJ_SCHEME *GFX_HGC_SchemeCreate(void);


/******************************************************************************
  Function:
    void GFX_HGC_InitializeSchemes ( void )

  Summary:
    Initializes all HGC-specified schemes
 */
void GFX_HGC_InitializeSchemes( void );


/******************************************************************************
  Function: 
    bool GFX_HGC_MESSAGECallback(uint16_t objMsg, GFX_GOL_OBJ_HEADER* pObj, GFX_GOL_MESSAGE* pMsg)

  Input: 
    objMsg - translated message for the object,
    pObj - pointer to the object,
    pMsg - pointer to the non-translated, raw GOL message

  Output: 
    If the function returns non-zero the message will be processed by default

  Remarks: 
    GFX_GOL_MESSAGECallback() function calls it each time the valid message for the GOL object is received.
 */
bool GFX_HGC_MessageCallback(GFX_GOL_TRANSLATED_ACTION objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawCallback( void )

  Output: 
    If the function returns non-zero the draw control will be passed to GOL

  Remarks: 
    GFX_GOL_Draw() function calls it each time when GOL objects drawing is 
    completed. HGC-specified draw data is grouped by screens states. It takes 
    two states to complete the drawing of each screen.  GFX GOL objects are drawn
    first and then GFX Primitives are drawn next to ensure primitives are not
    covered by GOL objects.
 */
bool GFX_HGC_DrawCallback( void );
/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_GOL( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX GOL objects are drawn here, grouped by screen.
    The draw order is reverse Z-ordered.
 */
bool GFX_HGC_DrawScreen_GOL(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_Primitives( uint8_t  screenId )

  Output:
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX Primitives are drawn here, grouped by screen.
    GFX Primitives are drawn after GFX GOL Objects to make sure GFX GOL Objects
    do not cover GFX Primitives
 */
bool GFX_HGC_DrawScreen_Primitives(uint8_t screenId);


/******************************************************************************
  Function: 
    void GFX_HGC_SetupScreen( uint8_t  screenId )

  Remarks: 
    Clears current screen and starts a fresh screen with its background color
 */
void GFX_HGC_SetupScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_HasCurrentScreenDrawn( void )

  Output: 
    Returns true if the current screen is completely drawn

  Remarks: 
    Allows application to know if the current screen is finished drawing
 */
bool GFX_HGC_HasCurrentScreenDrawn( void );


/******************************************************************************
  Function: 
    bool GFX_HGC_ChangeScreen( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    Can be called to initiate GFX Library to draw a new screen
 */
bool GFX_HGC_ChangeScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawItem(int itemId)

  Output:
    Returns true if a itemId matches an existing item identifier

  Remarks: 
    Every item specified in every screen in HGC is listed in this function
 */
bool GFX_HGC_DrawItem(int itemId);


/******************************************************************************
  Function: 
    bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Button events
 */
bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgDigitalMeters(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Digital Meter events
 */
bool GFX_HGC_MsgDigitalMeters(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgCheckBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Check Boxes events
 */
bool GFX_HGC_MsgCheckBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgRadioButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Radio Button events
 */
bool GFX_HGC_MsgRadioButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgScrollBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Scroll Bar events
 */
bool GFX_HGC_MsgScrollBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgEditBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Edit Boxes events
 */
bool GFX_HGC_MsgEditBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgListBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL List Boxes events
 */
bool GFX_HGC_MsgListBoxes(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Static Text events
 */
bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Window events
 */
bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgProgressBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Progress Bar events
 */
bool GFX_HGC_MsgProgressBars(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgTextEntrys(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Text Entry events
 */
bool GFX_HGC_MsgTextEntrys(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);


//DOM-IGNORE-BEGIN
#ifdef __cplusplus
}
#endif
//DOM-IGNORE-END

#endif // _GFX_HGC_DEFINITIONS_H
/*******************************************************************************
 End of File
*/
