/*******************************************************************************
  MPLAB Harmony Graphics Composer Generated Definitions Header

  File Name:
    gfx_hgc_definitions.h

  Summary:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

  Description:
    Build-time generated definitions header based on output by the MPLAB Harmony
    Graphics Composer.

    Created with MPLAB Harmony Version 1.05
*******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
Copyright (c) 2013-2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*******************************************************************************/
// DOM-IGNORE-END


#ifndef _GFX_HGC_DEFINITIONS_H
#define _GFX_HGC_DEFINITIONS_H

#include "system_config.h"
#include "system_definitions.h"

typedef enum
{
    HGC_STATE_INIT = 0,
    HGC_STATE_RUNNING
} HGC_STATES;

typedef enum
{
    HGC_SCREEN_STATE_INIT = 0,
    HGC_SCREEN_STATE_SETUP_SCREEN_MainScreen,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_MainScreen,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_MainScreen,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_MainScreen,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_MainScreen,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_MainScreen,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_MainScreen,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_MainScreen,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Comfort,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Comfort,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Comfort,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Comfort,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Comfort,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Comfort,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Comfort,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Comfort,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Gradients,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Gradients,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Gradients,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Gradients,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Gradients,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Gradients,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Gradients,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Gradients,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_AlphaBlend,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_AlphaBlend,
	
    HGC_SCREEN_STATE_SETUP_SCREEN_Info,
    HGC_SCREEN_STATE_PRE_DRAW_GOL_SCREEN_Info,
    HGC_SCREEN_STATE_DRAW_GOL_SCREEN_Info,
    HGC_SCREEN_STATE_POST_DRAW_GOL_SCREEN_Info,
    HGC_SCREEN_STATE_PRE_DRAW_PRIMITIVE_SCREEN_Info,
    HGC_SCREEN_STATE_DRAW_PRIMITIVE_SCREEN_Info,
    HGC_SCREEN_STATE_POST_DRAW_PRIMITIVE_SCREEN_Info,
    HGC_SCREEN_STATE_DISPLAY_SCREEN_Info,
	
} HGC_SCREEN_STATES;

/*** GFX GOL Scheme Definitions ***/

#define GFX_SCHEME_NAME_0                       "TextboxScheme2"
#define GFX_SCHEME_ALPHA_0                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_0      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_0     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_0          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_0        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_0         0xB8

#define GFX_SCHEME_SECONDARY_COLOR_RED_0        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_0      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_0       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_0         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_0       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_0        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_0       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_0     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_0      0xB8

#define GFX_SCHEME_EMBOSS_SIZE_0                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_0     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_0   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_0    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_0      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_0    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_0     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_0     0xF8
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_0   0x80
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_0    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_0   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_0 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_0  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_0    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_0  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_0   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_0    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_0  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_0   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_0    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_0  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_0   0xFF

#define GFX_SCHEME_FILL_STYLE_0                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_0           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_1                       "TextScheme3"
#define GFX_SCHEME_ALPHA_1                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_1      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_1     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_1          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_1        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_1         0xB8

#define GFX_SCHEME_SECONDARY_COLOR_RED_1        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_1      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_1       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_1         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_1       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_1        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_1       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_1     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_1      0xB8

#define GFX_SCHEME_EMBOSS_SIZE_1                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_1     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_1   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_1    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_1      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_1    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_1     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_1     0xF8
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_1   0x80
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_1    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_1   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_1 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_1  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_1    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_1  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_1   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_1    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_1  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_1   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_1    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_1  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_1   0xFF

#define GFX_SCHEME_FILL_STYLE_1                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_1           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_2                       "AlphaScheme"
#define GFX_SCHEME_ALPHA_2                      60

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_2      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_2     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_2          0xC0
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_2        0xEC
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_2         0xF0

#define GFX_SCHEME_SECONDARY_COLOR_RED_2        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_2      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_2       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_2         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_2       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_2        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_2       0xC0
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_2     0xEC
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_2      0xF8

#define GFX_SCHEME_EMBOSS_SIZE_2                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_2     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_2   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_2    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_2      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_2    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_2     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_2     0x78
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_2   0x7C
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_2    0x78

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_2   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_2 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_2  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_2    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_2  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_2   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_2    0xC8
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_2  0xF0
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_2   0xF8

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_2    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_2  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_2   0xFF

#define GFX_SCHEME_FILL_STYLE_2                GFX_FILL_STYLE_GRADIENT_DOWN
#define GFX_SCHEME_BACKGROUND_TYPE_2           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_3                       "default"
#define GFX_SCHEME_ALPHA_3                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_3      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_3     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_3          0xFF
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_3        0xFF
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_3         0xFF

#define GFX_SCHEME_SECONDARY_COLOR_RED_3        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_3      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_3       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_3         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_3       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_3        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_3       0xF8
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_3     0xFC
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_3      0xF8

#define GFX_SCHEME_EMBOSS_SIZE_3                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_3     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_3   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_3    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_3      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_3    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_3     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_3     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_3   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_3    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_3   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_3 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_3  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_3    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_3  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_3   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_3    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_3  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_3   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_3    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_3  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_3   0xFF

#define GFX_SCHEME_FILL_STYLE_3                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_3           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_4                       "TextboxScheme"
#define GFX_SCHEME_ALPHA_4                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_4      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_4     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_4          0x80
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_4        0x80
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_4         0xF8

#define GFX_SCHEME_SECONDARY_COLOR_RED_4        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_4      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_4       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_4         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_4       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_4        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_4       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_4     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_4      0xB8

#define GFX_SCHEME_EMBOSS_SIZE_4                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_4     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_4   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_4    0xC0

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_4      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_4    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_4     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_4     0xF8
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_4   0x80
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_4    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_4   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_4 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_4  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_4    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_4  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_4   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_4    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_4  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_4   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_4    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_4  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_4   0xFF

#define GFX_SCHEME_FILL_STYLE_4                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_4           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_5                       "GroupScheme"
#define GFX_SCHEME_ALPHA_5                      50

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_5      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_5     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_5          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_5        0x00
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_5         0xB8

#define GFX_SCHEME_SECONDARY_COLOR_RED_5        0x40
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_5      0x40
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_5       0x40

#define GFX_SCHEME_DISABLED_COLOR_RED_5         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_5       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_5        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_5       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_5     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_5      0xB8

#define GFX_SCHEME_EMBOSS_SIZE_5                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_5     0x80
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_5   0x80
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_5    0xF8

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_5      0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_5    0x40
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_5     0x40

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_5     0xF8
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_5   0x80
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_5    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_5   0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_5 0xFF
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_5  0xFF

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_5    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_5  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_5   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_5    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_5  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_5   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_5    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_5  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_5   0xFF

#define GFX_SCHEME_FILL_STYLE_5                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_5           GFX_BACKGROUND_NONE

		

#define GFX_SCHEME_NAME_6                       "ButtonScheme"
#define GFX_SCHEME_ALPHA_6                      100

#define GFX_SCHEME_BACKGROUND_OFFSET_TOP_6      0
#define GFX_SCHEME_BACKGROUND_OFFSET_LEFT_6     0

#define GFX_SCHEME_PRIMARY_COLOR_RED_6          0x00
#define GFX_SCHEME_PRIMARY_COLOR_GREEN_6        0x78
#define GFX_SCHEME_PRIMARY_COLOR_BLUE_6         0xE0

#define GFX_SCHEME_SECONDARY_COLOR_RED_6        0xD8
#define GFX_SCHEME_SECONDARY_COLOR_GREEN_6      0xDC
#define GFX_SCHEME_SECONDARY_COLOR_BLUE_6       0xD8

#define GFX_SCHEME_DISABLED_COLOR_RED_6         0xC0
#define GFX_SCHEME_DISABLED_COLOR_GREEN_6       0xC0
#define GFX_SCHEME_DISABLED_COLOR_BLUE_6        0xC0

#define GFX_SCHEME_BACKGROUND_COLOR_RED_6       0x00
#define GFX_SCHEME_BACKGROUND_COLOR_GREEN_6     0x00
#define GFX_SCHEME_BACKGROUND_COLOR_BLUE_6      0x00

#define GFX_SCHEME_EMBOSS_SIZE_6                3

#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_RED_6     0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_GREEN_6   0xC0
#define GFX_SCHEME_EMBOSS_LIGHT_COLOR_BLUE_6    0xF8

#define GFX_SCHEME_EMBOSS_DARK_COLOR_RED_6      0x00
#define GFX_SCHEME_EMBOSS_DARK_COLOR_GREEN_6    0x00
#define GFX_SCHEME_EMBOSS_DARK_COLOR_BLUE_6     0xB8

#define GFX_SCHEME_TEXT_PRIMARY_COLOR_RED_6     0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_GREEN_6   0x00
#define GFX_SCHEME_TEXT_PRIMARY_COLOR_BLUE_6    0x00

#define GFX_SCHEME_TEXT_SECONDARY_COLOR_RED_6   0xB8
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_GREEN_6 0xBC
#define GFX_SCHEME_TEXT_SECONDARY_COLOR_BLUE_6  0xB8

#define GFX_SCHEME_TEXT_DISABLED_COLOR_RED_6    0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_GREEN_6  0x40
#define GFX_SCHEME_TEXT_DISABLED_COLOR_BLUE_6   0x40

#define GFX_SCHEME_GRADIENT_START_COLOR_RED_6    0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_GREEN_6  0x00
#define GFX_SCHEME_GRADIENT_START_COLOR_BLUE_6   0x00

#define GFX_SCHEME_GRADIENT_END_COLOR_RED_6    0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_GREEN_6  0xFF
#define GFX_SCHEME_GRADIENT_END_COLOR_BLUE_6   0xFF

#define GFX_SCHEME_FILL_STYLE_6                GFX_FILL_STYLE_COLOR
#define GFX_SCHEME_BACKGROUND_TYPE_6           GFX_BACKGROUND_NONE

		
/*** GFX GOL Button Definitions ***/
#define GFX_BUTTON_LEFT_0            5
#define GFX_BUTTON_TOP_0             365
#define GFX_BUTTON_RIGHT_0           159
#define GFX_BUTTON_BOTTOM_0          422
#define GFX_BUTTON_TEXT_0            "0x49, 0x6e, 0x66, 0x6f, 0x0"
#define GFX_BUTTON_ALIGNMENT_0       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_0          15
#define GFX_BUTTON_STATE_0           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_0     NULL
#define GFX_BUTTON_RELEASE_IMAGE_0   NULL
#define GFX_BUTTON_SCHEME_0          gfxScheme6
		
#define GFX_BUTTON_LEFT_1            5
#define GFX_BUTTON_TOP_1             309
#define GFX_BUTTON_RIGHT_1           159
#define GFX_BUTTON_BOTTOM_1          366
#define GFX_BUTTON_TEXT_1            "0x41, 0x6c, 0x70, 0x68, 0x61, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x0"
#define GFX_BUTTON_ALIGNMENT_1       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_1          15
#define GFX_BUTTON_STATE_1           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_1     NULL
#define GFX_BUTTON_RELEASE_IMAGE_1   NULL
#define GFX_BUTTON_SCHEME_1          gfxScheme6
		
#define GFX_BUTTON_LEFT_2            5
#define GFX_BUTTON_TOP_2             253
#define GFX_BUTTON_RIGHT_2           159
#define GFX_BUTTON_BOTTOM_2          310
#define GFX_BUTTON_TEXT_2            "0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x0"
#define GFX_BUTTON_ALIGNMENT_2       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_2          15
#define GFX_BUTTON_STATE_2           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_2     NULL
#define GFX_BUTTON_RELEASE_IMAGE_2   NULL
#define GFX_BUTTON_SCHEME_2          gfxScheme6
		
#define GFX_BUTTON_LEFT_3            5
#define GFX_BUTTON_TOP_3             197
#define GFX_BUTTON_RIGHT_3           159
#define GFX_BUTTON_BOTTOM_3          254
#define GFX_BUTTON_TEXT_3            "0x53, 0x70, 0x65, 0x65, 0x64, 0x0"
#define GFX_BUTTON_ALIGNMENT_3       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_3          15
#define GFX_BUTTON_STATE_3           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_3     NULL
#define GFX_BUTTON_RELEASE_IMAGE_3   NULL
#define GFX_BUTTON_SCHEME_3          gfxScheme6
		
#define GFX_BUTTON_LEFT_4            5
#define GFX_BUTTON_TOP_4             141
#define GFX_BUTTON_RIGHT_4           159
#define GFX_BUTTON_BOTTOM_4          198
#define GFX_BUTTON_TEXT_4            "0x43, 0x6f, 0x6d, 0x66, 0x6f, 0x72, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_4       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_4          15
#define GFX_BUTTON_STATE_4           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_4     NULL
#define GFX_BUTTON_RELEASE_IMAGE_4   NULL
#define GFX_BUTTON_SCHEME_4          gfxScheme6
		
#define GFX_BUTTON_LEFT_5            483
#define GFX_BUTTON_TOP_5             413
#define GFX_BUTTON_RIGHT_5           613
#define GFX_BUTTON_BOTTOM_5          463
#define GFX_BUTTON_TEXT_5            "0x41, 0x55, 0x54, 0x4f, 0x0"
#define GFX_BUTTON_ALIGNMENT_5       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_5          20
#define GFX_BUTTON_STATE_5           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_5     NULL
#define GFX_BUTTON_RELEASE_IMAGE_5   NULL
#define GFX_BUTTON_SCHEME_5          gfxScheme6
		
#define GFX_BUTTON_LEFT_6            483
#define GFX_BUTTON_TOP_6             361
#define GFX_BUTTON_RIGHT_6           613
#define GFX_BUTTON_BOTTOM_6          411
#define GFX_BUTTON_TEXT_6            "0x4f, 0x4e, 0x0"
#define GFX_BUTTON_ALIGNMENT_6       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_6          20
#define GFX_BUTTON_STATE_6           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_6     NULL
#define GFX_BUTTON_RELEASE_IMAGE_6   NULL
#define GFX_BUTTON_SCHEME_6          gfxScheme6
		
#define GFX_BUTTON_LEFT_7            320
#define GFX_BUTTON_TOP_7             413
#define GFX_BUTTON_RIGHT_7           450
#define GFX_BUTTON_BOTTOM_7          463
#define GFX_BUTTON_TEXT_7            "0x43, 0x4f, 0x4f, 0x4c, 0x0"
#define GFX_BUTTON_ALIGNMENT_7       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_7          20
#define GFX_BUTTON_STATE_7           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_7     NULL
#define GFX_BUTTON_RELEASE_IMAGE_7   NULL
#define GFX_BUTTON_SCHEME_7          gfxScheme6
		
#define GFX_BUTTON_LEFT_8            191
#define GFX_BUTTON_TOP_8             413
#define GFX_BUTTON_RIGHT_8           321
#define GFX_BUTTON_BOTTOM_8          463
#define GFX_BUTTON_TEXT_8            "0x48, 0x45, 0x41, 0x54, 0x0"
#define GFX_BUTTON_ALIGNMENT_8       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_8          20
#define GFX_BUTTON_STATE_8           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_8     NULL
#define GFX_BUTTON_RELEASE_IMAGE_8   NULL
#define GFX_BUTTON_SCHEME_8          gfxScheme6
		
#define GFX_BUTTON_LEFT_9            320
#define GFX_BUTTON_TOP_9             361
#define GFX_BUTTON_RIGHT_9           450
#define GFX_BUTTON_BOTTOM_9          411
#define GFX_BUTTON_TEXT_9            "0x4f, 0x46, 0x46, 0x0"
#define GFX_BUTTON_ALIGNMENT_9       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_9          20
#define GFX_BUTTON_STATE_9           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_9     NULL
#define GFX_BUTTON_RELEASE_IMAGE_9   NULL
#define GFX_BUTTON_SCHEME_9          gfxScheme6
		
#define GFX_BUTTON_LEFT_10            191
#define GFX_BUTTON_TOP_10             361
#define GFX_BUTTON_RIGHT_10           321
#define GFX_BUTTON_BOTTOM_10          411
#define GFX_BUTTON_TEXT_10            "0x41, 0x55, 0x54, 0x4f, 0x0"
#define GFX_BUTTON_ALIGNMENT_10       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_10          20
#define GFX_BUTTON_STATE_10           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_10     NULL
#define GFX_BUTTON_RELEASE_IMAGE_10   NULL
#define GFX_BUTTON_SCHEME_10          gfxScheme6
		
#define GFX_BUTTON_LEFT_11            558
#define GFX_BUTTON_TOP_11             257
#define GFX_BUTTON_RIGHT_11           613
#define GFX_BUTTON_BOTTOM_11          312
#define GFX_BUTTON_TEXT_11            "0x0"
#define GFX_BUTTON_ALIGNMENT_11       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_11          25
#define GFX_BUTTON_STATE_11           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_11     (GFX_RESOURCE_HDR*)&list_add
#define GFX_BUTTON_RELEASE_IMAGE_11   (GFX_RESOURCE_HDR*)&list_add
#define GFX_BUTTON_SCHEME_11          gfxScheme6
		
#define GFX_BUTTON_LEFT_12            431
#define GFX_BUTTON_TOP_12             257
#define GFX_BUTTON_RIGHT_12           486
#define GFX_BUTTON_BOTTOM_12          312
#define GFX_BUTTON_TEXT_12            "0x0"
#define GFX_BUTTON_ALIGNMENT_12       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_12          25
#define GFX_BUTTON_STATE_12           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_12     (GFX_RESOURCE_HDR*)&list_remove
#define GFX_BUTTON_RELEASE_IMAGE_12   (GFX_RESOURCE_HDR*)&list_remove
#define GFX_BUTTON_SCHEME_12          gfxScheme6
		
#define GFX_BUTTON_LEFT_13            558
#define GFX_BUTTON_TOP_13             177
#define GFX_BUTTON_RIGHT_13           613
#define GFX_BUTTON_BOTTOM_13          232
#define GFX_BUTTON_TEXT_13            "0x0"
#define GFX_BUTTON_ALIGNMENT_13       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_13          25
#define GFX_BUTTON_STATE_13           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_13     (GFX_RESOURCE_HDR*)&list_add
#define GFX_BUTTON_RELEASE_IMAGE_13   (GFX_RESOURCE_HDR*)&list_add
#define GFX_BUTTON_SCHEME_13          gfxScheme6
		
#define GFX_BUTTON_LEFT_14            431
#define GFX_BUTTON_TOP_14             177
#define GFX_BUTTON_RIGHT_14           486
#define GFX_BUTTON_BOTTOM_14          232
#define GFX_BUTTON_TEXT_14            "0x0"
#define GFX_BUTTON_ALIGNMENT_14       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_14          25
#define GFX_BUTTON_STATE_14           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_14     (GFX_RESOURCE_HDR*)&list_remove
#define GFX_BUTTON_RELEASE_IMAGE_14   (GFX_RESOURCE_HDR*)&list_remove
#define GFX_BUTTON_SCHEME_14          gfxScheme6
		
#define GFX_BUTTON_LEFT_15            191
#define GFX_BUTTON_TOP_15             98
#define GFX_BUTTON_RIGHT_15           301
#define GFX_BUTTON_BOTTOM_15          142
#define GFX_BUTTON_TEXT_15            "0x3c, 0x3c, 0x3c, 0x3c, 0x0"
#define GFX_BUTTON_ALIGNMENT_15       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_15          15
#define GFX_BUTTON_STATE_15           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_15     NULL
#define GFX_BUTTON_RELEASE_IMAGE_15   NULL
#define GFX_BUTTON_SCHEME_15          gfxScheme6
		
#define GFX_BUTTON_LEFT_16            502
#define GFX_BUTTON_TOP_16             98
#define GFX_BUTTON_RIGHT_16           612
#define GFX_BUTTON_BOTTOM_16          141
#define GFX_BUTTON_TEXT_16            "0x3e, 0x3e, 0x3e, 0x3e, 0x0"
#define GFX_BUTTON_ALIGNMENT_16       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_16          15
#define GFX_BUTTON_STATE_16           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_16     NULL
#define GFX_BUTTON_RELEASE_IMAGE_16   NULL
#define GFX_BUTTON_SCHEME_16          gfxScheme6
		
#define GFX_BUTTON_LEFT_17            5
#define GFX_BUTTON_TOP_17             141
#define GFX_BUTTON_RIGHT_17           159
#define GFX_BUTTON_BOTTOM_17          198
#define GFX_BUTTON_TEXT_17            "0x4d, 0x61, 0x69, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_17       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_17          15
#define GFX_BUTTON_STATE_17           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_17     NULL
#define GFX_BUTTON_RELEASE_IMAGE_17   NULL
#define GFX_BUTTON_SCHEME_17          gfxScheme6
		
#define GFX_BUTTON_LEFT_18            5
#define GFX_BUTTON_TOP_18             197
#define GFX_BUTTON_RIGHT_18           159
#define GFX_BUTTON_BOTTOM_18          254
#define GFX_BUTTON_TEXT_18            "0x53, 0x70, 0x65, 0x65, 0x64, 0x0"
#define GFX_BUTTON_ALIGNMENT_18       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_18          15
#define GFX_BUTTON_STATE_18           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_18     NULL
#define GFX_BUTTON_RELEASE_IMAGE_18   NULL
#define GFX_BUTTON_SCHEME_18          gfxScheme6
		
#define GFX_BUTTON_LEFT_19            5
#define GFX_BUTTON_TOP_19             253
#define GFX_BUTTON_RIGHT_19           159
#define GFX_BUTTON_BOTTOM_19          310
#define GFX_BUTTON_TEXT_19            "0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x0"
#define GFX_BUTTON_ALIGNMENT_19       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_19          15
#define GFX_BUTTON_STATE_19           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_19     NULL
#define GFX_BUTTON_RELEASE_IMAGE_19   NULL
#define GFX_BUTTON_SCHEME_19          gfxScheme6
		
#define GFX_BUTTON_LEFT_20            5
#define GFX_BUTTON_TOP_20             309
#define GFX_BUTTON_RIGHT_20           159
#define GFX_BUTTON_BOTTOM_20          366
#define GFX_BUTTON_TEXT_20            "0x41, 0x6c, 0x70, 0x68, 0x61, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x0"
#define GFX_BUTTON_ALIGNMENT_20       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_20          15
#define GFX_BUTTON_STATE_20           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_20     NULL
#define GFX_BUTTON_RELEASE_IMAGE_20   NULL
#define GFX_BUTTON_SCHEME_20          gfxScheme6
		
#define GFX_BUTTON_LEFT_21            5
#define GFX_BUTTON_TOP_21             365
#define GFX_BUTTON_RIGHT_21           159
#define GFX_BUTTON_BOTTOM_21          422
#define GFX_BUTTON_TEXT_21            "0x49, 0x6e, 0x66, 0x6f, 0x0"
#define GFX_BUTTON_ALIGNMENT_21       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_21          15
#define GFX_BUTTON_STATE_21           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_21     NULL
#define GFX_BUTTON_RELEASE_IMAGE_21   NULL
#define GFX_BUTTON_SCHEME_21          gfxScheme6
		
#define GFX_BUTTON_LEFT_22            5
#define GFX_BUTTON_TOP_22             141
#define GFX_BUTTON_RIGHT_22           159
#define GFX_BUTTON_BOTTOM_22          198
#define GFX_BUTTON_TEXT_22            "0x43, 0x6f, 0x6d, 0x66, 0x6f, 0x72, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_22       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_22          15
#define GFX_BUTTON_STATE_22           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_22     NULL
#define GFX_BUTTON_RELEASE_IMAGE_22   NULL
#define GFX_BUTTON_SCHEME_22          gfxScheme6
		
#define GFX_BUTTON_LEFT_23            5
#define GFX_BUTTON_TOP_23             197
#define GFX_BUTTON_RIGHT_23           159
#define GFX_BUTTON_BOTTOM_23          254
#define GFX_BUTTON_TEXT_23            "0x53, 0x70, 0x65, 0x65, 0x64, 0x0"
#define GFX_BUTTON_ALIGNMENT_23       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_23          15
#define GFX_BUTTON_STATE_23           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_23     NULL
#define GFX_BUTTON_RELEASE_IMAGE_23   NULL
#define GFX_BUTTON_SCHEME_23          gfxScheme6
		
#define GFX_BUTTON_LEFT_24            5
#define GFX_BUTTON_TOP_24             253
#define GFX_BUTTON_RIGHT_24           159
#define GFX_BUTTON_BOTTOM_24          310
#define GFX_BUTTON_TEXT_24            "0x4d, 0x61, 0x69, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_24       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_24          15
#define GFX_BUTTON_STATE_24           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_24     NULL
#define GFX_BUTTON_RELEASE_IMAGE_24   NULL
#define GFX_BUTTON_SCHEME_24          gfxScheme6
		
#define GFX_BUTTON_LEFT_25            5
#define GFX_BUTTON_TOP_25             309
#define GFX_BUTTON_RIGHT_25           159
#define GFX_BUTTON_BOTTOM_25          366
#define GFX_BUTTON_TEXT_25            "0x41, 0x6c, 0x70, 0x68, 0x61, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x0"
#define GFX_BUTTON_ALIGNMENT_25       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_25          15
#define GFX_BUTTON_STATE_25           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_25     NULL
#define GFX_BUTTON_RELEASE_IMAGE_25   NULL
#define GFX_BUTTON_SCHEME_25          gfxScheme6
		
#define GFX_BUTTON_LEFT_26            5
#define GFX_BUTTON_TOP_26             365
#define GFX_BUTTON_RIGHT_26           159
#define GFX_BUTTON_BOTTOM_26          422
#define GFX_BUTTON_TEXT_26            "0x49, 0x6e, 0x66, 0x6f, 0x0"
#define GFX_BUTTON_ALIGNMENT_26       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_26          15
#define GFX_BUTTON_STATE_26           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_26     NULL
#define GFX_BUTTON_RELEASE_IMAGE_26   NULL
#define GFX_BUTTON_SCHEME_26          gfxScheme6
		
#define GFX_BUTTON_LEFT_27            5
#define GFX_BUTTON_TOP_27             141
#define GFX_BUTTON_RIGHT_27           159
#define GFX_BUTTON_BOTTOM_27          198
#define GFX_BUTTON_TEXT_27            "0x43, 0x6f, 0x6d, 0x66, 0x6f, 0x72, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_27       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_27          15
#define GFX_BUTTON_STATE_27           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_27     NULL
#define GFX_BUTTON_RELEASE_IMAGE_27   NULL
#define GFX_BUTTON_SCHEME_27          gfxScheme6
		
#define GFX_BUTTON_LEFT_28            5
#define GFX_BUTTON_TOP_28             197
#define GFX_BUTTON_RIGHT_28           159
#define GFX_BUTTON_BOTTOM_28          254
#define GFX_BUTTON_TEXT_28            "0x53, 0x70, 0x65, 0x65, 0x64, 0x0"
#define GFX_BUTTON_ALIGNMENT_28       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_28          15
#define GFX_BUTTON_STATE_28           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_28     NULL
#define GFX_BUTTON_RELEASE_IMAGE_28   NULL
#define GFX_BUTTON_SCHEME_28          gfxScheme6
		
#define GFX_BUTTON_LEFT_29            5
#define GFX_BUTTON_TOP_29             253
#define GFX_BUTTON_RIGHT_29           159
#define GFX_BUTTON_BOTTOM_29          310
#define GFX_BUTTON_TEXT_29            "0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x0"
#define GFX_BUTTON_ALIGNMENT_29       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_29          15
#define GFX_BUTTON_STATE_29           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_29     NULL
#define GFX_BUTTON_RELEASE_IMAGE_29   NULL
#define GFX_BUTTON_SCHEME_29          gfxScheme6
		
#define GFX_BUTTON_LEFT_30            5
#define GFX_BUTTON_TOP_30             309
#define GFX_BUTTON_RIGHT_30           159
#define GFX_BUTTON_BOTTOM_30          366
#define GFX_BUTTON_TEXT_30            "0x4d, 0x61, 0x69, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_30       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_30          15
#define GFX_BUTTON_STATE_30           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_30     NULL
#define GFX_BUTTON_RELEASE_IMAGE_30   NULL
#define GFX_BUTTON_SCHEME_30          gfxScheme6
		
#define GFX_BUTTON_LEFT_31            5
#define GFX_BUTTON_TOP_31             365
#define GFX_BUTTON_RIGHT_31           159
#define GFX_BUTTON_BOTTOM_31          422
#define GFX_BUTTON_TEXT_31            "0x49, 0x6e, 0x66, 0x6f, 0x0"
#define GFX_BUTTON_ALIGNMENT_31       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_31          15
#define GFX_BUTTON_STATE_31           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_31     NULL
#define GFX_BUTTON_RELEASE_IMAGE_31   NULL
#define GFX_BUTTON_SCHEME_31          gfxScheme6
		
#define GFX_BUTTON_LEFT_32            5
#define GFX_BUTTON_TOP_32             141
#define GFX_BUTTON_RIGHT_32           159
#define GFX_BUTTON_BOTTOM_32          198
#define GFX_BUTTON_TEXT_32            "0x43, 0x6f, 0x6d, 0x66, 0x6f, 0x72, 0x74, 0x0"
#define GFX_BUTTON_ALIGNMENT_32       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_32          15
#define GFX_BUTTON_STATE_32           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_32     NULL
#define GFX_BUTTON_RELEASE_IMAGE_32   NULL
#define GFX_BUTTON_SCHEME_32          gfxScheme6
		
#define GFX_BUTTON_LEFT_33            5
#define GFX_BUTTON_TOP_33             197
#define GFX_BUTTON_RIGHT_33           159
#define GFX_BUTTON_BOTTOM_33          254
#define GFX_BUTTON_TEXT_33            "0x53, 0x70, 0x65, 0x65, 0x64, 0x0"
#define GFX_BUTTON_ALIGNMENT_33       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_33          15
#define GFX_BUTTON_STATE_33           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_33     NULL
#define GFX_BUTTON_RELEASE_IMAGE_33   NULL
#define GFX_BUTTON_SCHEME_33          gfxScheme6
		
#define GFX_BUTTON_LEFT_34            5
#define GFX_BUTTON_TOP_34             253
#define GFX_BUTTON_RIGHT_34           159
#define GFX_BUTTON_BOTTOM_34          310
#define GFX_BUTTON_TEXT_34            "0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x0"
#define GFX_BUTTON_ALIGNMENT_34       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_34          15
#define GFX_BUTTON_STATE_34           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_34     NULL
#define GFX_BUTTON_RELEASE_IMAGE_34   NULL
#define GFX_BUTTON_SCHEME_34          gfxScheme6
		
#define GFX_BUTTON_LEFT_35            5
#define GFX_BUTTON_TOP_35             309
#define GFX_BUTTON_RIGHT_35           159
#define GFX_BUTTON_BOTTOM_35          366
#define GFX_BUTTON_TEXT_35            "0x41, 0x6c, 0x70, 0x68, 0x61, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x0"
#define GFX_BUTTON_ALIGNMENT_35       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_35          15
#define GFX_BUTTON_STATE_35           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_35     NULL
#define GFX_BUTTON_RELEASE_IMAGE_35   NULL
#define GFX_BUTTON_SCHEME_35          gfxScheme6
		
#define GFX_BUTTON_LEFT_36            5
#define GFX_BUTTON_TOP_36             365
#define GFX_BUTTON_RIGHT_36           159
#define GFX_BUTTON_BOTTOM_36          422
#define GFX_BUTTON_TEXT_36            "0x4d, 0x61, 0x69, 0x6e, 0x0"
#define GFX_BUTTON_ALIGNMENT_36       GFX_ALIGN_HCENTER | GFX_ALIGN_VCENTER
#define GFX_BUTTON_RADIUS_36          15
#define GFX_BUTTON_STATE_36           GFX_GOL_BUTTON_DRAW_STATE
#define GFX_BUTTON_PRESS_IMAGE_36     NULL
#define GFX_BUTTON_RELEASE_IMAGE_36   NULL
#define GFX_BUTTON_SCHEME_36          gfxScheme6
		
/*** Button IDs ***/
#define Button6                  100 
	
#define Button5                  101 
	
#define Button4                  102 
	
#define Button3                  103 
	
#define Button1                  104 
	
#define Button22                  105 
	
#define Button21                  106 
	
#define Button18                  107 
	
#define Button20                  108 
	
#define Button19                  109 
	
#define Button17                  110 
	
#define Button16                  111 
	
#define Button15                  112 
	
#define Button14                  113 
	
#define Button13                  114 
	
#define Button12                  115 
	
#define Button2                  116 
	
#define Button11                  117 
	
#define Button10                  118 
	
#define Button9                  119 
	
#define Button8                  120 
	
#define Button7                  121 
	
#define Button30                  122 
	
#define Button29                  123 
	
#define Button28                  124 
	
#define Button27                  125 
	
#define Button26                  126 
	
#define Button35                  127 
	
#define Button34                  128 
	
#define Button33                  129 
	
#define Button32                  130 
	
#define Button31                  131 
	
#define Button40                  132 
	
#define Button39                  133 
	
#define Button38                  134 
	
#define Button37                  135 
	
#define Button36                  136 
	
/*** GFX GOL Group box Definitions ***/
#define GFX_GROUPBOX_LEFT_0            482
#define GFX_GROUPBOX_TOP_0             335
#define GFX_GROUPBOX_RIGHT_0           612
#define GFX_GROUPBOX_BOTTOM_0          465
#define GFX_GROUPBOX_STATE_0           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_0          gfxScheme5
#define GFX_GROUPBOX_ALIGNMENT_0       GFX_ALIGN_HCENTER

		
#define GFX_GROUPBOX_LEFT_1            191
#define GFX_GROUPBOX_TOP_1             335
#define GFX_GROUPBOX_RIGHT_1           451
#define GFX_GROUPBOX_BOTTOM_1          465
#define GFX_GROUPBOX_STATE_1           GFX_GOL_GROUPBOX_DRAW_STATE
#define GFX_GROUPBOX_SCHEME_1          gfxScheme5
#define GFX_GROUPBOX_ALIGNMENT_1       GFX_ALIGN_HCENTER

		
/*** Group Box IDs ***/
#define GroupBox2                  7000 
#define GroupBox1                  7001 
/*** GFX GOL Button Definitions ***/
#define GFX_STATICTEXT_LEFT_0            252
#define GFX_STATICTEXT_TOP_0             229
#define GFX_STATICTEXT_RIGHT_0           322
#define GFX_STATICTEXT_BOTTOM_0          299
#define GFX_STATICTEXT_STATE_0          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_FRAME_STATE
#define GFX_STATICTEXT_TEXT_0            "0x37, 0x32, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_0          gfxScheme1
		
#define GFX_STATICTEXT_LEFT_1            505
#define GFX_STATICTEXT_TOP_1             273
#define GFX_STATICTEXT_RIGHT_1           543
#define GFX_STATICTEXT_BOTTOM_1          311
#define GFX_STATICTEXT_STATE_1          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_FRAME_STATE
#define GFX_STATICTEXT_TEXT_1            "0x37, 0x38, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_1       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_1          gfxScheme0
		
#define GFX_STATICTEXT_LEFT_2            504
#define GFX_STATICTEXT_TOP_2             189
#define GFX_STATICTEXT_RIGHT_2           542
#define GFX_STATICTEXT_BOTTOM_2          227
#define GFX_STATICTEXT_STATE_2          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_FRAME_STATE
#define GFX_STATICTEXT_TEXT_2            "0x37, 0x32, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_2       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_2          gfxScheme0
		
#define GFX_STATICTEXT_LEFT_3            348
#define GFX_STATICTEXT_TOP_3             108
#define GFX_STATICTEXT_RIGHT_3           451
#define GFX_STATICTEXT_BOTTOM_3          131
#define GFX_STATICTEXT_STATE_3          GFX_GOL_STATICTEXT_DRAW_STATE | GFX_GOL_STATICTEXT_FRAME_STATE
#define GFX_STATICTEXT_TEXT_3            "0x55, 0x70, 0x73, 0x74, 0x61, 0x69, 0x72, 0x73, 0x0"
#define GFX_STATICTEXT_ALIGNMENT_3       GFX_ALIGN_LEFT | GFX_ALIGN_TOP
#define GFX_STATICTEXT_SCHEME_3          gfxScheme4
		
/*** static text IDs ***/
#define StaticText2                  700 
	
#define StaticText4                  701 
	
#define StaticText3                  702 
	
#define StaticText1                  703 
	
/*** GFX GOL windows Definitions ***/
#define GFX_WINDOW_LEFT_0            175
#define GFX_WINDOW_TOP_0             107
#define GFX_WINDOW_RIGHT_0           632
#define GFX_WINDOW_BOTTOM_0          413
#define GFX_WINDOW_STATE_0           GFX_GOL_WINDOW_DRAW_STATE
#define GFX_WINDOW_IMAGE_0           NULL
#define GFX_WINDOW_TEXT_0            "0x44, 0x65, 0x6d, 0x6f, 0x20, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x0"
#define GFX_WINDOW_ALIGNMENT_0       GFX_ALIGN_LEFT | GFX_ALIGN_VCENTER
#define GFX_WINDOW_SCHEME_0          gfxScheme2
		
/*** Window IDs ***/
#define Window1                  975 
	
/*** GFX GOL windows Definitions ***/
#define GFX_PICTURE_LEFT_0            161
#define GFX_PICTURE_TOP_0             150
#define GFX_PICTURE_RIGHT_0           634
#define GFX_PICTURE_BOTTOM_0          422
#define GFX_PICTURE_STATE_0          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_0       1
#define GFX_PICTURE_SCHEME_0          gfxScheme3
		
#define GFX_PICTURE_LEFT_1            174
#define GFX_PICTURE_TOP_1             80
#define GFX_PICTURE_RIGHT_1           628
#define GFX_PICTURE_BOTTOM_1          480
#define GFX_PICTURE_STATE_1          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_1       1
#define GFX_PICTURE_SCHEME_1          gfxScheme3
		
#define GFX_PICTURE_LEFT_2            161
#define GFX_PICTURE_TOP_2             150
#define GFX_PICTURE_RIGHT_2           634
#define GFX_PICTURE_BOTTOM_2          422
#define GFX_PICTURE_STATE_2          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_2       1
#define GFX_PICTURE_SCHEME_2          gfxScheme3
		
#define GFX_PICTURE_LEFT_3            161
#define GFX_PICTURE_TOP_3             150
#define GFX_PICTURE_RIGHT_3           634
#define GFX_PICTURE_BOTTOM_3          422
#define GFX_PICTURE_STATE_3          GFX_GOL_PICTURECONTROL_DRAW_STATE
#define GFX_PICTURE_SCALE_3       1
#define GFX_PICTURE_SCHEME_3          gfxScheme3
		
/*** Pictures IDs ***/
#define Picture2                  800 
	
#define Picture1                  801 
	
#define Picture3                  802 
	
#define Picture4                  803 
	
/*** Line IDs ***/
#define Line1                 950 
	
#define Line2                 951 
	
#define Line3                 952 
	
#define Line4                 953 
	
#define Line5                 954 
	
/*** Rectangle IDs ***/
#define Rectangle1                 1000 
	
#define Rectangle2                 1001 
	
#define Rectangle9                 1002 
	
#define Rectangle8                 1003 
	
#define Rectangle7                 1004 
	
#define Rectangle6                 1005 
	
#define Rectangle5                 1006 
	
#define Rectangle4                 1007 
	
#define Rectangle3                 1008 
	
#define Rectangle10                 1009 
	
#define Rectangle11                 1010 
	
/*** Image IDs ***/
#define Image2                 1100 
	
#define Image4                 1101 
	
#define Image3                 1102 
	
#define Image1                 1103 
	
#define Image5                 1104 
	
/*** Text IDs ***/
#define Text1                 1150 
	
#define Text5                 1151 
	
#define Text4                 1152 
	
#define Text3                 1153 
	
#define Text2                 1154 
	
#define Text6                 1155 
	
#define Text9                 1156 
	
#define Text7                 1157 
	
#define Text11                 1158 
	
#define Text8                 1159 
	
/*** Screen IDs ***/
#define MainScreen                 0 
	
#define Comfort                 1 
	
#define Gradients                 2 
	
#define AlphaBlend                 3 
	
#define Info                 4 
	


// *****************************************************************************
/* MPLAB Harmony Graphics Composer Objects

  Summary:
    Structure holding the graphics object handles

  Description:
    This structure contains the object handles for all graphics objects 
    generated by the Harmony Graphics Composer

  Remarks:
*/

typedef struct HGC_OBJECTS
{
    HGC_SCREEN_STATES screenState;      // current state of screen state machine
    HGC_SCREEN_STATES prevRefreshState; // previous state of screen state machine

    DRV_TOUCH_SAMPLE_POINTS samplePoints;

    /*** GOL Objects References ***/
    GFX_GOL_BUTTON* pButton6Obj;
    GFX_GOL_BUTTON* pButton5Obj;
    GFX_GOL_BUTTON* pButton4Obj;
    GFX_GOL_BUTTON* pButton3Obj;
    GFX_GOL_BUTTON* pButton1Obj;
    GFX_GOL_BUTTON* pButton22Obj;
    GFX_GOL_BUTTON* pButton21Obj;
    GFX_GOL_BUTTON* pButton18Obj;
    GFX_GOL_BUTTON* pButton20Obj;
    GFX_GOL_BUTTON* pButton19Obj;
    GFX_GOL_BUTTON* pButton17Obj;
    GFX_GOL_BUTTON* pButton16Obj;
    GFX_GOL_BUTTON* pButton15Obj;
    GFX_GOL_BUTTON* pButton14Obj;
    GFX_GOL_BUTTON* pButton13Obj;
    GFX_GOL_BUTTON* pButton12Obj;
    GFX_GOL_BUTTON* pButton2Obj;
    GFX_GOL_BUTTON* pButton11Obj;
    GFX_GOL_BUTTON* pButton10Obj;
    GFX_GOL_BUTTON* pButton9Obj;
    GFX_GOL_BUTTON* pButton8Obj;
    GFX_GOL_BUTTON* pButton7Obj;
    GFX_GOL_BUTTON* pButton30Obj;
    GFX_GOL_BUTTON* pButton29Obj;
    GFX_GOL_BUTTON* pButton28Obj;
    GFX_GOL_BUTTON* pButton27Obj;
    GFX_GOL_BUTTON* pButton26Obj;
    GFX_GOL_BUTTON* pButton35Obj;
    GFX_GOL_BUTTON* pButton34Obj;
    GFX_GOL_BUTTON* pButton33Obj;
    GFX_GOL_BUTTON* pButton32Obj;
    GFX_GOL_BUTTON* pButton31Obj;
    GFX_GOL_BUTTON* pButton40Obj;
    GFX_GOL_BUTTON* pButton39Obj;
    GFX_GOL_BUTTON* pButton38Obj;
    GFX_GOL_BUTTON* pButton37Obj;
    GFX_GOL_BUTTON* pButton36Obj;
    GFX_GOL_GROUPBOX* pGroupBox2Obj;
    GFX_GOL_GROUPBOX* pGroupBox1Obj;
    GFX_GOL_STATICTEXT* pStaticText2Obj;
    GFX_GOL_STATICTEXT* pStaticText4Obj;
    GFX_GOL_STATICTEXT* pStaticText3Obj;
    GFX_GOL_STATICTEXT* pStaticText1Obj;
    GFX_GOL_WINDOW* pWindow1Obj;
    GFX_GOL_PICTURECONTROL* pPicture2Obj;
    GFX_GOL_PICTURECONTROL* pPicture1Obj;
    GFX_GOL_PICTURECONTROL* pPicture3Obj;
    GFX_GOL_PICTURECONTROL* pPicture4Obj;
} HGC_OBJECTS;

extern HGC_OBJECTS hgcObj;

/******************************************************************************
  Function:
    void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg )

  Summary:
    This function sets up the Message System Service to route touch callbacks
    to the GOL message system  
 */
void GFX_HGC_TouchMessageCallback ( SYS_MSG_OBJECT *pMsg );


/******************************************************************************
  Function:
    void GFX_HGC_Setup ( void )

  Summary:
    This function sets up the GOL message callback and draw callbacks.  
 */
void GFX_HGC_Setup ( void );


/******************************************************************************
  Function:
    HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void )

  Remarks:
    This function returns the screen state
 */
HGC_SCREEN_STATES GFX_HGC_GetScreenState ( void );


/******************************************************************************
  Function:
    void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState )

  Remarks:
    This function sets the screen state machine to a new state
 */
void GFX_HGC_SetScreenState ( HGC_SCREEN_STATES newState );


/******************************************************************************
  Function:
    void GFX_HGC_Tasks (SYS_MODULE_OBJ gfxObject);

  Summary:
    This function is called in SYS_Tasks.  The intent wait until the GFX library
    is initialized before supplying items to draw
*/
void GFX_HGC_Tasks  (SYS_MODULE_OBJ gfxObject);


/******************************************************************************
  Function:
    void GFX_HGC_SchemeCreate ( void )

  Summary:
    Allocates memory for a new scheme
 */
GFX_GOL_OBJ_SCHEME *GFX_HGC_SchemeCreate(void);


/******************************************************************************
  Function:
    void GFX_HGC_InitializeSchemes ( void )

  Summary:
    Initializes all HGC-specified schemes
 */
void GFX_HGC_InitializeSchemes( void );


/******************************************************************************
  Function: 
    bool GFX_HGC_MESSAGECallback(uint16_t objMsg, GFX_GOL_OBJ_HEADER* pObj, GFX_GOL_MESSAGE* pMsg)

  Input: 
    objMsg - translated message for the object,
    pObj - pointer to the object,
    pMsg - pointer to the non-translated, raw GOL message

  Output: 
    If the function returns non-zero the message will be processed by default

  Remarks: 
    GFX_GOL_MESSAGECallback() function calls it each time the valid message for the GOL object is received.
 */
bool GFX_HGC_MessageCallback(GFX_GOL_TRANSLATED_ACTION objMsg, GFX_GOL_OBJ_HEADER *pObj, GFX_GOL_MESSAGE *pMsg);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawCallback( void )

  Output: 
    If the function returns non-zero the draw control will be passed to GOL

  Remarks: 
    GFX_GOL_Draw() function calls it each time when GOL objects drawing is 
    completed. HGC-specified draw data is grouped by screens states. It takes 
    two states to complete the drawing of each screen.  GFX GOL objects are drawn
    first and then GFX Primitives are drawn next to ensure primitives are not
    covered by GOL objects.
 */
bool GFX_HGC_DrawCallback( void );
/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_GOL( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX GOL objects are drawn here, grouped by screen.
    The draw order is reverse Z-ordered.
 */
bool GFX_HGC_DrawScreen_GOL(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawScreen_Primitives( uint8_t  screenId )

  Output:
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    HGC-specified GFX Primitives are drawn here, grouped by screen.
    GFX Primitives are drawn after GFX GOL Objects to make sure GFX GOL Objects
    do not cover GFX Primitives
 */
bool GFX_HGC_DrawScreen_Primitives(uint8_t screenId);


/******************************************************************************
  Function: 
    void GFX_HGC_SetupScreen( uint8_t  screenId )

  Remarks: 
    Clears current screen and starts a fresh screen with its background color
 */
void GFX_HGC_SetupScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_ChangeScreen( uint8_t  screenId )

  Output: 
    Returns true if a screenId matches an existing screen identifier

  Remarks: 
    Can be called to initiate GFX Library to draw a new screen
 */
bool GFX_HGC_ChangeScreen(uint8_t screenId);


/******************************************************************************
  Function: 
    bool GFX_HGC_DrawItem(int itemId)

  Output:
    Returns true if a itemId matches an existing item identifier

  Remarks: 
    Every item specified in every screen in HGC is listed in this function
 */
bool GFX_HGC_DrawItem(int itemId);


/******************************************************************************
  Function: 
    bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Button events
 */
bool GFX_HGC_MsgButtons(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgPictures(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Picture Control events
 */
bool GFX_HGC_MsgPictures(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Static Text events
 */
bool GFX_HGC_MsgStaticTexts(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj);

/******************************************************************************
  Function: 
    bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj)

  Output:
    Returns true if a Object ID matches an existing item identifier

  Remarks: 
    Handles GFX GOL Window events
 */
bool GFX_HGC_MsgWindows(uint16_t objMsg, GFX_GOL_OBJ_HEADER *pObj);

#endif // _GFX_HGC_DEFINITIONS_H
/*******************************************************************************
 End of File
*/
